CREATE INDEX IF NOT EXISTS workspace_documents_deletion_cleanup_due_idx
ON workspace_documents (max(COALESCE(json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.cleanupRetry.nextAttemptAt'),json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.requestedAt')),COALESCE(json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.cleanupRetry.leaseUntil'),0),COALESCE(json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.leaseUntil'),0)),id)
WHERE status='deletion_pending' AND json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.version')=1 AND json_type(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.requestedAt')='integer' AND json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.requestedAt')>0 AND json_type(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.requestedBy')='text' AND length(json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.requestedBy'))>0 AND json_type(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.deletion.originalRemoved') IN ('true','false');
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS workspace_documents_processing_cleanup_due_idx
ON workspace_documents (max(COALESCE(json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.cleanupRetry.nextAttemptAt'),json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.authorizedAt')),COALESCE(json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.cleanupRetry.leaseUntil'),0),COALESCE(json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.leaseUntil'),0)),id)
WHERE status<>'deletion_pending' AND extraction_status='complete' AND json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.version')=1 AND json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.stage')='complete' AND json_type(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.extraction')='object' AND json_type(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.authorizedAt')='integer' AND json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.authorizedAt')>0 AND json_type(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.authorizedBy')='text' AND length(json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.authorizedBy'))>0 AND json_type(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.noticeVersion')='text' AND length(json_extract(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.noticeVersion'))>0 AND (json_type(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.operation')='text' OR json_type(CASE WHEN json_valid(extracted_json) THEN extracted_json ELSE '{}' END,'$.processing.azureScan')='object');
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS audit_events_document_cleanup_started_idx
ON audit_events (organization_id,created_at DESC)
WHERE action='document.cleanup_retry.started';
