import { and, eq } from "drizzle-orm";
import { getDb, getRuntimeEnv } from "../../db";
import { integrationConnections, integrationSecrets } from "../../db/schema";
import { ApiError } from "../api";
import { decryptIntegrationSecret, encryptIntegrationSecret } from "./lightspeed";

export const MONERIS_PROVIDER = "moneris";
export const MONERIS_API_VERSION = "2026-08-14";
export const MONERIS_DEFAULT_SCOPE = "payment.read";
export type MonerisEnvironment = "sandbox" | "production";

export type MonerisCredentialInput = {
  environment: MonerisEnvironment;
  merchantId: string;
  clientId: string;
  clientSecret: string;
  scope: string;
};

export type NormalizedMonerisPayment = {
  externalPaymentId: string;
  externalSaleId: string;
  paymentTypeRef: string | null;
  paymentTypeName: string;
  category: "cash" | "card" | "gift_card" | "store_credit" | "other";
  amountCents: number;
  paidAt: string | null;
  sourcePayloadHash: string;
};

const text = (value: unknown) => typeof value === "string" ? value.trim() : "";

export function monerisReadiness() {
  const encryptionConfigured = Boolean(getRuntimeEnv().INTEGRATION_ENCRYPTION_KEY?.trim());
  return {
    adapterBuilt: true,
    credentialsConfigured: encryptionConfigured,
    missingConfiguration: encryptionConfigured ? [] : ["INTEGRATION_ENCRYPTION_KEY"],
    environment: "merchant_selected",
    permissions: ["Payments read only"],
    mode: "merchant_credentials_read_only" as const,
    dataPromotionEnabled: false,
  };
}

export function validateMonerisCredentialInput(value: Record<string, unknown>): MonerisCredentialInput {
  const environment = value.environment === "production" ? "production" : value.environment === "sandbox" ? "sandbox" : null;
  const merchantId = text(value.merchantId);
  const clientId = text(value.clientId);
  const clientSecret = text(value.clientSecret);
  const scope = text(value.scope) || MONERIS_DEFAULT_SCOPE;
  if (!environment) throw new ApiError(400, "MONERIS_ENVIRONMENT_INVALID", "Choose the Moneris sandbox or production environment.");
  if (!/^[A-Za-z0-9]{13}$/.test(merchantId)) throw new ApiError(400, "MONERIS_MERCHANT_ID_INVALID", "The Moneris merchant ID must contain exactly 13 letters or numbers.");
  if (clientId.length < 8 || clientId.length > 256) throw new ApiError(400, "MONERIS_CLIENT_ID_INVALID", "Enter the Application ID generated by Moneris.");
  if (clientSecret.length < 16 || clientSecret.length > 512) throw new ApiError(400, "MONERIS_CLIENT_SECRET_INVALID", "Enter the client secret generated by Moneris.");
  if (!/^[A-Za-z0-9._:\-/ ]{1,256}$/.test(scope)) throw new ApiError(400, "MONERIS_SCOPE_INVALID", "Enter only the read scope shown in the Moneris application.");
  return { environment, merchantId, clientId, clientSecret, scope };
}

function origin(environment: MonerisEnvironment) {
  return environment === "production" ? "https://api.moneris.io" : "https://api.sb.moneris.io";
}

export async function requestMonerisAccessToken(credentials: MonerisCredentialInput, fetcher: typeof fetch = fetch) {
  const response = await fetcher(`${origin(credentials.environment)}/oauth2/token`, {
    method: "POST",
    headers: { Accept: "application/json", "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "client_credentials",
      client_id: credentials.clientId,
      client_secret: credentials.clientSecret,
      scope: credentials.scope,
    }),
    signal: AbortSignal.timeout(15_000),
  });
  const body = await response.json().catch(() => ({})) as Record<string, unknown>;
  if (response.status === 429) throw new ApiError(503, "MONERIS_RATE_LIMITED", "Moneris is rate limiting this connection. Wait a moment and retry.");
  if (!response.ok) throw new ApiError(502, "MONERIS_CREDENTIALS_REJECTED", "Moneris did not accept these merchant credentials or scope.");
  const accessToken = text(body.access_token);
  if (!accessToken) throw new ApiError(502, "MONERIS_TOKEN_RESPONSE_INVALID", "Moneris returned an incomplete access-token response.");
  return { accessToken, expiresIn: Math.max(60, Number(body.expires_in) || 900) };
}

export async function saveMonerisCredentials(organizationId: string, connectionId: string, credentials: MonerisCredentialInput) {
  const now = new Date();
  const accessTokenCiphertext = await encryptIntegrationSecret(credentials.clientId);
  const refreshTokenCiphertext = await encryptIntegrationSecret(credentials.clientSecret);
  await getDb().insert(integrationSecrets).values({
    id: crypto.randomUUID(), organizationId, provider: MONERIS_PROVIDER, connectionId,
    accessTokenCiphertext, refreshTokenCiphertext,
    tokenExpiresAt: new Date("2099-01-01T00:00:00.000Z"), createdAt: now, updatedAt: now,
  }).onConflictDoUpdate({
    target: integrationSecrets.connectionId,
    set: { accessTokenCiphertext, refreshTokenCiphertext, tokenExpiresAt: new Date("2099-01-01T00:00:00.000Z"), updatedAt: now },
  });
}

export async function loadMonerisCredentials(organizationId: string, connectionId: string): Promise<MonerisCredentialInput> {
  const [row] = await getDb().select({
    merchantId: integrationConnections.externalAccountRef,
    environment: integrationConnections.domainPrefix,
    scopesJson: integrationConnections.scopesJson,
    clientId: integrationSecrets.accessTokenCiphertext,
    clientSecret: integrationSecrets.refreshTokenCiphertext,
  }).from(integrationConnections).innerJoin(integrationSecrets, and(
    eq(integrationSecrets.connectionId, integrationConnections.id),
    eq(integrationSecrets.organizationId, integrationConnections.organizationId),
    eq(integrationSecrets.provider, integrationConnections.provider),
  )).where(and(
    eq(integrationConnections.organizationId, organizationId),
    eq(integrationConnections.provider, MONERIS_PROVIDER),
    eq(integrationConnections.id, connectionId),
  )).limit(1);
  if (!row?.merchantId || (row.environment !== "sandbox" && row.environment !== "production")) {
    throw new ApiError(409, "MONERIS_NOT_CONNECTED", "Connect a Moneris merchant before synchronizing payments.");
  }
  let scope = MONERIS_DEFAULT_SCOPE;
  try { scope = text((JSON.parse(row.scopesJson) as unknown[])[0]) || scope; } catch { /* keep safe default */ }
  return {
    environment: row.environment,
    merchantId: row.merchantId,
    clientId: await decryptIntegrationSecret(row.clientId),
    clientSecret: await decryptIntegrationSecret(row.clientSecret),
    scope,
  };
}

function listPayload(body: unknown) {
  if (Array.isArray(body)) return body.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object"));
  if (!body || typeof body !== "object") return [];
  const object = body as Record<string, unknown>;
  for (const key of ["payments", "items", "data"]) {
    if (Array.isArray(object[key])) return object[key].filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object"));
  }
  return [];
}

function nextCursor(body: unknown) {
  if (!body || typeof body !== "object") return null;
  const object = body as Record<string, unknown>;
  const pagination = object.pagination && typeof object.pagination === "object" ? object.pagination as Record<string, unknown> : null;
  return text(object.next_cursor) || text(object.nextCursor) || text(object.cursor) || text(pagination?.next_cursor) || text(pagination?.nextCursor) || null;
}

export async function fetchMonerisPayments(
  organizationId: string,
  connectionId: string,
  options: { createdFrom: string; createdTo: string; cursor?: string | null; maxPages?: number; fetcher?: typeof fetch },
) {
  const credentials = await loadMonerisCredentials(organizationId, connectionId);
  const { accessToken } = await requestMonerisAccessToken(credentials, options.fetcher ?? fetch);
  const payments: Record<string, unknown>[] = [];
  let cursor = options.cursor ?? null;
  let pages = 0;
  const maximum = Math.min(Math.max(options.maxPages ?? 10, 1), 25);
  while (pages < maximum) {
    const url = new URL("/payments", origin(credentials.environment));
    url.searchParams.set("limit", "20");
    url.searchParams.set("created_from", options.createdFrom);
    url.searchParams.set("created_to", options.createdTo);
    if (cursor) url.searchParams.set("cursor", cursor);
    const response = await (options.fetcher ?? fetch)(url, {
      headers: {
        Accept: "application/json",
        Authorization: `Bearer ${accessToken}`,
        "Api-Version": MONERIS_API_VERSION,
        "X-Merchant-Id": credentials.merchantId,
        "X-Correlation-Id": crypto.randomUUID(),
      },
      signal: AbortSignal.timeout(15_000),
    });
    if (response.status === 429) throw new ApiError(503, "MONERIS_RATE_LIMITED", "Moneris is rate limiting payment history. Wait a moment and resume the sync.");
    if (!response.ok) throw new ApiError(502, "MONERIS_PAYMENTS_FAILED", "Moneris could not return this merchant's payment history.");
    const body = await response.json().catch(() => ({}));
    payments.push(...listPayload(body));
    pages += 1;
    const next = nextCursor(body);
    if (!next || next === cursor) { cursor = null; break; }
    cursor = next;
  }
  return { data: payments, cursor, pages };
}

function amountCents(value: unknown) {
  const candidate = value && typeof value === "object" ? (value as Record<string, unknown>).amount : value;
  const parsed = Number(candidate);
  if (!Number.isInteger(parsed) || parsed < 0 || parsed > 9_000_000_000) throw new Error("invalid amount");
  return parsed;
}

export async function normalizeMonerisPayment(payment: Record<string, unknown>): Promise<NormalizedMonerisPayment | null> {
  const status = (text(payment.paymentStatus) || text(payment.status)).toUpperCase();
  if (status && status !== "SUCCEEDED") return null;
  const externalPaymentId = text(payment.paymentId) || text(payment.id);
  if (!externalPaymentId) throw new Error("payment id missing");
  const transaction = payment.transactionDetails && typeof payment.transactionDetails === "object" ? payment.transactionDetails as Record<string, unknown> : {};
  const externalSaleId = text(payment.orderId) || text(transaction.orderId) || externalPaymentId;
  const paidAtRaw = text(payment.createdAt) || text(payment.processedAt) || text(payment.updatedAt) || text(transaction.createdAt);
  const paidAtDate = paidAtRaw ? new Date(paidAtRaw) : null;
  const paidAt = paidAtDate && !Number.isNaN(paidAtDate.getTime()) ? paidAtDate.toISOString() : null;
  const method = payment.paymentMethod && typeof payment.paymentMethod === "object" ? payment.paymentMethod as Record<string, unknown> : {};
  const methodName = text(method.type) || text(payment.paymentMethodType) || "Card";
  const sanitized = { externalPaymentId, externalSaleId, status: status || "SUCCEEDED", amountCents: amountCents(payment.amount), paidAt, methodName };
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(sanitized)));
  const sourcePayloadHash = [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
  return {
    externalPaymentId, externalSaleId,
    paymentTypeRef: methodName.toLowerCase(), paymentTypeName: methodName,
    category: methodName.toLowerCase().includes("gift") ? "gift_card" : methodName.toLowerCase().includes("credit") || methodName.toLowerCase().includes("debit") || methodName.toLowerCase().includes("card") ? "card" : "other",
    amountCents: sanitized.amountCents, paidAt, sourcePayloadHash,
  };
}
