import { getD1 } from "../../../../../db";
import { validateOnboardingDraft } from "../../../../../domain/onboarding-draft";
import { requireBillingAccess } from "../../../../../server/authorization";
import { ApiError,enforceRateLimit,handleApi,jsonResponse,readJsonObject,requireSameOrigin } from "../../../../../server/api";
async function contextFor(request:Request){const context=await requireBillingAccess(request,["owner"]);if(context.organization.setupComplete)throw new ApiError(409,"SETUP_COMPLETED","Business setup is already complete. Use Settings to change your business.");await getD1().prepare("DELETE FROM onboarding_drafts WHERE user_id=? AND coalesce(json_extract(draft_json,'$.organizationId'),'')<>?").bind(context.userId,context.organizationId).run();return context;}
async function expire(){await getD1().prepare("DELETE FROM onboarding_drafts WHERE user_id IN (SELECT user_id FROM onboarding_drafts WHERE expires_at<=? LIMIT 500)").bind(Date.now()).run();}
export async function GET(request:Request){return handleApi(request,async()=>{const c=await contextFor(request);await enforceRateLimit("setup-draft:read",c.userId,60,60);await expire();const row=await getD1().prepare("SELECT draft_json draft, revision, expires_at expiresAt FROM onboarding_drafts WHERE user_id=? AND expires_at>?").bind(c.userId,Date.now()).first<{draft:string;revision:number;expiresAt:number}>();return jsonResponse(row?{draft:validateOnboardingDraft(JSON.parse(row.draft)),revision:row.revision,expiresAt:row.expiresAt}:{draft:null,revision:0});});}
export async function POST(request:Request){return handleApi(request,async()=>{requireSameOrigin(request);const c=await contextFor(request);await enforceRateLimit("setup-draft:write",c.userId,60,3600);const body=await readJsonObject(request,32000);let draft;try{draft=validateOnboardingDraft(body.draft);}catch(e){throw new ApiError(400,"SETUP_DRAFT_INVALID",e instanceof Error?e.message:"Review this draft.");}if(!Number.isInteger(body.expectedRevision)||Number(body.expectedRevision)<0)throw new ApiError(400,"SETUP_DRAFT_REVISION","Reload your setup draft before saving.");await expire();const now=Date.now(),expires=now+48*3600000;const result=body.expectedRevision===0?await getD1().prepare("INSERT INTO onboarding_drafts(user_id,draft_json,revision,updated_at,expires_at) VALUES(?,?,1,?,?) ON CONFLICT(user_id) DO NOTHING RETURNING revision").bind(c.userId,JSON.stringify({...draft,organizationId:c.organizationId}),now,expires).first<{revision:number}>():await getD1().prepare("UPDATE onboarding_drafts SET draft_json=?,revision=revision+1,updated_at=?,expires_at=? WHERE user_id=? AND revision=? RETURNING revision").bind(JSON.stringify({...draft,organizationId:c.organizationId}),now,expires,c.userId,body.expectedRevision).first<{revision:number}>();if(!result)throw new ApiError(409,"SETUP_DRAFT_CHANGED","This draft changed in another session. Reload before saving over it.");return jsonResponse({revision:result.revision,expiresAt:expires});});}
export async function DELETE(request:Request){return handleApi(request,async()=>{requireSameOrigin(request);const c=await contextFor(request);await enforceRateLimit("setup-draft:discard",c.userId,60,3600);const body=await readJsonObject(request,1000);if(!Number.isInteger(body.expectedRevision)||Number(body.expectedRevision)<1)throw new ApiError(400,"SETUP_DRAFT_REVISION","Reload the saved draft before discarding it.");const deleted=await getD1().prepare("DELETE FROM onboarding_drafts WHERE user_id=? AND revision=? RETURNING user_id").bind(c.userId,body.expectedRevision).first<{user_id:string}>();if(!deleted)throw new ApiError(409,"SETUP_DRAFT_CHANGED","This draft changed in another session. Reload it before discarding it.");return jsonResponse({deleted:true});});}
