import assert from "node:assert/strict";
import test from "node:test";
import { createEnvironment, createReportWorkspace, dateOffset, dispatch } from "./helpers/retail-worker-fixture.mjs";
import { projectAdvisorBookloq } from "../domain/advisor-bookloq.ts";

test("built statement API enforces access, reviewed input, replay safety and historical-only reporting", { timeout: 120000 }, async () => {
  const { worker, environment, database, dispose } = await createEnvironment();
  try {
    const business = await createReportWorkspace(worker,environment,database,"statement");
    const { organizationId, userId, owner } = business;
    environment.BUCKET = { get: async key => key.startsWith(`${organizationId}:`) ? { customMetadata: { organizationId,securityState:"clean" } } : null };
    const send = (body) => dispatch(worker,environment,"/api/v1/bookloq/statements",{...owner,method:"POST",body});
    const list = () => dispatch(worker,environment,"/api/v1/bookloq/statements",owner);
    const withoutAddon = await list(); assert.equal(withoutAddon.status,403,"BookLoQ must be purchased before importing statements"); assert.equal((await withoutAddon.json()).error.code,"ADDON_NOT_INCLUDED");
    await database.prepare("INSERT INTO tenant_addons(id,organization_id,addon_key,status,created_at,updated_at) VALUES (?,?,'bookloq','active',1,1)").bind(crypto.randomUUID(),organizationId).run();
    const documentId = crypto.randomUUID();
    await database.prepare("INSERT INTO workspace_documents(id,organization_id,document_type,file_name,object_key,content_type,size_bytes,sha256_hex,security_state,status,scan_status,extraction_status,uploaded_by_user_id,created_at,updated_at) VALUES (?,?,'other','Test statement.pdf',?,'application/pdf',100,?,'clean','review_required','clean','complete',?,1,1)").bind(documentId,organizationId,`${organizationId}:${documentId}`,documentId,userId).run();
    const endDate = dateOffset(new Date().toISOString().slice(0,10),-1), startDate = dateOffset(endDate,-14);
    const input = { action:"preview",documentId,documentKindConfirmed:"bank_statement",newAccount:{name:"Main cash account",institutionName:"Test Bank",last4:"4321"},currency:"CAD",startDate,endDate,openingBalanceCents:100000,closingBalanceCents:125000,rows:[{postingDate:dateOffset(startDate,1),description:"Bank deposit",amountCents:40000},{postingDate:dateOffset(startDate,3),description:"Bank payment",amountCents:-15000}],sourceSystem:"plaid",journalEntryId:"untrusted-journal" };
    await database.prepare("UPDATE memberships SET role='manager' WHERE organization_id=? AND user_id=?").bind(organizationId,userId).run();
    assert.equal((await send(input)).status,403,"importing bank activity requires finance permissions");
    await database.prepare("UPDATE memberships SET role='owner' WHERE organization_id=? AND user_id=?").bind(organizationId,userId).run();
    assert.equal((await send({...input,documentId:"another-workspace-document"})).status,404);
    await database.prepare("UPDATE workspace_documents SET security_state='quarantined' WHERE id=?").bind(documentId).run();
    assert.equal((await send(input)).status,409,"unclean source documents cannot be imported");
    await database.prepare("UPDATE workspace_documents SET security_state='clean' WHERE id=?").bind(documentId).run();
    assert.equal((await send({...input,closingBalanceCents:125001})).status,400);
    assert.equal((await send({...input,rows:[{postingDate:startDate,description:"Foreign",amountCents:25000,currency:"USD"}]})).status,400);
    const previewResponse = await send(input); assert.equal(previewResponse.status,200,await previewResponse.clone().text());
    const preview = await previewResponse.json(); assert.equal(preview.preview.rowCount,2); assert.equal(preview.preview.differenceCents,0); assert.equal(preview.preview.demoRecord,false);
    assert.equal((await database.prepare("SELECT COUNT(*) count FROM financial_transactions WHERE organization_id=?").bind(organizationId).first()).count,0,"preview makes no financial changes");
    assert.equal((await send({...input,action:"confirm",previewFingerprint:preview.previewFingerprint})).status,409,"explicit review confirmation is required");
    assert.equal((await send({...input,action:"confirm",reviewConfirmed:true,previewFingerprint:"wrong"})).status,409,"confirmation must match preview");
    const confirmed = await send({...input,action:"confirm",reviewConfirmed:true,previewFingerprint:preview.previewFingerprint});
    assert.equal(confirmed.status,201,await confirmed.clone().text());
    const result = await confirmed.json(); assert.equal(result.postedToLedger,false);
    const records = await database.prepare("SELECT source_system,journal_entry_id,amount_cents,categorization_status FROM financial_transactions WHERE organization_id=?").bind(organizationId).all();
    assert.equal(records.results.length,2); assert.ok(records.results.every(row => row.source_system === "bank_statement" && row.journal_entry_id === null && row.categorization_status === "missing"));
    const repeatedPreview = await send(input); assert.equal((await repeatedPreview.json()).preview.rowCount,2);
    const replay = await send({...input,action:"confirm",reviewConfirmed:true,previewFingerprint:preview.previewFingerprint}); assert.equal(replay.status,200); assert.equal((await replay.json()).replayed,true);
    const bookloqResponse = await dispatch(worker,environment,"/api/v1/bookloq",owner); assert.equal(bookloqResponse.status,200,await bookloqResponse.clone().text());
    const bookloq = (await bookloqResponse.json()).bookloq;
    assert.equal(bookloq.cashActivity.days30.inflowCents,40000); assert.equal(bookloq.cashActivity.days30.outflowCents,15000); assert.equal(bookloq.summary.currentCashCents,null,"a statement closing balance is not live bank availability");
    assert.equal(bookloq.summary.revenueCents,null,"bank deposits do not create ledger revenue");
    assert.equal(bookloq.journals.length,0);
    const advisor = projectAdvisorBookloq({bookloq});
    assert.equal(advisor.status,"available"); assert.equal(advisor.ledgerAvailable,false);
    assert.equal(advisor.cashActivity[0].inflowCents,40000); assert.equal(advisor.cashActivity[0].outflowCents,15000); assert.equal(advisor.cashActivity[0].netCashFlowCents,25000);
    assert.equal(advisor.statements,null); assert.equal(advisor.values.revenueCents,null);
    assert.doesNotMatch(JSON.stringify(advisor),/Bank deposit|Bank payment|Test statement\.pdf|4321|Test Bank|untrusted-journal/);
    const catalog = await (await list()).json(); assert.equal(catalog.imports.length,1); assert.equal(catalog.accounts.length,1);
    await database.prepare("INSERT INTO integration_connections(id,organization_id,provider,status,external_account_ref,external_account_name,scopes_json,data_promotion_status,created_at,updated_at) VALUES (?,?,'plaid','connected','test-live-item','Test feed','[]','approved',1,1)").bind(crypto.randomUUID(),organizationId).run();
    const withPlaid = (await (await dispatch(worker,environment,"/api/v1/bookloq",owner)).json()).bookloq;
    assert.equal(withPlaid.cashActivity.days30.transactionCount,0,"approved Plaid suppresses statement activity until account mapping is reviewed");
    assert.equal((await (await list()).json()).statementCashEnabled,false);
    const undo = {action:"undo",importId:result.id,confirmation:"UNDO IMPORT",reason:"Correct the reviewed statement period"};
    assert.equal((await send({...undo,confirmation:""})).status,400);
    assert.equal((await send({...undo,reason:""})).status,400);
    assert.equal((await send({...undo,importId:"another-organization-import"})).status,404);
    await database.prepare("UPDATE financial_transactions SET reconciliation_status='matched' WHERE organization_id=?").bind(organizationId).run();
    assert.equal((await send(undo)).status,409,"matched downstream activity blocks undo atomically");
    assert.equal((await database.prepare("SELECT COUNT(*) count FROM financial_transactions WHERE organization_id=?").bind(organizationId).first()).count,2);
    await database.prepare("UPDATE financial_transactions SET reconciliation_status='unreconciled' WHERE organization_id=?").bind(organizationId).run();
    const undone = await send(undo); assert.equal(undone.status,200,await undone.clone().text()); assert.equal((await undone.json()).removedRows,2);
    assert.equal((await send(undo)).status,404,"a second undo cannot remove unrelated activity");
    assert.equal((await database.prepare("SELECT status FROM workspace_documents WHERE id=?").bind(documentId).first()).status,"review_required");
    assert.equal((await database.prepare("SELECT COUNT(*) count FROM bank_accounts WHERE organization_id=?").bind(organizationId).first()).count,1);
    const audit = await database.prepare("SELECT details_json FROM audit_events WHERE organization_id=? AND action='bank_statement.undone'").bind(organizationId).first(); assert.equal(JSON.parse(audit.details_json).reason,undo.reason);
    await database.prepare("UPDATE tenant_addons SET status='inactive' WHERE organization_id=? AND addon_key='bookloq'").bind(organizationId).run();
    const revoked = await list(); assert.equal(revoked.status,403,"revoked add-on access applies to existing imports too"); assert.equal((await revoked.json()).error.code,"ADDON_NOT_INCLUDED");
  } finally { await dispose(); }
});
