import test from "node:test";
import assert from "node:assert/strict";
import {buildForecast,normalizeForecastSettings,defaultForecastSettings,forecastLocation,shiftForecastDate,type ForecastLocation} from "../domain/forecasting.ts";
import {promotionScenario,inventoryProjection,capacityPlan,type PromotionPlan,type InventoryPlan} from "../domain/forecast-planning.ts";
import {forecastCashPreview,type CashAssumptions} from "../domain/forecast-cash.ts";
import {buildThirteenWeekCashFlow} from "../domain/thirteen-week-cash-flow.ts";
const issued="2026-09-30T16:00:00Z",today="2026-09-30";
function location():ForecastLocation{return {id:"a",name:"North",timezone:"America/Edmonton",currency:"CAD",settings:{...defaultForecastSettings(),hours:Array.from({length:7},()=>({open:true,from:"09:00",to:"17:00"})),reviewedAt:issued,reviewedFrom:shiftForecastDate(today,-364),reviewedThrough:shiftForecastDate(today,-1)},sourceIds:["a"],sourceCutoff:issued,blocked:[],days:Array.from({length:364},(_,i)=>({date:shiftForecastDate(today,i-364),status:"complete",transactions:10,units:20,netSalesCents:10000}))};}
test("reviewed zeros forecast zero; missing and partial dates withhold rather than filling zero",()=>{const l=location();l.days.forEach(d=>{d.transactions=0;d.units=0;});assert.equal(forecastLocation(l,7,issued).series.transactions.total,0);l.days.at(-1)!.status="missing";assert.equal(forecastLocation(l,7,issued).series.transactions.available,false);l.days.at(-1)!.status="partial";assert.equal(forecastLocation(l,7,issued).series.transactions.available,false);});
test("net returns preserve negative signed financial forecasts and zero MASE scale is undefined",()=>{const l=location();l.days.forEach(d=>d.netSalesCents=-5000);const s=forecastLocation(l,7,issued).series.netSalesCents;assert.equal(s.total,-35000);assert.equal(s.evaluation.mase,null);assert.equal(s.evaluation.mae,0);assert.equal(s.low,-35000);assert.equal(s.high,-35000);});
test("current partial day never trains the forecast; original results are reproducible",()=>{const l=location(),before=forecastLocation(l,7,issued);l.days.push({date:today,status:"partial",transactions:100000,units:50000,netSalesCents:9999999});const after=forecastLocation(l,7,issued);assert.deepEqual(after.series,before.series);assert.equal(after.observedToday?.transactions,100000);assert.deepEqual(forecastLocation(structuredClone(l),7,issued),after);});
test("source blocking, stockouts and a new operating regime do not fabricate coverage",()=>{const l=location();l.blocked=["Disconnected source"];assert.equal(forecastLocation(l,7,issued).series.units.available,false);l.blocked=[];l.days.at(-2)!.stockout=true;assert.equal(forecastLocation(l,7,issued).series.units.available,false);l.days.at(-2)!.stockout=false;l.settings.regimeFrom="2026-09-20";assert.equal(forecastLocation(l,7,issued).series.units.available,false);});
test("closures, unusual dates and local DST boundaries remain calendar dates",()=>{const l=location();l.settings.closures=["2026-10-01"];l.settings.unusualDates=["2026-10-02"];const s=forecastLocation(l,7,issued).series.transactions;assert.equal(s.points[0].value,0);assert.equal(s.points[0].workload,null);assert.equal(s.points[0].high,0);assert.equal(s.points[1].value,null);assert.equal(s.total,null);const dates=forecastLocation(location(),7,"2026-11-01T05:30:00Z").series.units.points.map(p=>p.date);assert.equal(new Set(dates).size,7);assert.equal(dates[0],"2026-11-01");});
test("company sums complete compatible locations only and never sums uncertainty bounds",()=>{const a=location(),b={...location(),id:"b"};const r=buildForecast([a,b],7,issued);assert.equal(r.totals.transactions,140);b.currency="USD";assert.equal(buildForecast([a,b],7,issued).totals.transactions,null);b.currency="CAD";b.blocked=["Missing channel"];assert.equal(buildForecast([a,b],7,issued).totals.transactions,null);});
test("rolling origins stay chronological and sparse series receive no made-up intervals",()=>{const l=location();l.days=l.days.slice(-35);const s=forecastLocation(l,7,issued).series.transactions;assert.equal(s.low,null);assert.equal(s.evaluation.rangeCoverage,null);assert.equal(forecastLocation(l,28,issued).series.transactions.available,false);});
const promotion:PromotionPlan={from:"2026-10-01",to:"2026-10-07",location:"North",channel:"Retail",lines:[{key:"a",name:"Test",baselineUnits:100,scenarioUnits:150,priceCents:1000,discountPercent:20,costCents:600,variableCents:0}],advertisingCents:5000,staffingCents:0,otherCents:0,displacedContributionCents:0,deferredContributionCents:0};
test("higher sales can reduce contribution; break-even preserves baseline after promotion costs",()=>{const r=promotionScenario(promotion);assert.equal(r.baseline.contributionCents,40000);assert.equal(r.scenario.salesCents,120000);assert.equal(r.scenario.contributionCents,25000);assert.equal(r.preserveContributionUnits,225);assert.equal(r.differenceCents,-15000);});
test("unknown costs withhold profit; unchanged promotions have exactly zero difference",()=>{const p=structuredClone(promotion);p.lines[0].costCents=null;assert.equal(promotionScenario(p).scenario.contributionCents,null);p.lines[0].costCents=600;p.lines[0].scenarioUnits=100;p.lines[0].discountPercent=0;p.advertisingCents=0;assert.equal(promotionScenario(p).differenceCents,0);p.lines[0].priceCents=10.1;assert.throws(()=>promotionScenario(p));});
const stock:InventoryPlan={start:"2026-10-01",units:0,reserved:0,demand:Array.from({length:7},(_,i)=>({date:shiftForecastDate("2026-10-01",i),units:i===1?10:0})),receipts:[{id:"a",date:"2026-10-05",units:10}],lots:[],pack:1,minimumUnits:0,minimumSpendCents:0,unitCostCents:100,cashCents:10000,storageUnits:100,leadDays:1,bufferUnits:0};
test("late receipts do not hide a preventable earlier stockout",()=>{const r=inventoryProjection(stock);assert.equal(r.firstStockout,"2026-10-02");assert.equal(r.reorderUnits,10);assert.equal(r.days.at(-1)?.closing,10);assert.equal(r.unmetUnits,10);});
test("missing demand is rejected; FEFO uses demand once and reservations cannot exceed stock",()=>{assert.throws(()=>inventoryProjection({...stock,demand:stock.demand.slice(1)}));assert.throws(()=>inventoryProjection({...stock,reserved:1}));const r=inventoryProjection({...stock,units:200,demand:[{date:stock.start,units:100}],receipts:[],lots:[{id:"a",units:100,expires:"2026-10-02"},{id:"b",units:100,expires:"2026-10-10"}]});assert.equal(r.days[0].closing,100);assert.equal(r.unmetUnits,0);});
test("cash caps cannot round orders below supplier minimum into valid orders",()=>{const r=inventoryProjection({...stock,pack:6,minimumUnits:12,cashCents:700});assert.equal(r.reorderUnits,null);const free=inventoryProjection({...stock,unitCostCents:0,minimumSpendCents:100});assert.equal(free.reorderUnits,null);});
test("capacity uses staff-hours and does not derive workload from sales dollars",()=>{assert.equal(capacityPlan({transactions:100,openHours:8,minimumStaff:2,transactionsPerStaffHour:10,fixedTaskHours:2})?.staffHours,16);assert.equal(capacityPlan({transactions:100,openHours:0,minimumStaff:2,transactionsPerStaffHour:10,fixedTaskHours:2}),null);});
const schedule=[{id:"invoice",dueDate:"2026-10-02",amountCents:100000,direction:"in" as const,certainty:"expected" as const,label:"Invoice"},{id:"bill",dueDate:"2026-10-01",amountCents:80000,direction:"out" as const,certainty:"confirmed" as const,label:"Bill"}];
const flow=buildThirteenWeekCashFlow({asOf:"2026-09-30",openingCashCents:50000,safetyThresholdCents:10000,actualTransactions:[],forecastItems:schedule});
const assumptions:CashAssumptions={additionalSalesConfirmed:true,cashSharePercent:100,feePercent:0,taxPercent:0,settlementDays:2,collectionDelayDays:7,volumeChangePercent:0,bufferCents:10000,additional:[]};
test("cash replaces invoice timing once, finds midweek deficits and never adds actuals again",()=>{const r=forecastCashPreview(flow,schedule,[],assumptions);assert.equal(r.lowestCents,-30000);assert.equal(r.lowestDate,"2026-10-01");assert.equal(r.daily.at(-1)?.balanceCents,70000);assert.ok(r.belowBufferDates.includes("2026-10-08"));assert.equal(r.flow.purchasingCapacityCents,flow.purchasingCapacityCents);});
test("cash excludes hypothetical sales until attested and fails closed on incomplete finance",()=>{assert.throws(()=>forecastCashPreview(flow,schedule,[],{...assumptions,additionalSalesConfirmed:false}));assert.throws(()=>forecastCashPreview({...flow,status:"needs_review"},schedule,[],assumptions));assert.throws(()=>forecastCashPreview(flow,schedule,[{date:"2026-10-01",netSalesCents:-100}],assumptions));});

test("adding complete history never revokes 28-day readiness at model-selection activation",()=>{for(const n of [105,112,119,126,133,140]){const l=location();l.days=l.days.slice(-n);assert.equal(forecastLocation(l,28,issued).series.transactions.available,true,String(n));}});

test("closed-day activity requires a schedule review and invalid event dates are rejected",()=>{const l=location();l.settings.hours[1].open=false;const result=forecastLocation(l,7,issued);assert.equal(result.series.transactions.available,false);assert.ok(result.series.transactions.reasons.some(r=>r.includes("closed-day")));assert.throws(()=>normalizeForecastSettings({...l.settings,closures:["2026-02-30"]}));});
