import type { Metadata } from "next";
import { LegalContactLink, LegalShell, PolicySection } from "../legal-shell";

export const metadata: Metadata = {
  title: "Privacy Policy | Vanteloq",
  description: "Learn how Vanteloq collects, uses, shares, protects, and retains personal information.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalShell eyebrow="PRIVACY POLICY" title="Your information should have a clear purpose." summary="This policy explains what Vanteloq handles, why it is needed, and the choices available to account holders and other individuals." updated="October 4, 2026">
      <PolicySection id="scope" title="1. Scope and accountability">
        <p>This Privacy Policy applies when you visit vanteloq.com, create or use a Vanteloq account, administer a workspace, connect a supported service, submit a form, or contact us.</p>
        <p>2855706 ALBERTA INC, doing business as LexEdge Consulting and operating Vanteloq, is responsible for personal information under its control. The privacy contact is the Vanteloq Privacy Officer through <LegalContactLink/>.</p>
        <p>Vanteloq follows Alberta’s <a href="https://www.alberta.ca/personal-information-protection-act">Personal Information Protection Act</a> and Canada’s <a href="https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/">Personal Information Protection and Electronic Documents Act</a> where each law applies.</p>
      </PolicySection>

      <PolicySection id="collection" title="2. Information we collect">
        <h3>Account and workspace information</h3>
        <p>We collect information you provide, such as your name, email address, password credentials handled by the authentication provider, business name, legal name, business contact details, role, location information, operating hours, and workspace settings.</p>
        <h3>Connected business information</h3>
        <p>Your business template, selected tools and priorities personalise onboarding and the workspace. Reviewed changes retain a dated configuration history. Changing a business type does not delete existing records, change accounting totals or grant additional subscription or role permissions.</p>
        <p>If you choose Save progress during setup, we retain the entered business profile, operating hours, business template, layout and current step in an account-scoped draft. Drafts exclude tax identifiers, passwords, payment details and legal acceptance. A draft expires after 48 hours and becomes unavailable; expired records are removed during subsequent draft housekeeping. Completing setup, discarding the draft or deleting the account also removes it. This is not a promise of immediate physical deletion from managed backups.</p>
        <p>Manual payroll accounting entries may contain aggregate wage costs, employer costs, payroll liabilities, and a reference to a customer-approved payroll report. The payroll screen does not connect to a payroll provider or collect employee bank instructions. Customers must limit entries to necessary accounting information and provide employees with any notices or other protections required for their use of the service.</p>
        <p>When an authorized workspace user connects a supported provider or imports records, Vanteloq may receive sales, payment, refund, product, inventory, customer, supplier, location, purchasing, finance, and operational records. The exact fields depend on the source, the permissions granted, and the import selected by the user.</p>
        <h3>Shopify privacy requests</h3>
        <p>When Shopify sends a verified customer data request for a previously authorized store, Vanteloq records the store, request identifier, customer identifier or email address, and requested order identifiers in an encrypted request scope. A generic task and notification alert an authorized workspace owner or administrator without including those customer identifiers. The private request workflow provides matching imported customer, sale, payment and staged-order records for local download. The operator must review other retained documents or communications, verify the recipient and deliver the response securely before confirming completion. Vanteloq does not automatically send the export to the customer.</p>
        <h3>Vehicle inventory</h3>
          <p>For dealerships that use vehicle inventory, Vanteloq stores the vehicle identifier or VIN, model year, make, model, workspace stock number, location, inventory status, acquisition date and any acquisition or reconditioning amounts the customer enters. Source, revision and access metadata support review and export. These records do not include customer finance applications or create accounting entries automatically. Vehicle identifiers can be associated with individuals in other records; enter only information needed for your authorized inventory work. Workspace deletion removes these inventory records. Removing an individual user preserves shared inventory with that user’s authorship removed where applicable.</p>
        <p>Dealership operations may also retain separate stock-acquisition episodes, ownership and preparation states, cost lines and approvals, reservations, delivered-sale and reversal records, sales-credit allocations, tasks, customer names and contact details, lead stages, follow-up dates and appointments entered by an authorised user. These are shared workspace operating records with location and permission restrictions, not credit applications or a dealer-management-system connection. Do not enter identity documents, social insurance numbers, credit scores or financing applications in these fields. Source references and change history support review; deleting an individual member does not erase shared transactions. Applicable workspace deletion removes these records. Customer correction or deletion requests can be directed to the Privacy Officer where a self-service control is unavailable.</p>
        <h3>Café and restaurant cost records</h3>
        <p>Recipe records include ingredient quantities, purchase costs, units, usable yields, portions, modifier mappings and source dates. Reviewed edits retain the versions saved from the time revision history is enabled; versions overwritten before that point are not reconstructed. Reviewed period records may contain inventory costs, sales, labour totals, waste and check counts. Payroll amounts require additional permissions. These records support operational comparisons and do not post journals, calculate employee pay or automatically change stock. They remain until applicable workspace deletion or an authorised retention process; no automatic age-based purge is established for these operating records.</p>
        <h3>Reviewed operating workflows and follow-up</h3>
        <p>Optional workflows retain the source references, quantities, amounts, dates, responsible people, review decisions and corrections entered by authorised users. Depending on your business tools, these may include supplier receipts, stock movements, lot actions, preparation batches, delivery and settlement records, vehicle funding checks, customer jobs and time costs, special orders, room readiness and reservation dates. Enter only information needed for the business task. These records are restricted to the permitted workspace and location. Manual references are not proof that a provider connection or external action has completed.</p>
        <p>Managed stock requires a reviewed opening count. Accepted receipts and explicitly approved preparation batches can change that separate stock ledger; reversals retain the original movements. These controls do not overwrite a connected POS or post accounting entries automatically. Reviewed operational changes retain dated revisions. Applicable workspace deletion removes these operating records and their revision history. Removing a member can leave shared business records with the member’s authorship removed. No automatic age-based purge is established for this operating history.</p>
        <p>BookLoQ collection follow-up can store contact notes, payment promises, dispute status and next actions linked to an invoice. Automatic reminders are off by default. Only the owner can authorise reminders for a real invoice and its saved recipient. Current access, recipient, invoice balance and delivery eligibility are checked again before a send. Opt-in owner briefings use operating hours, time zone, closures and quiet hours. Email delivery uses the configured mail provider; provider acceptance does not prove receipt or that the recipient read it. Delivery attempts, failures and acknowledgements are retained with the workspace to prevent duplicate sends and support review. Turning delivery off stops future eligible sends, but cannot recall a message already sent. A downloaded export or received email needs separate secure handling.</p>
          <h3>Google and Meta connections</h3>
        <p>After resource approval, detailed marketing reports may retrieve website traffic by channel, page and device; Search Console queries, pages, clicks, impressions and average positions; local Business Profile discovery measures and monthly search terms; and paid campaign measurements from Google Ads or Meta. Detailed report responses are not cached in Vanteloq&apos;s database. They are visible only within the user&apos;s permitted workspace and location scope. Refreshing a report does not change a campaign, publish content or grant new provider permissions. Meta paid-ad reporting does not include organic Facebook Page or Instagram insights.</p>
        <p>A Google or Meta connection remains unavailable for measurement until an authorized user selects the exact eligible account, property, or owned business location, assigns it organization-wide or to an owned workspace location, and approves a warning-free sample. Vanteloq may retain encrypted authorization credentials while the connection is active, the selected provider and resource identifiers, the chosen workspace scope, connection and sync status, and derived daily measurements with source and freshness details. We use that information only to provide the connected reporting and operational features requested by the workspace.</p>
        <p>For a selected Google Business Profile location, an authorized user may request the current review response queue. Review text, ratings, reviewer details, and reply content are fetched directly from Google for that request, are sent with a no-store response, and are not inserted into Vanteloq&apos;s database or aggregated into a customer profile. Vanteloq sends a reply to Google only after a user with marketing-management permission enters the reply and provides a separate, specific confirmation. Google remains the system of record for the review and reply.</p>
        <h3>Connected financial account information</h3>
        <p>When an authorized workspace owner chooses a bank connection, Vanteloq may use Plaid as a service provider to connect selected business accounts. Depending on the connection and consent shown, Vanteloq may receive account and institution names, masked account identifiers, account type, balances, transactions, transaction descriptions, pending or posted status, currency, provider item and account identifiers, and connection or sync status.</p>
        <p>Bank sign-in information entered in Plaid Link is handled by Plaid and the financial institution. Vanteloq does not receive the online banking credentials entered in that flow. When a Plaid connection is configured and an authorized workspace user completes the provider consent flow, the connection uses only the read-only data products disclosed in that flow and does not allow Vanteloq to move money. We use connected records for bookkeeping review, reconciliation, supported cash context, connection support, security, and audit evidence.</p>
        <h3>QuickBooks Online connection</h3>
        <p>When an owner or administrator chooses to connect QuickBooks Online, Vanteloq records the selected company identifier, company name, authorization status, encrypted refreshable credentials, and security or audit metadata. The current sandbox stage verifies the selected company but does not import ledger records or enable dashboard calculations. Before a future accounting import is enabled, Vanteloq will identify the accounting records requested, the mapping and reconciliation controls, and any additional review required.</p>
        <h3>Vanteloq AI information</h3>
        <p><strong>Vanteloq AI data use:</strong> Vanteloq AI handles business questions and app guidance in one conversation. With Workspace data enabled in AI Settings, answers may use permitted organization-wide BookLoQ ledger and cash summaries. Historical cash totals may include reviewed bank statement imports, with their reporting dates. Demonstration records, original documents and transaction descriptions are excluded from the automatic business summary. These summaries are kept separate from dated retail KPIs; raw ledger records and the identities in those records are not attached. With Workspace data disabled, business records are excluded, while your question, product guidance, limited personalization information and permitted recent conversation context may still be sent. Separately confirmed chat attachments follow the notice below. Changing Workspace data starts a new chat. A saved, current agreement must cover the selected data use before a request can be sent.</p>
        <p>When Workspace data is enabled and an authorized user accepts the current data-use notice and asks Vanteloq AI a question, Vanteloq sends OpenAI the question, product guidance, dated aggregate sales, profit, units, labour, inventory-value and accounts-payable metrics where the user has the corresponding permission, connected-source status and freshness, and permitted aggregate cash context. Users with marketing access may also include synchronized traffic, search and advertising totals from their approved sources, with reporting periods and data-coverage limits. Search queries, page addresses, Google Business Profile content, advertising amounts without verified currency, raw provider credentials, full account numbers, customer names, invoice or receipt files, and raw transaction records are excluded from the automated evidence summary. Do not include personal information or secrets in your question.</p>
        <p>Up to six recent conversation messages may be sent to OpenAI for a follow-up, including messages held in the open chat when conversation memory is off. Access is checked against the current user, workspace, permissions, subscription, consent and scope. A change in business figures does not by itself erase an authorized earlier conversation. Earlier replies are labelled as historical context and do not establish current accounting evidence. Open-chat context expires after a limited period and is rejected when its access or scope no longer matches. Starting a new chat clears that context. OpenAI is the current AI response provider.</p>
        <p>When conversation memory is enabled, Vanteloq stores the question, the generated explanation, a limited evidence summary, the model identifier, and conversation timestamps so the authorized user can continue the conversation. With memory off, new questions and replies are not saved in the Vanteloq chat database. Advisor records are scoped to that user and workspace.</p>
        <p>AI response and display preferences are saved separately from conversation memory. These choices include response length, explanation style, format, business priorities, text size and spacing. The preference controls do not accept a free-text personal profile. A request may send your selected preferences, workspace role, currency and time zone, and a validated first name from your account to personalize the reply. You can reset saved preferences in AI Settings. Saving a chat title stores that title with your private conversation.</p>
        <h3>Uploaded bank statements, invoices, receipts, and other documents</h3><p>Bank statements can supply historical bank movements after an authorized reviewer checks the account, dates, rows and opening-to-closing balance. Vanteloq retains the original document and import history. These imports do not automatically post journals, establish accounting profit or confirm today&apos;s available balance. Statement activity is withheld from combined cash reporting while an approved Plaid feed is active to avoid duplicate counting. Optional AI analysis receives only permitted dated aggregates under the current AI data-use agreement.</p>
        <p>When available, an authorized owner or administrator with BookLoQ can separately enable a private document forwarding address after accepting its storage notice. Cloudflare Email Routing processes incoming messages, and an Email Worker sends supported attachments to Vanteloq&apos;s private quarantine. Vanteloq records the unverified sender address, receipt time and duplicate-check references, but does not keep the email body. The address can be replaced or disabled. Forwarding does not authenticate the sender as a Vanteloq user and never starts scanning, extraction, AI analysis or accounting posting. Those actions retain their separate permissions and review steps.</p>
        <p>Forwarded originals follow the same document retention and deletion controls as uploaded originals. Deleting an original removes its sender address from the attachment receipt; a minimal receipt remains to prevent the same delivery from recreating the file. Failed uploads retain a private disposal reference until storage cleanup succeeds. Interrupted writes may require support review before cleanup can be confirmed. Cloudflare states that Email Routing does not store email content; this does not mean that Vanteloq&apos;s quarantined attachments, email-provider delivery metadata or copies in the sender&apos;s mailbox are not stored.</p>
        <p>When a user uploads a business document, we may collect the original file, file name, type, size, cryptographic duplicate-check value, uploader, upload time, document category, storage reference, review status, and links to related transactions or records. If document extraction is enabled, we may also process proposed supplier, customer, date, amount, tax, currency, line-item, confidence, and source-page fields. Extracted fields remain subject to human review.</p>
        <h3 id="linked-files">Private linked files</h3>
        <p>Where configured, a workspace owner may separately connect Google Drive and Sheets or Microsoft OneDrive. Google requests read access to Drive files; Microsoft requests read access to the signed-in user’s OneDrive files and continued access. These provider grants can cover more files than the owner selects in Vanteloq. Vanteloq uses that access to list supported files and import only the files and sheet tabs the owner selects. It does not edit the original files. These permissions are separate from marketing connections.</p>
        <p>Vanteloq stores encrypted connection credentials, file identifiers and names, source revision and refresh timestamps, encrypted Google Sheet table snapshots, and private PDF copies of selected documents. While the Linked Files panel is open and visible, it checks up to 2 enabled files per minute. This is not continuous background monitoring. Document copies enter quarantine and retain separate scanning, extraction and accounting review steps. A table or document refresh never automatically posts a journal or changes financial reports.</p>
        <p>You can pause a selected file, unlink it or disconnect the account. Unlinking removes the linked table snapshot. Disconnection removes local connection credentials and linked sources; you can also revoke the app in your Google or Microsoft account. Previously imported document copies and reviewed accounting records remain subject to their separate deletion and retention controls. Linked file content is not automatically sent to Vanteloq AI.</p>
        <h3>Service and security information</h3>
        <p>We may collect device and browser details, IP address, timestamps, authentication events, audit events, integration status, request identifiers, error details, and records of actions taken inside a workspace. This information supports sign-in, fraud prevention, troubleshooting, access control, and service reliability.</p>
        <h3>Website analytics</h3>
        <p>After a visitor explicitly allows analytics, Google Analytics may process page paths without URL query text, device and browser context, approximate region, timestamps, and configured interaction events. We use these measurements to understand public site use and improve navigation, content, and reliability. Advertising signals and ad personalization remain disabled, and Vanteloq does not intentionally send account details, form entries, contact details, or workspace records to visitor analytics.</p>
        <h3>Communications and billing information</h3>
        <p>We collect messages and support details that you send to us. Stripe provides subscription status, plan, billing contact, transaction identifiers, tax related checkout fields, and limited payment details. Stripe collects card information in its secure checkout. Vanteloq does not receive or store full card numbers.</p>
        <h3>Optional news and product updates</h3>
        <p>Newsletter enrolment is not offered during signup or onboarding. Creating an account, accepting our terms or contacting support does not subscribe you. Previously recorded preferences and unsubscribe controls remain available. We record the consent notice, your choice, verification time and limited hashed request evidence. Unverified signup choices expire after 7 days. You can turn updates off in Settings or use the unsubscribe link without signing in. Account and security messages are separate. When an account closes, we remove its newsletter recipient profile and keep only minimal keyed suppression and unlinked consent evidence needed to honor your choice and answer compliance questions.</p>
        <h3>Address validation and transactional email</h3>
        <p>Signup uses manual address fields. If a separate AddressComplete search is offered and you choose to use it, Vanteloq sends the address search text and country to Canada Post AddressComplete and receives address suggestions and the selected address result. When an authorized user sends an invoice email, Resend processes the recipient, sender, subject, message content, attachment, and delivery metadata for that requested delivery.</p>
      </PolicySection>

      <PolicySection id="use" title="3. How we use information">
        <p>We use information to:</p>
        <ul>
          <li>create, authenticate, secure, and administer accounts and workspaces;</li>
          <li>import, organize, reconcile, display, and analyze records selected by authorized users;</li>
          <li>store and review uploaded source documents, detect duplicate files, and support document extraction where that feature is enabled;</li>
          <li>provide reports, calculations, alerts, audit context, and operational workflows;</li>
          <li>use the selected AI provider, after separate affirmative acceptance, to explain verified aggregate business evidence and identify missing inputs;</li>
          <li>maintain integrations and show their connection or verification status;</li>
          <li>respond to support requests and service communications;</li>
          <li>protect the service, investigate misuse, and meet legal obligations;</li>
          <li>measure and improve the public website after the visitor allows optional analytics;</li>
          <li>improve reliability and usability using the service and security information described above; and</li>
          <li>send commercial electronic messages only with express or implied consent, or when an applicable CASL exception permits the message, with the required sender information and unsubscribe method;</li>
        </ul>
        <p>We do not sell personal information. We do not use workspace business data to create advertising profiles.</p>
      </PolicySection>

      <PolicySection id="authority" title="4. Consent and workspace authority">
        <p>We obtain consent where required and identify the purpose before or when information is collected. You may withdraw consent, subject to legal, security, and contractual limits. Withdrawal may prevent features that need the information from continuing to operate.</p>
        <p>A workspace customer decides which authorized users and supported sources are added. The customer is responsible for having the authority to provide business records and personal information to Vanteloq. If Vanteloq processes personal information for a customer, that customer remains responsible for its own notices, permissions, and legal obligations.</p>
        <h3 id="financial-connections">Financial-connection consent</h3>
        <p>Before Plaid Link opens, Vanteloq shows a separate financial-data authorization that names the requested data categories, each processing purpose, the read-only limitation, retention consequences, and withdrawal choices. The authorization is not preselected. An authenticated user must actively accept it, and Vanteloq records the workspace, user identifier, acceptance time, provider, data categories, purposes, and versions of this Privacy Policy and the authorization notice. Plaid then presents the eligible institutions, accounts, and provider-specific permissions in Plaid Link.</p>
        <p>A financial connection begins only after both steps are completed. A workspace owner can disconnect the connection, which stops scheduled access and causes stored provider access credentials to be revoked or deleted. The owner can then use the protected Plaid deletion control to delete unreviewed imports and remove bank/provider identifiers from accounting records that must remain. Approved, reconciled, or posted accounting fields and limited audit evidence may remain when needed for legal recordkeeping or a documented retention requirement.</p>
        <p>For Google and Meta, authorization alone does not approve measurement collection. An authorized workspace user must complete the provider resource and owned-location selection described above before measurement sync can begin. Disconnecting stops scheduled access and removes the local authorization credential even if the provider&apos;s remote revocation service is temporarily unavailable.</p>
        <p>Before QuickBooks authorization begins, Vanteloq shows a separate, unselected checkbox describing the company identity and future read only accounting categories, the purposes, the staging limitation, and the disconnection choice. Vanteloq records the workspace, user, provider, acceptance time, data categories, purposes, and notice versions. Intuit then presents its own company selection and authorization screen.</p>
        <p>Vanteloq&apos;s use and transfer of information received from Google APIs complies with the Google API Services User Data Policy, including its Limited Use requirements. Google data is used only to provide or improve the customer requested feature, is not sold, is not used for advertising, and is not transferred except to provide or secure the feature, comply with law, or as part of a transaction with appropriate safeguards.</p>
        <h3>Vanteloq AI data-use acceptance</h3>
        <p>Vanteloq AI uses OpenAI. Before the first request for a data-use purpose, the agreement starts unchecked. Your acceptance is saved for your account and workspace and checked against the current notice before each request. New chats and changes to conversation memory keep that agreement. Disabling Workspace data keeps business records out of the request while allowing app instructions and general financial or analytical guidance in the same assistant. You can decline the agreement or withdraw it in AI Settings to stop future AI requests while continuing to use other permitted workspace features. The workspace must have authority to use its imported records for this purpose; an employee agreement does not replace obligations to customers or staff.</p>
        <p>OpenAI API content is not used for training by default unless the account opts in. The Vanteloq application does not enable training; provider-account administrators must keep optional training and data-sharing settings disabled for business analysis. Requests disable stored Responses API objects, but this is not zero retention: provider abuse-monitoring logs may retain content for up to 30 days, with exceptions described by OpenAI. Additional provider caching and legal obligations may apply. Clearing a conversation in Vanteloq deletes its active application records; it does not erase provider safety logs. <a href="https://developers.openai.com/api/docs/guides/your-data">OpenAI data controls</a>.</p>
        <p>Optional chat attachments have a separate confirmation for each message. If you select a PDF, supported photo, TXT or CSV file and confirm sending it, its contents and filename are sent to OpenAI for that reply. This works separately from the Workspace data setting. Vanteloq processes these files in request memory and does not save them in Documents, file storage or chat history. The attached exchange, including its question and answer, is not saved even when conversation memory is enabled. It remains visible in the open chat until cleared or closed. Recent messages from that exchange may inform a follow-up while the open-chat context remains valid; the original file is not automatically attached again. Follow-ups using that attachment context also remain unsaved. OpenAI safety retention still applies, including exceptions for file and image inputs under its data controls. Structural file validation is not a malware-scan certification. Attach only files you are authorized to share, remove personal identifiers or secrets first, and verify extracted figures. Attaching a file does not import transactions or change accounting records. Use Documents and the reviewed import workflow for those tasks.</p>
        <p>The separate AI data-use notice describes the data categories, purpose, exclusions, conversation memory, and links to this Privacy Policy. Vanteloq records the workspace, user, provider, acceptance time, data categories, purposes, and versions of this Privacy Policy and the Advisor notice. A current agreement must cover the selected Workspace data setting. If no matching agreement exists, including after withdrawal or a notice-version change, Vanteloq asks for acceptance again before sending a request.</p>
        <p>Commercial electronic messages require express or implied consent, or an applicable CASL exception. A purchase, transaction, customer profile, or imported contact does not automatically establish consent to receive those messages. Customers remain responsible for determining which rule applies and for their notices, sender identification, contact information, unsubscribe controls, consent evidence, and suppression lists.</p>
      </PolicySection>

      <PolicySection id="sharing" title="5. When information is shared">
        <p>We may disclose information:</p>
        <ul>
          <li>to authorized users in the same workspace according to their roles and permissions;</li>
          <li>to providers that support hosting, authentication, security, email delivery, payments, support, and connected services;</li>
          <li>when an authorized user directs a connection, export, or disclosure;</li>
          <li>to investigate security incidents or enforce the Terms of Service;</li>
          <li>where required by law, court order, or lawful government request; or</li>
          <li>as part of a business transaction, subject to appropriate confidentiality and legal protections.</li>
        </ul>
        <p>Current infrastructure and product flows may involve Cloudflare for hosting and security, Supabase for authentication, Stripe for billing, Resend for authorized transactional email, Canada Post AddressComplete for address validation, Google Analytics after a visitor allows public website measurement, Plaid for a bank connection selected by an authorized workspace owner, OpenAI for a Vanteloq AI request affirmatively started by an authorized user, and the provider chosen by a workspace for another authorized integration. The current list and purposes appear in the <a href="/subprocessors">Subprocessor and Connected Service Notice</a>. Plaid also provides information about its handling of connected account data in its <a href="https://plaid.com/legal/#end-user-privacy-policy">End User Privacy Policy</a>.</p>
      </PolicySection>

      <PolicySection id="transfers" title="6. Processing outside Canada">
        <p>Some service providers may process or store personal information outside Canada. Cloudflare may process web traffic through its global network for hosting, delivery, and security. Supabase processes authentication information in the configured project region and may use subprocessors in other countries. Stripe may process billing and supported payment information in the United States and other countries outside Canada when configured. Plaid may process authorized financial-connection information in the United States and other countries identified in its privacy materials when configured. Google may process consented website analytics and authorized Google integration data in countries described in Google&apos;s service materials. OpenAI is the enabled Vanteloq AI provider. OpenAI may process authorized AI requests in the United States and other countries described in its service materials; Canadian-only processing has not been established. A customer-selected integration may also process authorization and synchronized records in countries disclosed by that provider.</p>
        <p>Information processed in another country may be subject to that country’s laws and lawful access rules. We assess providers and use contractual, technical, and organizational safeguards appropriate to the information and service. Contact the Privacy Officer through <LegalContactLink/> to ask about a current service-provider location or safeguards relevant to a specific connection.</p>
      </PolicySection>

      <PolicySection id="retention" title="7. Retention and deletion">
        <p>We keep information only as long as reasonably needed for the purposes described in this policy, to provide the service, protect the integrity of business records, meet legal requirements, resolve disputes, and maintain security or audit evidence.</p>
        <p>Retention periods vary by record type. Account, transaction, audit, and accounting records may need different periods. When information is no longer required, we delete it, anonymize it, or securely isolate it until deletion is completed. Backup copies may remain for a limited period before being overwritten.</p>
        <p>Provider access credentials are kept only while the connection is active and are revoked or deleted after disconnection. Scheduled collection then stops. After disconnecting Plaid, an owner can permanently delete unreviewed Plaid imports. For a transaction already approved, reconciled, or posted into a journal, the deletion workflow removes Plaid identifiers, pending links, and transaction descriptions while retaining the minimum accounting fields needed to preserve ledger integrity.</p>
        <p>After a Google or Meta disconnection, Vanteloq removes the local access credential and stops collection. Selected resource identifiers, derived measurements, and limited audit evidence are deleted or retained only for the documented service, security, legal, or workspace recordkeeping purposes described in this policy.</p>
        <p>After a QuickBooks disconnection, Vanteloq requests provider revocation, deletes the locally stored authorization credential, and stops access. Company references and limited audit evidence are deleted or retained only for the documented security, legal, or accounting recordkeeping purpose. A disconnection does not silently delete accounting entries that an authorized user later reviewed and posted.</p>
        <p>Disconnecting Shopify deletes locally stored credentials and stops collection. Imported records are retained under their applicable rules. The store domain, prior authorization date and limited connection audit evidence can remain to route subsequent privacy or uninstall events for those records. Local disconnection does not establish that the provider-side app grant has been revoked.</p>
        <p>Pending Shopify privacy requests retain their encrypted identifying scope until completion or applicable workspace deletion. The queue assigns a 30-day response due date for operator follow-up; reaching that date does not automatically send a response or delete the request. Explicit completion clears the encrypted scope while retaining the opaque request identifier, request hash, status, export counts and timestamps, completing user, response method and a hash of the operator’s fulfilment reference. This is an operator attestation, not independent proof of delivery. This limited evidence follows the documented privacy and audit purpose and retention review; no automatic age-based purge is established. Workspace deletion removes the queue. Downloaded export copies require separate secure handling and disposal by the authorized operator.</p>
        <p>Linked-file names, provider identifiers, revision metadata and encrypted sheet snapshots remain while the source is linked. Pausing stops refresh without deleting those records. Unlinking removes the linked source and its snapshot; disconnecting removes local credentials and all linked sources for that connection, while limited connection and audit metadata may remain for the documented purpose. Applicable account or workspace deletion removes its cloud-file connections and linked sources. Previously imported PDF copies and reviewed accounting records follow their separate document and accounting retention controls. Revoke the app in the provider account when provider-side access also needs to end.</p>
        <p>Conversation memory is off by default whenever you open Vanteloq AI. With memory off, Vanteloq does not save new question or answer content in its chat database, but up to six recent messages held in the open chat may still be sent for a permitted follow-up. If you enable memory, Vanteloq saves eligible new messages and can reopen your authorized saved chats. Changing memory starts a fresh chat. Your data-use choice is stored against your account and workspace, and is checked against the current notice before a request. You can withdraw it in AI Settings; it is not required again for every message while that choice remains valid. Turning memory off stops loading saved history and saving new messages; it does not delete chats already saved. Use Manage saved chats to delete one or all of your saved chats in the current workspace from the active application database. Conversations inactive for 90 days are deleted when you next use the Advisor or open saved-chat controls. A limited deletion audit event remains without question or answer content. Provider safety logs and managed backups follow their separate retention periods.</p>
        <p>Saved AI response and display preferences remain until reset or applicable account or workspace deletion. Vanteloq also keeps limited request identifiers, hashes, state and timestamps to prevent duplicate AI processing and support retries. Those retry records do not contain the question, answer, attached files or authorization tokens. Records older than 24 hours are removed when you next submit a request that uses this retry control; this is not a scheduled 24-hour purge.</p>
        <p>Our retention policy assigns quarterly operational reviews and at least annual policy renewal to the Privacy Officer, with additional review after a material provider, product, infrastructure, or legal change. These reviews must identify expired purposes, unresolved deletion requests, legal holds, and records eligible for deletion or de-identification. Review dates, outcomes and exceptions must be recorded; the policy schedule does not itself establish that a review or disposal has occurred. A verified legal hold suspends deletion only for the affected records and documented period.</p>
        <p>Imported bank transactions, approved accounting records, original invoices and receipts, corrections, and review history may need a longer period because they support the customer’s books or legal obligations. Customers should export required records before closing an account and should confirm their retention duties with a qualified professional.</p>
        <p>Unsubscribe and suppression information may be kept in a minimal form so that a prior marketing choice can continue to be honoured. Security, incident, and audit records may be kept for a documented period that is proportionate to the risk and any applicable legal requirement.</p>
        <p>Optional website analytics remains disabled unless the visitor allows it. A visitor can withdraw that choice through Cookie settings. Google Analytics retention is controlled through the applicable property settings and Google&apos;s deletion tools, subject to legal and operational requirements.</p>
        <h3>Self service account and workspace deletion</h3>
        <p>If the protected deletion control is unavailable, contact the Privacy Officer using the address below. We will verify the request, explain any required retention or technical limitation, and arrange the applicable deletion process. Do not send passwords, authenticator codes, or identity documents in an ordinary email.</p>
        <p>Authenticated users can open Settings, Account and login, or the <a href="/account/deletion">account deletion page</a>, to review protected deletion controls after recent multifactor authentication. A paid subscription is not required. A nonowner can remove their Vanteloq membership, personal profile, preferences and private Advisor history. A shared sign-in needed by another service is retained. Business records remain with anonymous authorship where needed for the customer&apos;s accounting, security or audit integrity. Ambiguous or suspended workspace relationships require verified assistance before deletion can proceed.</p>
        <p>A workspace owner can permanently delete the workspace and its memberships after disconnecting providers and exporting required records. Vanteloq verifies the deletion scope, obtains separate confirmations, cancels the Vanteloq Stripe subscription and customer, and removes workspace records, uploaded files, local credentials and memberships. Other members&apos; independent sign-in identities are not deleted by the owner&apos;s request. The requesting person&apos;s identity is removed only when it is not required by another workspace or the separate private console.</p>
        <p>A confirmed deletion uses an encrypted processing record so an interrupted request can be retried. The browser keeps a private deletion-session key for that purpose; it is not included in links or analytics. The status page distinguishes pending work from confirmed completion. Processing identifiers are cleared when completion is confirmed. The retry session expires after 30 days; unresolved requests then require verified assistance from the Privacy Officer.</p>
        <p>Deletion cannot remove records that Stripe, a connected provider, or another independent organization must retain under its own agreement or law. A pseudonymous receipt containing hashes, the deletion scope, result and general retained categories may be kept for 24 months. It does not contain the deleted name, email, workspace name, network address or provider account number. Hashes are not a guarantee of anonymity. Expired completed processing records and receipts are removed during privacy-request housekeeping. Backup copies and legally required records are subject to the managed retention cycle and any documented legal hold.</p>
      </PolicySection>

      <PolicySection id="security" title="8. Safeguards">
        <p>Vanteloq uses safeguards designed for the sensitivity of the information, including authenticated access, records separated and scoped by organization, role-based server permissions, protected provider authorization flows, encrypted credential storage, request controls, and recorded audit and security events for important actions.</p>
        <p>Production browser, API, authentication, webhook, and provider traffic uses HTTPS. Vanteloq&apos;s production change control requires the managed edge to reject protocol versions below TLS 1.2 before Plaid production access is enabled. Stored application data is encrypted at rest by the managed database platform. Plaid access tokens and provider item identifiers receive an additional application-level AES-GCM encryption layer under a hosted key that is not stored with the database record. Vanteloq does not place raw Plaid credentials in browser storage, source control, ordinary connection-status responses, or application logs.</p>
        <p>No online service can promise absolute security. Users must protect their credentials, use strong passwords, enable available account protections, and promptly report suspected unauthorized access.</p>
      </PolicySection>

      <PolicySection id="rights" title="9. Access, correction, and privacy requests">
        <p>You may ask to access or correct personal information under our control, subject to legal exceptions. You may also ask about how information was used or disclosed, withdraw consent where applicable, or raise a privacy concern.</p>
        <p>Workspace controls allow an authenticated user to permanently delete their account and allow an authorized owner to permanently delete the workspace after the warnings and confirmation steps described above. Other controls allow an owner to export records, disconnect a provider, or correct reviewable fields. A disconnection is not the same as deleting legally retained accounting records. We will explain any applicable limitation when responding to a verified request.</p>
        <p>Send a clear request through <LegalContactLink/>. Contact and custom plan forms collect your name, email address, optional phone number, business name when relevant, and the message you submit. Resend delivers these inquiries to our team so we can respond. Submitting a request does not enroll you in marketing. Avoid sending passwords, payment details, identity documents or customer records. We may need to verify your identity and authority before responding. If information is controlled by a Vanteloq customer, we may direct the request to that customer.</p>
        <p>If a concern is not resolved, you may contact the <a href="https://oipc.ab.ca/">Office of the Information and Privacy Commissioner of Alberta</a> or the <a href="https://www.priv.gc.ca/">Office of the Privacy Commissioner of Canada</a>, depending on which law applies.</p>
      </PolicySection>

      <PolicySection id="automation" title="10. Analysis and human review">
        <h3 id="dictation">Optional voice dictation</h3>
        <p>Dictation starts only after you choose Start dictation and your browser permits microphone access. Your browser or operating system may send audio to its speech-recognition service under that provider’s terms. Vanteloq does not record or upload audio. The resulting text appears in your message box for review and is sent to Vanteloq AI only when you send the message using the normal data-use controls. Dictation stops when you stop it, edit the message, leave the page, or reach 30 seconds or the 800-character message limit. Browser support and service availability vary.</p>
        <h3>Reviewing analysis and suggested actions</h3>
        <p>Vanteloq may organize records and produce calculations, alerts, or suggested next steps from available data. These outputs depend on the quality, completeness, timing, and definitions of the source records. Material business, financial, legal, tax, employment, or inventory decisions should be reviewed by an authorized person and, where appropriate, a qualified professional.</p>
        <p>Vanteloq AI explains a bounded evidence snapshot; it does not receive authority to post journals, send payments, change inventory, contact customers, or take another business action. The generated explanation can be inaccurate or incomplete and does not replace qualified accounting, tax, legal or investment advice. Vanteloq displays source dates and missing inputs, and an authorized person must review the explanation before relying on it.</p>
        <p>Document extraction can misread text, numbers, tax, dates, pages, suppliers, or other fields. Vanteloq keeps extracted values provisional until an authorized reviewer compares them with the original document. An extracted value is not an approved accounting entry, payment instruction, tax position, or professional conclusion.</p>
        <p>When configured, Scan and Read sends the selected file to Microsoft Azure Blob Storage and Defender for Storage for malware scanning, then Microsoft Azure Document Intelligence for extraction after a verified clean result. The action includes a specific processing notice, and Vanteloq records who authorized it and when. Processing uses the configured Azure regions. See the <a href="/subprocessors">service provider notice</a> for purposes, temporary retention and recovery copies. This action does not send the document to OpenAI or change accounting balances.</p>
        <p>If a customer uses Vanteloq activity, access, scheduling, task, or operational records to monitor employees, the customer is responsible for a reasonable business purpose, appropriate notice, lawful authority, proportional access, retention limits, and any consent or employment requirement. Vanteloq must not be used for covert surveillance or an automated employment decision.</p>
      </PolicySection>

      <PolicySection id="children" title="11. Business users and children">
        <p>Vanteloq is a business service for people authorized to act for an organization. It is not directed to children, and we do not knowingly collect personal information from children for their own use of the service.</p>
      </PolicySection>

      <PolicySection id="changes" title="12. Changes to this policy">
        <p>We may update this policy when the service, providers, or legal requirements change. We will post the revised policy with a new update date. If a change materially affects how personal information is used, we will provide additional notice or seek consent where required.</p>
      </PolicySection>
    </LegalShell>
  );
}
