/** Product guidance shared by the public help centre and the AI's trusted instructions. */
export const APP_HELP_TOPICS = [
  { id: "documents", title: "Upload and check a document", area: "Documents", steps: ["Open Documents from the main navigation to upload an invoice, receipt, bank statement, sales report or supplier document.", "Check Security state and Extraction beside the file. A quarantined upload cannot be downloaded or used as verified extracted evidence.", "A duplicate-file message means the existing copy is retained. Uploading a document does not post a journal or change sales totals."], limit: "Retail Evidence settings imports reviewed measurements, not PDFs. AI receives no file contents or per-file extraction records and cannot confirm extraction of a named file. Independent malware scanning and document extraction must be configured before that pipeline is available." },
  { id: "opportunity-reviews", title: "Review, snooze and follow up on opportunities", area: "Intelligence", steps: ["Open Intelligence, then Opportunities. Inspect the evidence and dates before choosing Start review.", "Use Follow-up & activity to add notes, monitor, snooze, resolve or dismiss a finding. Closed reviews remain available in Show > Saved reviews and can be reopened. Snoozed findings return to Needs attention when their review time arrives.", "Create action opens the existing action form with the saved evidence. Assign its owner and deadline there. Linked actions show their status in the review. Inspect report and Ask Vanteloq AI carry the saved reporting period and selected location."], limit: "Saved reviews require organization-wide location access and the original financial-data permissions. Evidence is a historical snapshot, not a current report. Reminders appear in the app, not by email. Resolving a review records the user's assessment, not a verified financial gain. The review list loads recent saved records." },
  { id: "custom-plan", title: "Request a custom subscription", area: "Plans", steps: ["Open Pricing, or Billing & subscription in your workspace, and choose Request a custom plan.", "Provide your contact details and business requirements, then confirm permission to reply and send the form.", "The team reviews your needs before any custom scope, price or checkout is agreed."], limit: "The inquiry does not change your subscription, collect payment or guarantee a requested integration. For privacy or product questions, use /contact." },
  { id: "ledger-review", title: "Inspect financial statement checks", area: "BookLoQ", steps: ["Open BookLoQ and select Overview, then expand Ledger review.", "Inspect debit-credit equality, the accounting equation, gross profit and recorded earnings. Differences use integer minor currency units.", "Review any difference against the original records before interpreting totals or proposing a correction."], limit: "These are arithmetic checks on cumulative posted balances. They do not establish complete records, bank reconciliation, correct tax treatment or an audit opinion. AI receives permitted aggregate checks and cash scenarios, not underlying private journals." },
  { id: "retail-intelligence", title: "Explain retail performance", area: "Intelligence", steps: ["Open Intelligence or Sales and apply the reporting dates and location.", "Use Why? for the recorded revenue bridge, Products for category and item-type rankings, Baskets for co-purchases, and Operations for hourly demand. Select a chart hour to inspect its totals.", "Choose Ask Vanteloq AI to carry the selected dates and location into a business-analysis question, or create a review task from an opportunity."], limit: "Pairs need at least three receipts; observed repeat rates use identified buyers only. Scores are transparent relative heuristics. Driver decompositions and associations do not prove causes." },
  { id: "retail-evidence", title: "Supply missing retail evidence", area: "Intelligence", steps: ["Open Evidence settings under Retail intelligence. Select inventory period totals, paid labour, loyalty enrollment or product classification and the correct approved source.", "Use the displayed CSV template. Review the reference IDs, reporting period, units and source record name. Unknown optional inputs stay blank. Inventory values and wage amounts use cents.", "Review and save the dataset. Saving replaces that source and period's existing dataset. Reload if another person changed it. For lot dates, open Inventory and choose Manage lots & expiry."], limit: "Stock turnover needs recorded COGS and opening/closing inventory cost. Paid-hour efficiency needs complete reviewed location hours. Enrollment data does not connect a rewards provider or grant rewards. Access and plan permissions apply." },
  { id: "first-records", title: "Connect your first source", area: "Getting started", steps: ["Open Integrations & data and choose your supported provider or CSV import.", "Connect the correct merchant account, map its locations and synchronize records.", "Review the imported records and reconciliation before approving a source for reporting. A connected account alone does not make its data reportable."], limit: "Provider availability, account approvals and your plan determine which connections can be used." },
  { id: "report-differences", title: "Understand a number that looks wrong", area: "Reports", steps: ["Check the selected location, reporting dates and data-through date on the dashboard.", "Open Data Quality and Integrations & data to review missing records, costs, sync status and source approval.", "Compare the same dates and location in the source system. Net sales exclude tax and reflect returns and discounts. Exclude test accounts from business reporting."], limit: "Missing costs are not zero. Gross profit is sales less product costs; it is not net business profit." },
  { id: "bookloq", title: "Use BookLoQ with Vanteloq AI", area: "BookLoQ", steps: ["Open BookLoQ from the finance navigation. Your workspace needs BookLoQ access and the appropriate finance permissions.", "Review transactions, bills, invoices and reconciliation. Post verified, balanced journals to establish ledger totals.", "Choose Ask Vanteloq AI, then ask about your permitted financial summaries. Select All locations for organization-wide BookLoQ analysis; ask app questions in the same conversation. Turn Workspace data off in AI Settings to ask without attaching business records."], limit: "AI explains permitted summaries. It cannot post journals, pay bills, file returns or verify missing records. Demonstration ledgers are excluded from live AI analysis." },
  { id: "cash", title: "Review cash and future commitments", area: "BookLoQ", steps: ["Open BookLoQ, then Cash Flow to review the available opening balance and dated obligations.", "Check source freshness, reconciliation, currency and whether receipts are confirmed or expected.", "Compare cash after known obligations with your safety threshold before committing to a purchase."], limit: "A bank balance is not spendable profit. Plaid sandbox connections are test connections, and this workspace does not initiate bank payments." },
  { id: "ai-privacy", title: "Control AI privacy and saved chats", area: "Vanteloq AI", steps: ["Ask Vanteloq AI about your business, financial concepts or how to use the app in one conversation. Review the data-use notice before sending.", "Use Settings to turn conversation memory on or off. Memory is off when you open Vanteloq AI; switching it starts a new chat.", "Delete saved chats in Settings. New chat clears the current conversation view and keeps previously saved chats until you delete them."], limit: "Workspace data in AI Settings controls whether permitted business summaries are attached. With it off, only your question, product guidance and optional matching history are sent. Provider retention and backups are described in the privacy policy." },
  { id: "team", title: "Give each teammate the right access", area: "Team", steps: ["Open Team and review each member's role and permitted locations.", "Grant only the data and actions needed for that person's work, including separate finance and payroll permissions.", "Ask the member to verify their invitation and complete required sign-in security."], limit: "AI uses the signed-in member's current permissions. It does not grant access to another user's chats or restricted locations." },
  { id: "marketing", title: "Read marketing results accurately", area: "Marketing", steps: ["Connect an available marketing provider and select the correct resource or property.", "Check each source's reporting period, synchronization status and coverage.", "Compare traffic and conversions at measured stages, then record a specific experiment and review its result."], limit: "Traffic alone does not establish revenue or causation. CAC and ROAS need supported cost and attributable customer or revenue evidence." },
  { id: "follow-through", title: "Turn an insight into work", area: "Actions", steps: ["Review the source and confidence behind an insight.", "Create a task in Action Centre with a responsible person, priority and clear next step.", "Record the decision and revisit the measurable result in Decision Journal or your business review."], limit: "AI suggestions do not execute actions automatically. Confirm and approve consequential actions yourself." },
] as const;

export const APP_HELP_INSTRUCTIONS = APP_HELP_TOPICS.map(topic => `${topic.title}: ${topic.steps.join(" ")} Limitation: ${topic.limit}`).join("\n\n");
