/** Product guidance shared by the public help centre and the AI's trusted instructions. */
export const APP_HELP_TOPICS = [
  { id: "retail-intelligence", title: "Explain retail performance", area: "Intelligence", steps: ["Open Intelligence or Sales and apply the reporting dates and location.", "Use Why? for the recorded revenue bridge, Products for category and item-type rankings, Baskets for co-purchases, and Operations for hourly demand. Select a chart hour to inspect its totals.", "Choose Ask Vanteloq AI to carry the selected dates and location into a business-analysis question, or create a review task from an opportunity."], limit: "Pairs need at least three receipts; observed repeat rates use identified buyers only. Scores are transparent relative heuristics. Driver decompositions and associations do not prove causes." },
  { id: "retail-evidence", title: "Supply missing retail evidence", area: "Intelligence", steps: ["Open Evidence settings under Retail intelligence. Select inventory period totals, paid labour, loyalty enrollment or product classification and the correct approved source.", "Use the displayed CSV template. Review the reference IDs, reporting period, units and source record name. Unknown optional inputs stay blank. Inventory values and wage amounts use cents.", "Review and save the dataset. Saving replaces that source and period's existing dataset. Reload if another person changed it. For lot dates, open Inventory and choose Manage lots & expiry."], limit: "Stock turnover needs recorded COGS and opening/closing inventory cost. Paid-hour efficiency needs complete reviewed location hours. Enrollment data does not connect a rewards provider or grant rewards. Access and plan permissions apply." },
  { id: "first-records", title: "Connect your first source", area: "Getting started", steps: ["Open Integrations & data and choose your supported provider or CSV import.", "Connect the correct merchant account, map its locations and synchronize records.", "Review the imported records and reconciliation before approving a source for reporting. A connected account alone does not make its data reportable."], limit: "Provider availability, account approvals and your plan determine which connections can be used." },
  { id: "report-differences", title: "Understand a number that looks wrong", area: "Reports", steps: ["Check the selected location, reporting dates and data-through date on the dashboard.", "Open Data Quality and Integrations & data to review missing records, costs, sync status and source approval.", "Compare the same dates and location in the source system. Net sales exclude tax and reflect returns and discounts. Exclude test accounts from business reporting."], limit: "Missing costs are not zero. Gross profit is sales less product costs; it is not net business profit." },
  { id: "bookloq", title: "Use BookLoQ with Vanteloq AI", area: "BookLoQ", steps: ["Open BookLoQ from the finance navigation. Your workspace needs BookLoQ access and the appropriate finance permissions.", "Review transactions, bills, invoices and reconciliation. Post verified, balanced journals to establish ledger totals.", "Choose Ask Vanteloq AI, then ask about your permitted financial summaries. Select All locations for organization-wide BookLoQ analysis; use App help for instructions without attaching business records."], limit: "AI explains permitted summaries. It cannot post journals, pay bills, file returns or verify missing records. Demonstration ledgers are excluded from live AI analysis." },
  { id: "cash", title: "Review cash and future commitments", area: "BookLoQ", steps: ["Open BookLoQ, then Cash Flow to review the available opening balance and dated obligations.", "Check source freshness, reconciliation, currency and whether receipts are confirmed or expected.", "Compare cash after known obligations with your safety threshold before committing to a purchase."], limit: "A bank balance is not spendable profit. Plaid sandbox connections are test connections, and this workspace does not initiate bank payments." },
  { id: "ai-privacy", title: "Control AI privacy and saved chats", area: "Vanteloq AI", steps: ["Choose a ready AI provider and review the data-use notice before sending a question.", "Use Settings to turn conversation memory on or off. Memory is off when you open Vanteloq AI; switching it starts a new chat.", "Delete saved chats in Settings. New chat clears the current conversation view and keeps previously saved chats until you delete them."], limit: "App help attaches product instructions, not workspace records. Business analysis sends permitted aggregate evidence. Provider retention and backups are described in the privacy policy." },
  { id: "team", title: "Give each teammate the right access", area: "Team", steps: ["Open Team and review each member's role and permitted locations.", "Grant only the data and actions needed for that person's work, including separate finance and payroll permissions.", "Ask the member to verify their invitation and complete required sign-in security."], limit: "AI uses the signed-in member's current permissions. It does not grant access to another user's chats or restricted locations." },
  { id: "marketing", title: "Read marketing results accurately", area: "Marketing", steps: ["Connect an available marketing provider and select the correct resource or property.", "Check each source's reporting period, synchronization status and coverage.", "Compare traffic and conversions at measured stages, then record a specific experiment and review its result."], limit: "Traffic alone does not establish revenue or causation. CAC and ROAS need supported cost and attributable customer or revenue evidence." },
  { id: "follow-through", title: "Turn an insight into work", area: "Actions", steps: ["Review the source and confidence behind an insight.", "Create a task in Action Centre with a responsible person, priority and clear next step.", "Record the decision and revisit the measurable result in Decision Journal or your business review."], limit: "AI suggestions do not execute actions automatically. Confirm and approve consequential actions yourself." },
] as const;

export const APP_HELP_INSTRUCTIONS = APP_HELP_TOPICS.map(topic => `${topic.title}: ${topic.steps.join(" ")} Limitation: ${topic.limit}`).join("\n\n");
