import {buildThirteenWeekCashFlow,type ThirteenWeekCashFlow,type ThirteenWeekCashFlowItem} from "./thirteen-week-cash-flow";
import {forecastDate,shiftForecastDate} from "./forecasting";
export type CashAssumptions={additionalSalesConfirmed:boolean;cashSharePercent:number;feePercent:number;taxPercent:number;settlementDays:number;collectionDelayDays:number;volumeChangePercent:number;bufferCents:number;additional:{id:string;dueDate:string;amountCents:number;label:string}[]};
export function forecastCashPreview(flow:ThirteenWeekCashFlow,schedule:ThirteenWeekCashFlowItem[],sales:{date:string;netSalesCents:number}[],a:CashAssumptions){
 if(flow.status!=="available"||flow.openingCashCents===null)throw new Error("Resolve the existing BookLoQ cash coverage checks before modelling cash scenarios.");
 if(!a.additionalSalesConfirmed)throw new Error("Confirm the future cash-sales assumption is additional to existing invoices, payouts and deposits.");
 if(![a.cashSharePercent,a.feePercent,a.taxPercent,a.settlementDays,a.collectionDelayDays,a.volumeChangePercent,a.bufferCents].every(Number.isFinite)||a.cashSharePercent<0||a.cashSharePercent>100||a.feePercent<0||a.feePercent>100||a.taxPercent<0||a.taxPercent>100||a.volumeChangePercent< -100||a.volumeChangePercent>1000||a.bufferCents<0||a.settlementDays<0||a.settlementDays>90||!Number.isInteger(a.settlementDays)||a.collectionDelayDays<0||a.collectionDelayDays>90||!Number.isInteger(a.collectionDelayDays))throw new Error("Check the cash timing, volume, tax, fee and buffer assumptions.");
 if(new Set(schedule.map(i=>i.id)).size!==schedule.length||new Set(sales.map(i=>i.date)).size!==sales.length||new Set(a.additional.map(i=>i.id)).size!==a.additional.length)throw new Error("Duplicate planning items require review.");
 if(sales.some(s=>!forecastDate(s.date)||s.date<=flow.asOf||!Number.isSafeInteger(s.netSalesCents)||s.netSalesCents<0))throw new Error("Only future non-negative eligible sales can be bridged. Model refunds and other payments as separate dated plans.");
 if(a.additional.some(i=>!forecastDate(i.dueDate)||i.dueDate<flow.asOf||!Number.isSafeInteger(i.amountCents)||Math.abs(i.amountCents)>1e12||!i.label.trim()))throw new Error("Every additional plan needs a valid date, description and amount.");
 const items:ThirteenWeekCashFlowItem[]=schedule.map(i=>({...i,dueDate:i.certainty==="expected"&&i.direction==="in"?shiftForecastDate(i.dueDate<flow.asOf?flow.asOf:i.dueDate,a.collectionDelayDays):i.dueDate}));
 for(const s of sales){const amountCents=Math.round(s.netSalesCents*(1+a.volumeChangePercent/100)*a.cashSharePercent/100*(1+a.taxPercent/100)*(1-a.feePercent/100));if(!Number.isSafeInteger(amountCents))throw new Error("Cash scenario exceeds the supported amount.");items.push({id:`forecast:${s.date}`,dueDate:shiftForecastDate(s.date,a.settlementDays),amountCents,direction:"in",certainty:"expected",label:"Additional future cash sales, owner assumptions"});}
 for(const i of a.additional)items.push({id:`plan:${i.id}`,dueDate:i.dueDate,amountCents:Math.abs(i.amountCents),direction:i.amountCents<0?"out":"in",certainty:"expected",label:i.label});
 const result=buildThirteenWeekCashFlow({asOf:flow.asOf,openingCashCents:flow.openingCashCents,safetyThresholdCents:a.bufferCents,actualTransactions:[],forecastItems:items,confirmedPurchasingObligationsCents:flow.confirmedPurchasingObligationsCents});
 let balance=flow.openingCashCents,lowest=balance,lowestDate=flow.asOf;const below:string[]=[],daily:{date:string;balanceCents:number}[]=[];
 for(let date=flow.asOf;date<=result.weeks.at(-1)!.weekEnd;date=shiftForecastDate(date,1)){balance+=items.filter(i=>(i.dueDate<flow.asOf?flow.asOf:i.dueDate)===date).reduce((sum,i)=>sum+(i.direction==="in"?i.amountCents:-i.amountCents),0);if(balance<lowest){lowest=balance;lowestDate=date;}if(balance<a.bufferCents)below.push(date);daily.push({date,balanceCents:balance});}
 return {flow:result,lowestCents:lowest,lowestDate,belowBufferDates:below,daily,salesThrough:sales.at(-1)?.date??null,excludedBeyondHorizon:items.filter(i=>i.dueDate>result.weeks.at(-1)!.weekEnd).length,boundary:"Owner scenarios, not statistical intervals. Future sales are included only through the sales forecast horizon. Tax collected is not spendable profit; add its dated remittance. Purchases, payroll and fixed processor charges require explicit plans if not already recorded. Daily closing balances can still hide intraday shortfalls. Purchasing authority is unchanged."};
}
