import type {IndustryId} from "./industry-templates";
import type {IndustryShowcase,WorkflowStep} from "./industry-showcase";
const step=(title:string,shortTitle:string,icon:string,metric:string,value:string,rows:[string,string][],outcome:string):WorkflowStep=>({title,shortTitle,description:outcome,icon,recordLabel:"Reviewed workflow",recordTitle:title,metric,value,context:"Fictional operational records · One sample location",rows,outcome});
export function industryOperationsShowcase(id:IndustryId):IndustryShowcase {
 const boundary="Illustrative operational review. Source entry and approval are required; this does not change a connected provider or post accounting entries.";
 const build=(title:string,description:string,workspace:string,steps:IndustryShowcase['steps']):IndustryShowcase=>({title,description,workspace,steps,boundary});
 if(id==="dealership")return build("Make the handover ready, not just the sale.","Keep funding, documents and holding costs alongside the vehicle's next step.","Funding & handover",[
  step("Review the funding","Funding","Cash","Still to confirm","CAD $4,000",[["Agreed amount","$24,000"],["Received funding","$20,000"],["Difference","$4,000"]],"Keep unreceived funds visible."),
  step("Check the holding cost","Holding","Inventory","Recorded daily cost","CAD $18",[["Days held","20"],["Daily cost","$18"],["Recorded holding cost","$360"]],"Use the rate you can support with records."),
  step("Clear the handover","Handover","Action Centre","Needs attention","Funding & documents",[["Preparation","Reviewed"],["Funding","Awaiting confirmation"],["Documents","One outstanding check"]],"Resolve the remaining checks before completing handover.")]);
 if(id==="cafe"||id==="restaurant")return build(id==="cafe"?"Turn a prep plan into a reviewed batch.":"Bring preparation and service into one review.","Plan quantities, record actual usage and approve the stock movement after review.","Prep & service",[
  step("Plan the next batch","Plan","Inventory","Planned output","24 portions",[["Expected demand","30 portions"],["Ready stock","6 portions"],["Preparation needed","24 portions"]],"Review demand and usable stock before preparing more."),
  step("Record what was used","Prepare","Operations","Actual output","23 portions",[["Planned output","24 portions"],["Actual output","23 portions"],["Shortfall","1 portion"]],"Use actual ingredient quantities and the output count."),
  step("Approve the movement","Review","Action Centre","Approval","Ready to review",[["Ingredients","Deduct from managed stock"],["Output","Add to managed stock"],["Correction","Retain a reversal trail"]],"The separate stock ledger changes only after approval.")]);
 if(id==="services")return build("See the work that has not reached an invoice.","Keep approved scope, actual time, direct costs and linked invoices together.","Client jobs",[
  step("Confirm the scope","Scope","Operations","Approved quote","CAD $2,000",[["Original scope","$1,800"],["Approved change","$200"],["Quote total","$2,000"]],"Separate approved changes from the original promise."),
  step("Review time and cost","Work","Reports","Direct cost","CAD $700",[["10 hours at $50 cost","$500"],["Direct expenses","$200"],["Total direct cost","$700"]],"Missing time costs remain unknown."),
  step("Follow the remaining balance","Collect","BookLoQ","Invoice balance","CAD $600",[["Linked invoice","$2,100 incl. tax"],["Allocated payments","$1,500"],["Outstanding","$600"]],"Track the next collection action from the actual invoice.")]);
 if(id==="hospitality")return build("Keep the room and the stay ready.","Review manually recorded availability, room readiness, arrival and departure in one place.","Rooms & stays",[
  step("Record the stay","Reservation","Operations","Stay","3 nights",[["Arrival","October 8"],["Departure","October 11"],["Availability","Check each occupied night"]],"Reviewed stays reserve their room nights against overlaps."),
  step("Review the room","Readiness","Action Centre","Room status","Needs inspection",[["Cleaning","Recorded complete"],["Inspection","Pending"],["Arrival","Not checked in"]],"Complete readiness checks before recording arrival."),
  step("Review departure","Departure","BookLoQ","Folio balance","CAD $120",[["Recorded charges","$720"],["Recorded payments","$600"],["Difference","$120"]],"Resolve the recorded balance and departure checks. No PMS connection is implied.")]);
 if(id==="furniture")return build("Keep the customer promise with the order.","Track the special order from deposit and purchasing through arrival and delivery.","Orders & delivery",[
  step("Confirm the order","Order","Sales","Customer order","CAD $2,400",[["Agreed total","$2,400"],["Recorded deposit","$600"],["Remaining balance","$1,800"]],"A deposit is not the full collected order value."),
  step("Check the arrival","Supplier","Inventory","Supplier status","Awaiting arrival",[["Purchase order","Linked source"],["Promised delivery","Recorded date"],["Received quantity","Review on arrival"]],"Keep supplier and customer promises separate."),
  step("Finish the delivery","Deliver","Action Centre","Final review","Balance & handover",[["Goods received","Confirm"],["Final balance","Confirm payment"],["Customer delivery","Retain reference"]],"Complete the order with delivery evidence and the remaining balance.")]);
 if(id==="ecommerce")return build("Follow the order all the way to the bank.","Review order contribution and explain payout deductions without counting revenue twice.","Order contribution & payouts",[
  step("Review the order","Order","Sales","Net order revenue","CAD $85",[["Item sales","$100"],["Refund","−$20"],["Shipping charged","+$5"]],"Keep refunds, recoverable stock and shipping separate."),
  step("Include the variable costs","Costs","Reports","Contribution","CAD $40",[["Net revenue","$85"],["COGS less recovered stock","−$30"],["Fees and shipping","−$15"]],"Contribution requires confirmed cost coverage. It is not net profit."),
  step("Explain the payout","Bank","Cash","Expected deposit","CAD $950",[["Provider sales","$1,100"],["Refunds","−$100"],["Provider fees","−$50"]],"Compare the expected amount with the recorded bank deposit.")]);
 if(id==="health"||id==="grocery")return build("Give each lot a clear next action.","Separate best-before quality review from expiration and record the action, quantity and recovery.","Lot actions",[
  step("Identify the lot","Trace","Inventory","Recorded lot","DEMO-LOT-04",[["Quantity","18 units"],["Date classification","Best before"],["Supplier reference","Recorded source"]],"A best-before date is not automatically an expiration date."),
  step("Review the action","Review","Action Centre","Action","Supplier return",[["Affected units","6"],["Action reference","Supplier confirmation"],["Planned units after return","12"]],"Use the supplier's actual instructions. Record the physical stock change separately."),
  step("Track the recovery","Recovery","BookLoQ","Recovery to review","CAD $72",[["Returned units","6"],["Confirmed unit cost","$12"],["Credit received","Awaiting evidence"]],"Keep an expected credit separate from received cash.")]);
 if(id==="clothing")return build("Find the variant and the return behind the total.","Review size-level availability, return reasons and the actual disposition of returned goods.","Variants & returns",[
  step("Inspect the variant","Variant","Inventory","Size M","2 units available",[["Style","Sample overshirt"],["Colour","Navy"],["Variant","Size M"]],"A style total can hide a missing size."),
  step("Record the return","Return","Sales","Return reason","Fit",[["Quantity","1 unit"],["Inspection","Complete"],["Disposition","Resaleable"]],"Record inspection before treating a return as usable stock."),
  step("Review the pattern","Action","Reports","Next action","Check size demand",[["Return reason","Retained"],["Stock recovery","Separate reviewed count"],["Follow-up","Review comparable periods"]],"Use actual return evidence to guide the next buying review.")]);
 if(id==="other")return build("Make a recurring job easier to finish.","Choose a supported workflow, name an owner and retain the evidence for completion.","Your workflows",[
  step("Define the trigger","Trigger","Operations","Needs attention","Invoice mismatch",[["Workflow","Review a purchase"],["Condition","Amount differs from receipt"],["Owner","Operations manager"]],"Set a clear condition and next action."),
  step("Gather the evidence","Review","Documents","Required checks","2 of 3 complete",[["Purchase order","Checked"],["Goods receipt","Checked"],["Supplier credit","Pending"]],"Keep missing evidence visible."),
  step("Record the result","Outcome","Decision Journal","Observed result","Credit confirmed",[["Resolution","Supplier credit"],["Evidence","Saved reference"],["Next action","Review next invoice"]],"Retain the outcome and previous versions.")]);
 return build("Reorder with the constraints in view.","Review demand alongside supplier lead time, case packs, shelf life, storage and cash.","Stock & purchasing",[
  step("Review the requirement","Demand","Inventory","Unrounded requirement","38 units",[["Lead-time demand","40 units"],["Safety stock","10 units"],["Available less committed","12 units"]],"Check incoming stock and recorded demand before ordering."),
  step("Apply the supplier pack","Supplier","Suppliers","Pack-rounded quantity","48 units",[["Case size","12 units"],["Minimum order","24 units"],["Four cases","48 units"]],"Rounding can increase the cash and storage needed."),
  step("Check the constraints","Decision","Cash","Cash required","CAD $384",[["48 units × $8","$384"],["Storage and shelf life","Review capacity"],["Purchase","Requires your approval"]],"A recommendation stays unapproved until the constraints are reviewed.")]);
}
