"use client";
import { useEffect, useId, useRef, useState } from "react";
import { apiFetch } from "./supabase-browser";
import { bookloqRequest } from "./bookloq-request";
import FinanceChart from "./finance-chart";
import { formatBookloqMoney } from "../domain/bookloq-presentation";
import { normalizeCollectionsPreferences, type CollectionsDashboard, type CollectionsPreferences, type CollectionKind, type CollectionBucket, type CollectionsFilter, type OpenCollectionRecord } from "../domain/collections-dashboard";
import "./bookloq-collections.css";
import { BookLoQCollectionsSkeleton } from "./bookloq-skeleton";

export type CollectionsPayload = { report: CollectionsDashboard; records: OpenCollectionRecord[]; total: number; page: number; pageSize: number; demonstration: boolean };
const labels: Record<CollectionBucket, string> = { current: "Not overdue", "1-30": "1–30 days", "31-60": "31–60 days", "61-90": "61–90 days", "91+": "91+ days", undated: "No due date" };
const colours = ["#286ad6", "#568fc9", "#7368bc", "#a06594", "#bd5668", "#77869b"];
const widgetNames = { schedule: "Due-Date Timeline", aging: "Balance Ageing", actions: "Actions & Opportunities" };
const date = (value: string) => new Intl.DateTimeFormat("en-CA", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(value + "T00:00:00Z"));

export default function BookloqCollections({ refreshKey, navigate, initialPayload }: { refreshKey?: string; navigate: (section: "Invoicing" | "Bills" | "Cash Flow") => void; initialPayload?: CollectionsPayload }) {
  const id = useId().replaceAll(":", "");
  const [preferences, setPreferences] = useState(() => normalizeCollectionsPreferences(null));
  const [draft, setDraft] = useState(preferences), [customize, setCustomize] = useState(false), [saveStatus, setSaveStatus] = useState(""), [saving, setSaving] = useState(false);
  const [kind, setKind] = useState<CollectionKind>("receivable"), [filter, setFilter] = useState<CollectionsFilter>("all"), [query, setQuery] = useState(""), [search, setSearch] = useState(""), [page, setPage] = useState(0), [reload, setReload] = useState(0);
  const [payload, setPayload] = useState<CollectionsPayload | null>(initialPayload ?? null), [pending, setPending] = useState(!initialPayload), [error, setError] = useState(""), [selected, setSelected] = useState<string | null>(null);
  const scope = JSON.stringify([kind, filter, search, page, preferences.horizon, refreshKey, reload]);
  const [loadedScope, setLoadedScope] = useState(scope);
  const [requestedScope, setRequestedScope] = useState(scope);
  if (requestedScope !== scope) {
    setRequestedScope(scope); setPending(!initialPayload); setError(""); setSelected(null);
  }
  // Search and pagination only change the records, not the current summary.
  // Keep the controls mounted so a slow response does not steal keyboard focus.
  const sameReport = JSON.stringify(JSON.parse(loadedScope).slice(4)) === JSON.stringify([preferences.horizon, refreshKey, reload]);
  const recordsPending = !initialPayload && (pending || loadedScope !== scope);
  const data = initialPayload ?? (loadedScope === scope || sameReport ? payload : null);
  const recordsRef = useRef<HTMLElement>(null);
  useEffect(() => { const timer = setTimeout(() => { setSearch(query); setPage(0); }, 250); return () => clearTimeout(timer); }, [query]);
  useEffect(() => {
    let active = true;
    void bookloqRequest(apiFetch, "/api/v1/preferences").then(body => { if (active) { const next = normalizeCollectionsPreferences(body.dashboardPreferences?.collections); setPreferences(next); setDraft(next); } }).catch(() => { if (active) setSaveStatus("Default layout. Saved preferences could not be loaded."); });
    return () => { active = false; };
  }, []);
  useEffect(() => {
    if (initialPayload) return;
    const controller = new AbortController(); let active = true;
    const params = new URLSearchParams({ kind, filter, q: search, page: String(page), horizon: String(preferences.horizon) });
    void bookloqRequest(apiFetch, `/api/v1/bookloq/collections?${params}`, { signal: controller.signal }).then(body => { if (active) { setPayload(body); setLoadedScope(scope); } }).catch(reason => { if (active) { setError(reason instanceof Error ? reason.message : "Balances could not load."); setPayload(null); setLoadedScope(scope); } }).finally(() => { if (active) setPending(false); });
    return () => { active = false; controller.abort(); };
  }, [scope, kind, filter, search, page, preferences.horizon, initialPayload]);
  const inspect = (nextKind: CollectionKind, nextFilter: CollectionsFilter) => {
    setKind(nextKind); setFilter(nextFilter); setPage(0); setQuery(""); setSearch("");
    recordsRef.current?.scrollIntoView({ block: "start", behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth" });
    recordsRef.current?.focus({ preventScroll: true });
  };
  const save = async () => {
    setSaving(true); setSaveStatus("");
    try { const body = await bookloqRequest(apiFetch, "/api/v1/preferences", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ collectionsPreferences: draft }) }); const next = normalizeCollectionsPreferences(body.dashboardPreferences?.collections); setPreferences(next); setDraft(next); setCustomize(false); setSaveStatus("Your layout is saved."); }
    catch (reason) { setSaveStatus(reason instanceof Error ? reason.message : "Your layout could not be saved."); }
    finally { setSaving(false); }
  };
  const report = data?.report;
  const money = (value: number | null) => formatBookloqMoney(value, report?.currency ?? "CAD");
  const aging = report?.[kind === "receivable" ? "receivables" : "payables"];
  let offset = 0;
  const widget = (key: CollectionsPreferences["widgets"][number]["id"]) => {
    if (!report) return null;
    if (key === "schedule") return <article key={key} className="bq-collection-panel bq-collection-schedule">
      <div className="bq-panel-heading"><div><span className="bq-collection-kicker">Plan the Next {report.horizon} Days</span><h3>Money Due In & Out</h3></div><button onClick={() => navigate("Cash Flow")}>Open Cash Plan ↗</button></div>
      <FinanceChart title="Due-Date Timeline" description="Bars show outstanding amounts due. The line tracks their cumulative difference, starting at zero." currency={report.currency} basisLabel="Due Dates" tableCaption="Outstanding document amounts grouped by due date. Cumulative difference starts at zero, not a bank balance or cash forecast." points={report.receivables.count + report.payables.count ? report.schedule.map(p => ({ label: date(p.from), detail: `${p.from} to ${p.to}`, values: [p.incomingCents, -p.outgoingCents, p.cumulativeCents] })) : []} series={[{ label: "Invoices Due", kind: "bar", color: "blue" }, { label: "Bills Due", kind: "bar", color: "coral" }, { label: "Cumulative Difference", kind: "line", color: "violet" }]} emptyMessage="Create an invoice or record a bill to see upcoming due dates."/>
      <p className="bq-collection-note">A due-date schedule, not a bank balance or cash forecast. Overdue, undated and disputed items stay in the review queue. Payment timing and bill approvals still need review.</p>
    </article>;
    if (key === "aging") return <article key={key} className="bq-collection-panel bq-collection-aging">
      <div className="bq-panel-heading"><div><span className="bq-collection-kicker">Follow the Balance</span><h3>Balance Ageing</h3></div></div>
      <div className="bq-collection-switch" role="group" aria-label="Ageing balance type"><button aria-pressed={kind === "receivable"} onClick={() => { setKind("receivable"); setFilter("all"); setPage(0); }}>Receivables</button><button aria-pressed={kind === "payable"} onClick={() => { setKind("payable"); setFilter("all"); setPage(0); }}>Payables</button></div>
      <div className="bq-collection-donut"><svg viewBox="0 0 180 180" role="img" aria-labelledby={`${id}-donut-title`}><title id={`${id}-donut-title`}>{kind === "receivable" ? "Receivables" : "Payables"} by days overdue. Select a labelled group below to inspect records.</title><circle cx="90" cy="90" r="68" stroke="#e5ebf3" strokeWidth="17" fill="none"/>{aging?.aging.map((bucket, index) => { const share = aging.totalCents ? bucket.cents / aging.totalCents * 100 : 0; const start = offset; offset += share; return <circle key={bucket.bucket} cx="90" cy="90" r="68" fill="none" stroke={colours[index]} strokeWidth="17" pathLength="100" strokeDasharray={`${share} ${100 - share}`} strokeDashoffset={-start} transform="rotate(-90 90 90)"/>; })}</svg><div><strong>{money(aging?.totalCents ?? 0)}</strong><span>Outstanding · {report.currency}</span></div></div>
      <div className="bq-aging-legend">{aging?.aging.map((bucket, index) => <button key={bucket.bucket} onClick={() => inspect(kind, bucket.bucket)}><i style={{ background: colours[index] }}/><span>{labels[bucket.bucket]}<small>{bucket.count} {bucket.count === 1 ? "record" : "records"}</small></span><strong>{money(bucket.cents)}</strong></button>)}</div>
    </article>;
    return <article key={key} className="bq-collection-panel bq-collection-actions"><div className="bq-panel-heading"><div><span className="bq-collection-kicker">Turn Balances Into Actions</span><h3>Where to Focus</h3></div><span className="bq-recorded-tag">From Your Records</span></div><div className="bq-focus-grid">
      <button onClick={() => inspect("receivable", "overdue")}><span className="bq-focus-icon">↗</span><span><b>{report.receivables.overdueCount ? "Follow Up on Overdue Invoices" : "Keep Collections on Track"}</b><strong>{money(report.receivables.overdueCents)}</strong><small>{report.receivables.overdueCount} overdue. Confirm disputes and payment evidence before contacting customers.</small></span><em>Review →</em></button>
      <button onClick={() => inspect("payable", "due")}><span className="bq-focus-icon">↙</span><span><b>Plan Upcoming Payments</b><strong>{money(report.payables.dueCents)}</strong><small>Overdue and due within {report.horizon} days. Check available cash and approvals before committing.</small></span><em>Review →</em></button>
      <button onClick={() => inspect("receivable", "all")}><span className="bq-focus-icon">◎</span><span><b>Customer Concentration</b><strong>{report.largestCustomer ? `${Math.round(report.largestCustomer.share * 100)}%` : "No Open Invoices"}</strong><small>{report.largestCustomer ? `${report.largestCustomer.contactName} holds ${money(report.largestCustomer.cents)} of outstanding receivables. Review exposure, not a prediction of default.` : "This view highlights reliance on one customer's outstanding balance."}</small></span><em>Inspect →</em></button>
    </div>{(report.undatedCents > 0 || report.payables.unapprovedCents > 0 || report.receivables.disputedCents + report.payables.disputedCents > 0) && <div className="bq-collection-review-flags">{report.undatedCents > 0 && <span>{money(report.undatedCents)} has no valid due date.</span>}{report.payables.unapprovedCents > 0 && <button onClick={() => inspect("payable", "unapproved")}>{money(report.payables.unapprovedCents)} needs bill approval →</button>}{report.receivables.disputedCents + report.payables.disputedCents > 0 && <span>{money(report.receivables.disputedCents + report.payables.disputedCents)} is disputed and excluded from the timeline.</span>}</div>}</article>;
  };
  return <section className={`bq-collections ${preferences.density}`} aria-labelledby={`${id}-heading`}>
    <header className="bq-collections-heading"><div><p className="bq-collection-kicker">BookLoQ · Cash & Collections</p><h2 id={`${id}-heading`}>Know What’s Owed. Plan What’s Next.</h2><p>Track outstanding invoices, manage bills and see where cash needs your attention.</p></div><div className="bq-collections-tools"><button onClick={() => { setDraft(preferences); setCustomize(!customize); }} aria-expanded={customize}>Customise View</button><button onClick={() => setReload(v => v + 1)} disabled={pending} aria-label="Refresh invoice and bill balances">↻ Refresh</button></div></header>
    {customize && <section className="bq-collection-customize" aria-label="Customise collections dashboard"><div><h3>Your Dashboard, Your Priorities</h3><p>Choose the cards, reading density and default planning horizon. Saved to your account.</p></div><div className="bq-customize-fields"><label>Planning Horizon<select value={draft.horizon} onChange={e => setDraft({ ...draft, horizon: Number(e.target.value) as 7 | 30 | 90 })}><option value="7">7 Days</option><option value="30">30 Days</option><option value="90">90 Days</option></select></label><label>Reading Density<select value={draft.density} onChange={e => setDraft({ ...draft, density: e.target.value as CollectionsPreferences["density"] })}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label></div>{draft.widgets.map((item, index) => <div className="bq-widget-choice" key={item.id}><label><input type="checkbox" checked={item.visible} onChange={e => setDraft({ ...draft, widgets: draft.widgets.map(w => w.id === item.id ? { ...w, visible: e.target.checked } : w) })}/>{widgetNames[item.id]}</label><button disabled={!index} aria-label={`Move ${widgetNames[item.id]} up`} onClick={() => { const items = [...draft.widgets]; [items[index - 1], items[index]] = [items[index], items[index - 1]]; setDraft({ ...draft, widgets: items }); }}>↑</button><button disabled={index === draft.widgets.length - 1} aria-label={`Move ${widgetNames[item.id]} down`} onClick={() => { const items = [...draft.widgets]; [items[index + 1], items[index]] = [items[index], items[index + 1]]; setDraft({ ...draft, widgets: items }); }}>↓</button></div>)}<div className="bq-collections-tools"><button onClick={() => setDraft(normalizeCollectionsPreferences(null))}>Restore Defaults</button><button className="bq-primary" disabled={saving} onClick={() => void save()}>{saving ? "Saving…" : "Save Layout"}</button></div></section>}
    {saveStatus && <p role="status" className="bq-collection-note">{saveStatus}</p>}
    {error && <div role="alert" className="bq-collection-error"><h3>Balances Are Unavailable</h3><p>{error}</p><button onClick={() => setReload(v => v + 1)}>Try Again</button></div>}
    {!data && !error && <BookLoQCollectionsSkeleton widgets={preferences.widgets}/>}
    {report && <><div className="bq-collections-context"><span><i/>As of {date(report.asOf)} · {report.currency} · Current document balances{data?.demonstration ? " · Fictional demonstration" : ""}</span><div role="group" aria-label="Collections planning horizon">{([7, 30, 90] as const).map(days => <button key={days} aria-pressed={preferences.horizon === days} onClick={() => { setPreferences({ ...preferences, horizon: days }); setPage(0); }}>{days} Days</button>)}</div></div>
    <div className="bq-collection-kpis">{[
      { title: "Accounts Receivable", value: report.receivables.totalCents, note: `${report.receivables.count} open invoices · Owed to you`, kind: "receivable" as const, filter: "all" as const, icon: "↗" },
      { title: "Overdue Receivables", value: report.receivables.overdueCents, note: `${report.receivables.overdueCount} invoices past their due date`, kind: "receivable" as const, filter: "overdue" as const, icon: "◷" },
      { title: "Accounts Payable", value: report.payables.totalCents, note: `${report.payables.count} open bills · Owed by you`, kind: "payable" as const, filter: "all" as const, icon: "↙" },
      { title: `Payables Due in ${report.horizon} Days`, value: report.payables.dueCents, note: "Includes overdue bills · Before approvals", kind: "payable" as const, filter: "due" as const, icon: "▤" },
    ].map(item => <button key={item.title} onClick={() => inspect(item.kind, item.filter)}><span>{item.title}<i aria-hidden="true">{item.icon}</i></span><strong>{money(item.value)}</strong><small>{item.note}</small><em>View Records <span aria-hidden="true">↗</span></em></button>)}</div>
    {(report.otherCurrencyCount > 0 || report.invalidCount > 0) && <p role="status" className="bq-collection-review-flags">{report.otherCurrencyCount} open records in other currencies and {report.invalidCount} invalid balances are excluded. Review source records before relying on the total.</p>}
    <div className="bq-collections-grid">{preferences.widgets.filter(w => w.visible).map(w => widget(w.id))}</div>
    <section className="bq-collection-panel bq-collection-records" ref={recordsRef} tabIndex={-1} aria-labelledby={`${id}-records`}><div className="bq-panel-heading"><div><span className="bq-collection-kicker">The Records Behind the Number</span><h3 id={`${id}-records`}>{kind === "receivable" ? "Open Invoices" : "Open Bills"}</h3></div><button onClick={() => navigate(kind === "receivable" ? "Invoicing" : "Bills")}>{kind === "receivable" ? "Manage Invoices" : "Review Bills"} ↗</button></div><div className="bq-collection-filters"><label>Record Type<select value={kind} onChange={e => { setKind(e.target.value as CollectionKind); setPage(0); setFilter("all"); }}><option value="receivable">Customer Invoices</option><option value="payable">Supplier Bills</option></select></label><label>Show<select value={filter} onChange={e => { setFilter(e.target.value as CollectionsFilter); setPage(0); }}><option value="all">All Outstanding</option><option value="overdue">Overdue</option><option value="due">Due in {report.horizon} Days + Overdue</option><option value="disputed">Disputed</option>{kind === "payable" && <option value="unapproved">Needs Approval</option>}{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Find a Record<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Name or reference"/></label></div>
    {recordsPending ? <div className="bq-collection-empty" role="status" aria-busy="true">Loading matching records…</div> : data?.records.length ? <><div className="bq-record-table-wrap"><table><thead><tr><th>Record & Contact</th><th>Due Date</th><th>Status</th><th>Outstanding</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{data.records.map(r => <tr key={`${r.kind}:${r.id}`}><td><b>{r.reference}</b><span>{r.contactName}</span></td><td>{r.daysOverdue !== null && r.dueDate ? date(r.dueDate) : r.dueDate ? "Invalid due date" : "Not set"}<small>{r.daysOverdue ? `${r.daysOverdue} days overdue` : ""}</small></td><td><span className={`bq-status-pill ${r.daysOverdue ? "overdue" : ""}`}>{r.status.replaceAll("_", " ")}</span></td><td><strong>{money(r.outstandingCents)}</strong></td><td><button aria-label={`View details for ${r.reference}`} onClick={() => setSelected(selected === r.id ? null : r.id)}>Details</button></td></tr>)}</tbody></table></div>{selected && data.records.filter(r => r.id === selected).map(r => <article className="bq-record-detail" key={r.id}><h4>{r.reference} · {r.contactName}</h4><dl><div><dt>Original Total, Including Tax</dt><dd>{money(r.totalCents)}</dd></div><div><dt>Recorded Payments</dt><dd>{money(r.paidCents)}</dd></div><div><dt>Remaining Balance</dt><dd>{money(r.outstandingCents)}</dd></div></dl><p>Source: BookLoQ {r.kind === "receivable" ? "customer invoice" : "supplier bill"}. {r.updatedAt ? `Record updated ${new Date(r.updatedAt < 1e12 ? r.updatedAt * 1000 : r.updatedAt).toLocaleDateString("en-CA")}.` : "Update time is unavailable."} {r.kind === "payable" ? `Approval: ${r.approvalStatus.replaceAll("_", " ")}.` : ""}</p><button onClick={() => setSelected(null)}>Close Details</button></article>)}<div className="bq-collection-pagination"><span>{data.page * data.pageSize + 1}–{Math.min((data.page + 1) * data.pageSize, data.total)} of {data.total} records</span><div><button disabled={data.page === 0} onClick={() => setPage(data.page - 1)}>Previous</button><button disabled={(data.page + 1) * data.pageSize >= data.total} onClick={() => setPage(data.page + 1)}>Next</button></div></div></> : <div className="bq-collection-empty"><h4>No Matching Open {kind === "receivable" ? "Invoices" : "Bills"}</h4><p>Try another filter or add a reviewed record. No sales, cash receipts or payments are inferred from this empty view.</p><button onClick={() => navigate(kind === "receivable" ? "Invoicing" : "Bills")}>{kind === "receivable" ? "Open Invoicing" : "Open Bills"} →</button></div>}
    </section><details className="bq-collection-definitions"><summary>How These Balances Are Calculated</summary><p>{report.boundary}</p><p>Ageing uses your business date and the due date. Due today is not overdue. This is a current snapshot, so changing the planning horizon never backdates balances or invents historical collection performance.</p><p>Refresh requested at {new Date(report.generatedAt).toLocaleTimeString("en-CA", { hour: "numeric", minute: "2-digit" })}. This is report generation time, not a claim that a bank or provider just synced.</p></details></>}
  </section>;
}
