"use client";
import { useId, useState } from "react";
import { bookloqDemo } from "../domain/bookloq-demo";
import ProductBrandLogo from "./product-brand-logo";

const money = (cents: number | null) => cents === null ? "Unavailable" : new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD", maximumFractionDigits: 0 }).format(cents / 100);
export default function BookloqDemo() {
  const id = useId();
  const [purchase, setPurchase] = useState(6000), [delayed, setDelayed] = useState(false), [missing, setMissing] = useState(false);
  const cash = bookloqDemo(purchase * 100, delayed, missing);
  const low = cash.weeks.reduce<number | null>((lowest, week) => week.conservativeClosingCashCents === null ? lowest : Math.min(lowest ?? Infinity, week.conservativeClosingCashCents), null);
  return <div className="bookloq-demo"><div className="bookloq-demo-intro"><ProductBrandLogo product="bookloq"/><div><h3>Can this business afford new stock?</h3><p>Follow a fictional business with $30,000 opening cash, $12,000 of known bills and a $10,000 safety reserve.</p></div></div><div className="demo-scenario"><div><span className="demo-scenario-badge">SAMPLE BOOKLOQ DECISION</span><h3>Test the commitment.</h3><label htmlFor={`${id}-purchase`}>Proposed stock purchase <output>{money(purchase * 100)}</output></label><input id={`${id}-purchase`} type="range" min="0" max="20000" step="500" value={purchase} onChange={event => setPurchase(Number(event.target.value))}/><div className="demo-range-labels"><span>$0</span><span>$20,000</span></div><label className="demo-check"><input type="checkbox" checked={delayed} onChange={event => setDelayed(event.target.checked)}/>A $7,000 expected receipt arrives in August</label><label className="demo-check"><input type="checkbox" checked={missing} onChange={event => setMissing(event.target.checked)}/>Opening bank evidence is unavailable</label><p>Expected receipts appear only in the planning case. The conservative case uses confirmed obligations and excludes uncertain money.</p><button type="button" onClick={() => { setPurchase(6000); setDelayed(false); setMissing(false); }}>Reset cash scenario</button></div><aside aria-live="polite"><small>LOWEST CONSERVATIVE CASH</small><strong>{money(low)}</strong><p>{low === null ? "Restore verified opening cash before relying on this model." : low < 1_000_000 ? "This purchase takes cash below the sample safety reserve. Review the commitment." : "The model remains above the sample reserve after the listed obligations."}</p><dl><div><dt>Safety reserve</dt><dd>$10,000</dd></div><div><dt>Known bills</dt><dd>$12,000</dd></div><div><dt>Proposed purchase</dt><dd>{money(purchase * 100)}</dd></div></dl><p className="demo-model-limit">Illustrative sensitivity model. Unlisted costs and future sales are excluded. No order or payment is created.</p></aside></div><details className="bookloq-demo-detail"><summary>Inspect the 13-week cash plan</summary><div className="demo-table-scroll" tabIndex={0} role="region" aria-label="Scrollable thirteen-week sample cash plan"><table><caption>13-week cash plan, CAD. Actual future results may differ.</caption><thead><tr><th scope="col">Week beginning</th><th scope="col">Conservative closing cash</th><th scope="col">Planning closing cash</th></tr></thead><tbody>{cash.weeks.map(week => <tr key={week.weekStart}><td>{week.weekStart}</td><td>{money(week.conservativeClosingCashCents)}</td><td>{money(week.planningClosingCashCents)}</td></tr>)}</tbody></table></div></details><p className="demo-ai-disclosure">Calculated with BookLoQ’s production cash-flow engine. Vanteloq AI in the signed-in app can explain permitted summaries; this demo does not call an AI provider.</p></div>;
}
