"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { apiFetch } from "./supabase-browser";
import { BUSINESS_WORKFLOW_DEFINITIONS, businessWorkflowReport, validateBusinessWorkflow, type BusinessWorkflow, type BusinessWorkflowKind, type LinkedInvoice, type SavedBusinessWorkflow, type WorkflowField, type WorkflowReport } from "../domain/business-workflows";
import "./business-workflows.css";

type Item=SavedBusinessWorkflow&{report:WorkflowReport;invoices:LinkedInvoice[]};
type Data={locationId:string|null;locations:{id:string;name:string;currency:string;timezone:string}[];records:Item[];kinds:BusinessWorkflowKind[];canWrite:boolean;canReopen:boolean;canApproveOwnerReview:boolean;canExport:boolean;invoices:LinkedInvoice[];truncated:boolean};
type History={version:number;action:string;reason:string;recordedAt:number;snapshot:{record:BusinessWorkflow;state:string;version:number}};
const recordNouns:Record<BusinessWorkflowKind,string>={custom:"custom workflow",job:"job",settlement:"payout reconciliation",order_margin:"order contribution",outcome:"action outcome"};
function optionCaption(value:string){const label=value.replaceAll("-"," ");return label.charAt(0).toUpperCase()+label.slice(1);}
async function unpack(res:Response){const body=await res.json();if(!res.ok)throw Error(body.error?.message||"The workflow could not be loaded.");return body;}
function empty(kind:BusinessWorkflowKind,currency:string):BusinessWorkflow{const d=BUSINESS_WORKFLOW_DEFINITIONS[kind];return {kind,name:"",source:"",asOfDate:"",currency,values:Object.fromEntries(d.fields.map(f=>[f.key,f.type==="select"?f.options?.[0]??"":""])),groups:Object.fromEntries(d.groups.map(g=>[g.key,[]])),costCoverage:false,note:""};}
function Field({field,value,onChange,currency}:{field:WorkflowField;value:string;onChange:(v:string)=>void;currency:string}){
  return <label>{field.label}{field.type==="money"?` (${currency})`:""}{field.required?" *":""}{field.type==="select"?<select required={field.required} value={value} onChange={e=>onChange(e.target.value)}>{!field.required&&<option value="">Not recorded</option>}{field.options?.map(x=><option key={x} value={x}>{optionCaption(x)}</option>)}</select>:<input required={field.required} type={field.type==="date"?"date":"text"} inputMode={field.type==="money"||field.type==="number"?"decimal":undefined} maxLength={1000} value={value} onChange={e=>onChange(e.target.value)}/>} {field.hint&&<small>{field.hint}</small>}</label>;
}
function Report({report}:{report:WorkflowReport}){return <><dl className="business-workflow-metrics">{report.metrics.map(m=><div key={m.label} data-attention={m.attention||undefined}><dt>{m.label}</dt><dd>{m.value}</dd></div>)}</dl>{report.attention.length>0&&<ul className="business-workflow-attention">{report.attention.map(s=><li key={s}>{s}</li>)}</ul>}<p className="business-workflow-note">{report.boundary}</p></>;}
export default function BusinessWorkflows(props:{activeLocationId?:string|null;initialKind?:BusinessWorkflowKind}){return <WorkflowPanel key={props.activeLocationId??"all"} {...props}/>;}
function WorkflowPanel({activeLocationId=null,initialKind}:{activeLocationId?:string|null;initialKind?:BusinessWorkflowKind}){
  const [data,setData]=useState<Data|null>(null),[locationId,setLocationId]=useState(activeLocationId??""),[kind,setKind]=useState<BusinessWorkflowKind>(initialKind??"custom"),[filter,setFilter]=useState("active");
  const [draft,setDraft]=useState<BusinessWorkflow|null>(null),[editing,setEditing]=useState<Item|null>(null),[preview,setPreview]=useState<WorkflowReport|null>(null),[selected,setSelected]=useState<Item|null>(null),[history,setHistory]=useState<History[]|null>(null);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[reviewed,setReviewed]=useState(false),[reason,setReason]=useState(""),[reopening,setReopening]=useState(false);
  const read=useRef<AbortController|null>(null),formHeading=useRef<HTMLHeadingElement>(null),detailHeading=useRef<HTMLHeadingElement>(null),requests=useRef(new Map<string,string>()),recordId=useRef<string>("");
  const location=data?.locations.find(x=>x.id===(activeLocationId||locationId||data.locationId));
  const load=useCallback(async(focusId?:string)=>{read.current?.abort();const controller=new AbortController();read.current=controller;setError("");const params=new URLSearchParams();if(activeLocationId||locationId)params.set("locationId",activeLocationId||locationId);
    try{const body=await unpack(await apiFetch(`/api/v1/business-workflows?${params}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)])})) as Data;if(!controller.signal.aborted){setData(body);setKind(k=>body.kinds.includes(k)?k:body.kinds[0]??"custom");if(focusId)setSelected(body.records.find(r=>r.id===focusId)??null);}}
    catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Workflows could not be loaded.");}finally{if(!controller.signal.aborted)setLoading(false);}},[activeLocationId,locationId]);
  useEffect(()=>{let cancelled=false;void Promise.resolve().then(()=>{if(!cancelled)void load();});return()=>{cancelled=true;read.current?.abort();};},[load]);
  const hasDraft=Boolean(draft), selectedId=selected?.id;
  useEffect(()=>{if(hasDraft)formHeading.current?.focus();},[hasDraft]);
  useEffect(()=>{if(selectedId)detailHeading.current?.focus();},[selectedId]);
  const change=(next:BusinessWorkflow)=>{setDraft(next);setPreview(null);setReviewed(false);setMessage("");};
  function start(item?:Item){if(!location)return;setEditing(item??null);recordId.current=item?.id??crypto.randomUUID();setDraft(item?{kind:item.kind,name:item.name,source:item.source,asOfDate:item.asOfDate,currency:item.currency,values:{...item.values},groups:structuredClone(item.groups),costCoverage:item.costCoverage,note:item.note}:empty(kind,location.currency));setPreview(null);setSelected(null);setHistory(null);setReviewed(false);setMessage("");setError("");}
  async function mutate(action:string,item?:Item){if(busy||!location)return;setBusy(true);setError("");try{
    const content=action==="save"?validateBusinessWorkflow(draft):undefined;
    const body={id:item?.id??recordId.current,locationId:location.id,expectedVersion:item?.version??editing?.version??null,action,...(content?{record:content}:{}),reason:action==="reopen"?reason:"",reviewed};
    const key=JSON.stringify(body),requestId=requests.current.get(key)??crypto.randomUUID();requests.current.set(key,requestId);
    await unpack(await apiFetch("/api/v1/business-workflows",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,requestId}),signal:AbortSignal.timeout(20000)}));
    setDraft(null);setEditing(null);setPreview(null);setReviewed(false);setReason("");setReopening(false);setHistory(null);setMessage(action==="save"?"Draft saved. Source records and accounting balances were not changed.":action==="reopen"?"Reopened. The previous reviewed version remains in history.":"Workflow updated. The reviewed evidence is retained.");await load(body.id);
  }catch(e){setError(e instanceof Error?e.message:"The save could not be confirmed. Reload before retrying.");}finally{setBusy(false);}}
  function previewDraft(event:FormEvent){event.preventDefault();setError("");try{setPreview(businessWorkflowReport(validateBusinessWorkflow(draft),data?.invoices??[]));}catch(e){setError(e instanceof Error?e.message:"Review the entered fields.");}}
  async function showHistory(item:Item){setBusy(true);setError("");try{const body=await unpack(await apiFetch(`/api/v1/business-workflows?history=${encodeURIComponent(item.id)}`,{signal:AbortSignal.timeout(15000)}));setHistory(body.revisions);if(body.truncated)setMessage("Showing the 100 most recent revisions.");}catch(e){setError(e instanceof Error?e.message:"History could not be loaded.");}finally{setBusy(false);}}
  function exportRecord(item:Item){const blob=new Blob([JSON.stringify({record:item,history},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`vanteloq-workflow-${item.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const ownerReviewRequired=Boolean(selected?.kind==="custom"&&selected.values.approval==="owner-review"&&!data?.canApproveOwnerReview);
  const rows=data?.records.filter(r=>r.kind===kind&&(filter==="all"||filter==="completed"?filter==="all"||r.state==="completed":r.state!=="completed"))??[];
  return <section className="business-workflows" aria-label="Business workflows">
    <header><div><p className="business-workflow-eyebrow">Daily work</p><h2>From an issue to a result</h2><p>Keep the next action and its evidence together.</p></div>{data&&<button type="button" disabled={busy||Boolean(draft)} onClick={()=>void load(selected?.id)}>Refresh</button>}</header>
    {loading&&<p role="status" className="business-workflow-loading">Loading your saved workflows…</p>}{error&&<p role="alert" className="business-workflow-error">{error}</p>}{message&&<p role="status">{message}</p>}
    {!loading&&!data&&<button type="button" onClick={()=>void load()}>Try again</button>}
    {data&&<>
      {!activeLocationId&&<label className="business-workflow-location">Location<select disabled={busy||Boolean(draft)} value={locationId||data.locationId||""} onChange={e=>{setLocationId(e.target.value);setData(null);setSelected(null);setLoading(true);}}><option value="" disabled>Choose one location</option>{data.locations.map(l=><option key={l.id} value={l.id}>{l.name} · {l.currency}</option>)}</select></label>}
      <nav className="business-workflow-tabs" aria-label="Workflow types">{data.kinds.map(k=><button key={k} type="button" disabled={busy||Boolean(draft)} aria-pressed={kind===k} onClick={()=>{setKind(k);setSelected(null);setHistory(null);setReviewed(false);}}>{BUSINESS_WORKFLOW_DEFINITIONS[k].title}</button>)}</nav>
      <div className="business-workflow-toolbar"><p>{BUSINESS_WORKFLOW_DEFINITIONS[kind].description}</p><div><label>Show<select value={filter} disabled={busy} onChange={e=>setFilter(e.target.value)}><option value="active">Active</option><option value="completed">Completed</option><option value="all">All records</option></select></label>{data.canWrite&&<button className="business-workflow-primary" type="button" disabled={!location||busy||Boolean(draft)} onClick={()=>start()}>New record</button>}</div></div>
      {!draft&&!selected&&<div className="business-workflow-list">{rows.length?rows.map(r=><button className="business-workflow-record" type="button" key={r.id} onClick={()=>{setSelected(r);setReviewed(false);setHistory(null);setReopening(false);}}><span><strong>{r.name}</strong><small>{r.source} · {r.asOfDate}</small></span><span><span className="business-workflow-state" data-state={r.state}>{r.state}</span><small>{r.report.attention.length?`${r.report.attention.length} items to review`:r.state==="completed"?"Outcome recorded":"Open evidence"}</small></span></button>):<div className="business-workflow-empty"><h3>{location?"Start with one real record":"Choose a location"}</h3><p>{location?"Add the source and relevant amounts. Unknown costs stay visible, and each reviewed version is retained.":"Workflows and their currency belong to a specific location."}</p></div>}</div>}
      {selected&&!draft&&<article className="business-workflow-detail"><header><div><span className="business-workflow-state" data-state={selected.state}>{selected.state}</span><h3 ref={detailHeading} tabIndex={-1}>{selected.name}</h3><p>{selected.source} · Source date {selected.asOfDate} · Revision {selected.version}</p></div><button type="button" disabled={busy} onClick={()=>{setSelected(null);setHistory(null);}}>Close</button></header><Report report={selected.report}/>
        <details><summary>Inputs and source references</summary><dl className="business-workflow-evidence">{BUSINESS_WORKFLOW_DEFINITIONS[selected.kind].fields.map(f=><div key={f.key}><dt>{f.label}</dt><dd>{selected.values[f.key]||"Not recorded"}</dd></div>)}</dl>{BUSINESS_WORKFLOW_DEFINITIONS[selected.kind].groups.map(g=><div key={g.key}><h4>{g.label}</h4>{selected.groups[g.key].map((row,i)=><dl className="business-workflow-evidence" key={i}>{g.fields.map(f=><div key={f.key}><dt>{f.label}</dt><dd>{row[f.key]||"Not recorded"}</dd></div>)}</dl>)}</div>)}{selected.note&&<p>{selected.note}</p>}</details>
        <div className="business-workflow-actions"><button type="button" disabled={busy} onClick={()=>void showHistory(selected)}>Review history</button>{data.canExport&&<button type="button" disabled={busy} onClick={()=>exportRecord(selected)}>Export record</button>}{data.canWrite&&selected.state==="draft"&&<button type="button" disabled={busy} onClick={()=>start(selected)}>Edit draft</button>}{data.canReopen&&selected.state!=="draft"&&<button type="button" disabled={busy} onClick={()=>setReopening(true)}>Reopen for correction</button>}</div>
        {data.canWrite&&selected.state!=="completed"&&<div className="business-workflow-confirm"><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the source evidence and this action.</label><button className="business-workflow-primary" type="button" disabled={ownerReviewRequired||!reviewed||busy||selected.state==="reviewed"&&!selected.report.canComplete} onClick={()=>void mutate(selected.state==="draft"?"review":"complete",selected)}>{busy?"Saving…":selected.state==="draft"?"Mark reviewed":"Complete workflow"}</button>{ownerReviewRequired&&<p>The workspace owner must approve this workflow.</p>}{selected.state==="reviewed"&&!selected.report.canComplete&&<p>Required evidence or an outstanding action still needs resolution. Reopen to correct the record.</p>}</div>}
        {reopening&&<div className="business-workflow-confirm"><label>Reason for correction<textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={busy||reason.trim().length<5} onClick={()=>void mutate("reopen",selected)}>Confirm reopening</button><button type="button" disabled={busy} onClick={()=>setReopening(false)}>Cancel</button></div>}
        {history&&<section aria-label="Workflow history"><h4>Retained revisions</h4>{history.map(h=><details key={h.version}><summary>Revision {h.version} · {h.action} · {new Date(h.recordedAt).toISOString().slice(0,16).replace("T"," ")} UTC</summary>{h.reason&&<p>{h.reason}</p>}<p>{h.snapshot.record.name} · {h.snapshot.record.source} · {h.snapshot.state}</p><pre>{JSON.stringify(h.snapshot.record,null,2)}</pre></details>)}</section>}
      </article>}
      {draft&&<form className="business-workflow-editor" onSubmit={previewDraft}><fieldset disabled={busy}><h3 ref={formHeading} tabIndex={-1}>{editing?"Edit":"New"} {recordNouns[draft.kind]}</h3><p>Blank amounts remain unknown. Enter zero only when your source confirms it.</p>
        <div className="business-workflow-fields">{([['name','Record name'],['source','Source reference'],['asOfDate','Source date']] as const).map(([key,label])=><label key={key}>{label} *<input required maxLength={key==="name"?120:300} type={key==="asOfDate"?"date":"text"} value={draft[key]} onChange={e=>change({...draft,[key]:e.target.value})}/></label>)}
        {BUSINESS_WORKFLOW_DEFINITIONS[draft.kind].fields.filter(f=>f.key!=="invoiceRefs").map(f=><Field key={f.key} field={f} currency={draft.currency} value={draft.values[f.key]??""} onChange={v=>change({...draft,values:{...draft.values,[f.key]:v}})}/>)}
        {draft.kind==="job"&&<fieldset><legend>Linked BookLoQ invoices</legend>{data.invoices.length?data.invoices.map(i=><label className="business-workflow-check" key={i.id}><input type="checkbox" checked={draft.values.invoiceRefs.split(",").includes(i.id)} onChange={e=>{const ids=draft.values.invoiceRefs.split(",").filter(Boolean).filter(x=>x!==i.id);if(e.target.checked)ids.push(i.id);change({...draft,values:{...draft.values,invoiceRefs:ids.join(",")}});}}/>{i.number} · {i.status}</label>):<p className="business-workflow-note">Create invoices in BookLoQ. Linking requires BookLoQ and workspace-wide invoice access.</p>}</fieldset>}
        </div>
        {BUSINESS_WORKFLOW_DEFINITIONS[draft.kind].groups.map(g=><section className="business-workflow-entry-group" key={g.key}><h4>{g.label}</h4>{draft.groups[g.key].map((row,index)=><fieldset className="business-workflow-entry" key={index}><legend>{g.label} {index+1}</legend>{g.fields.map(f=><Field key={f.key} field={f} currency={draft.currency} value={row[f.key]??""} onChange={v=>change({...draft,groups:{...draft.groups,[g.key]:draft.groups[g.key].map((r,i)=>i===index?{...r,[f.key]:v}:r)}})}/>)}<button type="button" onClick={()=>change({...draft,groups:{...draft.groups,[g.key]:draft.groups[g.key].filter((_,i)=>i!==index)}})}>Remove entry</button></fieldset>)}<button type="button" disabled={draft.groups[g.key].length>=100} onClick={()=>change({...draft,groups:{...draft.groups,[g.key]:[...draft.groups[g.key],Object.fromEntries(g.fields.map(f=>[f.key,f.type==="select"?f.options?.[0]??"":""]))]}})}>Add entry</button></section>)}
        {["job","order_margin"].includes(draft.kind)&&<label className="business-workflow-check"><input type="checkbox" checked={draft.costCoverage} onChange={e=>change({...draft,costCoverage:e.target.checked})}/>All relevant direct costs for this review are included.</label>}
        <label>Review notes<textarea maxLength={2000} value={draft.note} onChange={e=>change({...draft,note:e.target.value})}/></label>
        <div className="business-workflow-actions"><button type="submit">Preview calculations</button><button type="button" onClick={()=>{setDraft(null);setEditing(null);setPreview(null);}}>Discard unsaved changes</button></div>
        {preview&&<div className="business-workflow-preview"><Report report={preview}/><button type="button" className="business-workflow-primary" onClick={()=>void mutate("save")}>{busy?"Saving…":"Save draft"}</button></div>}
      </fieldset></form>}
      {data.truncated&&<p className="business-workflow-note">The list is limited to the most recent records at this location. Listed totals are not a complete business balance.</p>}
    </>}
  </section>;
}
