"use client";
import { useEffect, useRef, useState } from 'react';
import { executiveDefinitions } from '../domain/executive-metrics';
import { normalizeDashboardPreferences, type DashboardPreferences } from '../domain/dashboard-preferences';
import { recommendedOverview } from '../domain/dashboard-personalization';
import { industryKpiRecommendation } from '../domain/industry-kpis';
import {useMotionPreference,setMotionPreference} from './use-motion-preference';

const groups: Record<string,string> = {net_revenue:'Sales',transactions:'Sales',average_order_value:'Sales',units_sold:'Sales',gross_profit:'Profitability',gross_margin:'Profitability',operating_profit:'Profitability',net_margin:'Profitability',cash_balance:'Cash',cash_flow:'Cash',inventory_value:'Stock'};
const inputs: Record<string,string> = {Sales:'Completed sales, dated returns and transaction counts.',Profitability:'Matched revenue, product costs and posted expense accounts. Missing costs stay visible.',Cash:'Reviewed, posted cash-account entries. Sales are not cash receipts.',Stock:'Dated inventory quantities and recorded unit costs.'};
export default function DashboardCustomizer({draft,onChange,onClose,onDiscard,onSave,saving,dirty,draftStatus,currency,industry,period,locationId,error}:{draft:DashboardPreferences;onChange:(next:DashboardPreferences)=>void;onClose:()=>void;onDiscard?:()=>void;onSave:()=>void;saving:boolean;dirty?:boolean;draftStatus?:string;error?:string;currency:string;industry?:string|null;period?:{from:string;to:string};locationId?:string|null}) {
  const dialog=useRef<HTMLDialogElement>(null),[search,setSearch]=useState(''),[viewName,setViewName]=useState(''),[undo,setUndo]=useState<DashboardPreferences|null>(null),[notice,setNotice]=useState('');
  const guide=industryKpiRecommendation(industry);
  const motion=useMotionPreference();
  useEffect(()=>{const element=dialog.current;const trigger=document.activeElement as HTMLElement|null;element?.showModal();return()=>{element?.close();trigger?.focus();};},[]);
  const update=(patch:Partial<DashboardPreferences>)=>onChange({...draft,...patch});
  const move=(index:number,offset:number)=>{const widgets=[...draft.widgets];[widgets[index],widgets[index+offset]]=[widgets[index+offset],widgets[index]];update({widgets});};
  const saveView=()=>{const name=viewName.trim();if(!name)return setNotice('Enter a name for this view.');const {views,collections:_collections,...layout}=draft;void _collections;const same=views.some(v=>v.name.toLowerCase()===name.toLowerCase());if(!same&&views.length>=5)return setNotice('Keep up to 5 named views. Remove one before adding another.');update({views:[...views.filter(v=>v.name.toLowerCase()!==name.toLowerCase()),{name,layout}]});setViewName('');setNotice('View added to your draft. Save Layout to keep it.');};
  return <dialog ref={dialog} className="dashboard-drawer" aria-labelledby="customizer-title" onCancel={e=>{e.preventDefault();if(!saving)onClose();}}>
    <header><div><span className="dashboard-eyebrow">YOUR OVERVIEW</span><h2 id="customizer-title">Make It Yours</h2><p>Choose the numbers that help you act.</p></div><button type="button" onClick={onClose} disabled={saving} aria-label={onDiscard ? "Close and keep dashboard draft" : "Cancel dashboard changes"}>×</button></header>
    <fieldset className="dashboard-drawer-body" disabled={saving} style={{border:0,margin:0,minWidth:0}}>
      {draftStatus&&<p role="status">{dirty?"Unsaved changes. ":""}{draftStatus}</p>}
      <section><h3>Saved Views</h3><div className="dashboard-view-list">{draft.views.map(view=><div key={view.name}><button type="button" onClick={()=>{onChange(normalizeDashboardPreferences({...view.layout,views:draft.views,collections:draft.collections}));setNotice(`${view.name} loaded into your draft.`);}}>{view.name}</button><button type="button" aria-label={`Remove view ${view.name}`} onClick={()=>{setUndo(draft);update({views:draft.views.filter(v=>v!==view)});}}>×</button></div>)}</div><div className="dashboard-name-view"><input aria-label="New view name" maxLength={40} placeholder="Name this view" value={viewName} onChange={e=>setViewName(e.target.value)}/><button type="button" onClick={saveView}>Add View</button></div></section>
      <section><h3>Interface Motion</h3><label className="dashboard-check"><input type="checkbox" checked={motion} onChange={event=>setMotionPreference(event.target.checked)}/>Subtle interface motion</label><p>Applied immediately in this browser. Your device’s reduced-motion setting always takes priority. Figures and controls stay available with motion off.</p></section>
      <section><h3>Your Starting Point</h3><p>{guide.industry}. Recommendations are starting points, not industry targets.</p><button type="button" onClick={()=>{setUndo(draft);onChange({...recommendedOverview(industry,draft.priorities),views:draft.views,collections:draft.collections,targets:draft.targets,goalRules:draft.goalRules});}}>Restore Recommended Layout</button></section>
      <section className="dashboard-options"><label>Default Period<select value={draft.defaultPeriod} onChange={e=>update({defaultPeriod:e.target.value as DashboardPreferences['defaultPeriod']})}>{[['today','Today'],['7d','7 Days'],['30d','30 Days'],['90d','90 Days'],['mtd','Month to Date'],['qtd','Quarter to Date'],['ytd','Year to Date'],['1y','1 Year'],['custom','Custom']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Compare With<select value={draft.comparison} onChange={e=>update({comparison:e.target.value as DashboardPreferences['comparison']})}><option value="previous">Previous Period</option><option value="yoy">Previous Year</option><option value="budget">Budget</option><option value="target">My Target</option></select></label>{draft.defaultPeriod==='custom'&&<><label>From<input type="date" value={draft.customDates.from} onChange={e=>update({customDates:{...draft.customDates,from:e.target.value}})}/></label><label>To<input type="date" min={draft.customDates.from} value={draft.customDates.to} onChange={e=>update({customDates:{...draft.customDates,to:e.target.value}})}/></label></>}</section>
      <section><h3>Metric Library</h3><p>Start with 4–6 cards. Use the arrows to reorder them.</p><input type="search" aria-label="Search metrics" placeholder="Search metrics or a business question" value={search} onChange={e=>setSearch(e.target.value)}/><div className="dashboard-library">{draft.widgets.map((widget,index)=>{const metric=executiveDefinitions.find(m=>m.key===widget.id)!;const group=groups[widget.id];const why=guide.recommended.find(m=>m.key===widget.id)?.reason??metric.formula;if(!`${metric.label} ${group} ${why}`.toLowerCase().includes(search.toLowerCase()))return null;return <article key={widget.id}><label><input type="checkbox" checked={widget.visible} onChange={e=>{setUndo(draft);update({widgets:draft.widgets.map(w=>w.id===widget.id?{...w,visible:e.target.checked}:w)});}}/><span><b>{metric.label}</b><small>{group}</small></span></label><div className="dashboard-widget-controls"><select aria-label={`${metric.label} card width`} value={widget.size} onChange={e=>update({widgets:draft.widgets.map(w=>w.id===widget.id?{...w,size:e.target.value==='wide'?'wide':'standard'}:w)})}><option value="standard">Standard</option><option value="wide">Wide</option></select><button type="button" aria-label={`Move ${metric.label} up`} disabled={!index} onClick={()=>move(index,-1)}>↑</button><button type="button" aria-label={`Move ${metric.label} down`} disabled={index===draft.widgets.length-1} onClick={()=>move(index,1)}>↓</button></div><details><summary>About This Metric</summary><p>{why}</p><p><b>Calculation:</b> {metric.formula}</p><p><b>Inputs:</b> {inputs[group]}</p><p><b>Period:</b> {['cash_balance','inventory_value'].includes(widget.id)?'Balance at the selected end date.':'Activity within the selected reporting dates.'} Updated after an eligible import or posting, not on a fixed live timer.</p><p>Open the card to inspect its permitted source, freshness and missing inputs. Source and account coverage determine availability.</p></details></article>;})}</div><details><summary>Measures That Need More Inputs</summary>{guide.nextMeasures.map(item=><p key={item.name}><b>{item.name}:</b> {item.definition} Needed: {item.requiredEvidence}</p>)}<p>These are not selectable overview metrics until the required evidence is supported.</p></details></section>
      <section><h3>Charts and Sections</h3><label>Trend Style<select value={draft.chart} onChange={e=>update({chart:e.target.value==='bar'?'bar':'line'})}><option value="line">Line</option><option value="bar">Bars</option></select></label>{([['needsAttention','What Needs Attention'],['collections','Invoices & Bills'],['financialDetail','Financial Detail']] as const).map(([key,label])=><label className="dashboard-check" key={key}><input type="checkbox" checked={draft.sections[key]} onChange={e=>update({sections:{...draft.sections,[key]:e.target.checked}})}/>{label}</label>)}<p>Financial panels still require your plan and role. Use the workspace location selector for locations you can access. Channel filtering is available in Sales detail, not this overview.</p></section>
      <section><h3>Your Goals</h3><p>Targets follow their saved dates and location. Amounts use {currency}; margin targets use percent.</p>{draft.goalRings.map((id,index)=>{const rule=draft.goalRules[id]??{direction:'higher' as const,from:period?.from??'',to:period?.to??'',locationId:locationId??null};const setRule=(patch:Partial<typeof rule>)=>update({goalRules:{...draft.goalRules,[id]:{...rule,...patch}}});return <fieldset className="dashboard-goal" key={index}><legend>Goal {index+1}</legend><label>Metric<select value={id} onChange={e=>{const goalRings=[...draft.goalRings] as DashboardPreferences['goalRings'];const key=e.target.value as typeof id;const other=goalRings.indexOf(key);if(other>=0)goalRings[other]=id;goalRings[index]=key;update({goalRings});}}>{executiveDefinitions.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label><div className="dashboard-options"><label>Target<input type="number" min="0.01" max="1000000000" step="any" value={draft.targets[id]??''} onChange={e=>{const targets={...draft.targets};if(!e.target.value)delete targets[id];else targets[id]=Number(e.target.value);update({targets,goalRules:{...draft.goalRules,[id]:rule}});}}/></label><label>Direction<select value={rule.direction} onChange={e=>setRule({direction:e.target.value==='lower'?'lower':'higher'})}><option value="higher">Reach or Exceed</option><option value="lower">At or Below</option></select></label><label>Start Date<input type="date" value={rule.from} onChange={e=>setRule({from:e.target.value})}/></label><label>Target Date<input type="date" min={rule.from} value={rule.to} onChange={e=>setRule({to:e.target.value})}/></label>{rule.direction==='lower'&&<label>Starting Value (Optional)<input type="number" step="any" value={rule.start??''} onChange={e=>setRule({start:e.target.value?Number(e.target.value):undefined})}/></label>}</div><button type="button" onClick={()=>setRule({locationId:locationId??null})}>Use Current Location Scope</button><small>{rule.locationId?'Saved to one permitted location':'All permitted locations'}. {rule.direction==='lower'?'Progress requires a starting value above the target.':''}</small></fieldset>;})}</section>
      <details><summary>Metric References</summary><p>Our formulas describe the records Vanteloq supports. Targets are yours.</p><a href="https://www.bdc.ca/en/articles-tools/entrepreneur-toolkit/templates-business-guides/glossary/gross-margin" target="_blank" rel="noreferrer">BDC: Gross Margin</a><a href="https://www.bdc.ca/en/articles-tools/entrepreneur-toolkit/financial-tools/inventory-turnover-benchmarking-tool" target="_blank" rel="noreferrer">BDC: Inventory Turnover</a><a href="https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-of-cash-flows/" target="_blank" rel="noreferrer">IFRS Foundation: Cash Flow Categories</a></details>
      {notice&&<p role="status">{notice}</p>}{undo&&<button type="button" onClick={()=>{onChange(undo);setUndo(null);}}>Undo Last Removal or Reset</button>}
    </fieldset><footer>{error&&<p role="alert">{error}</p>}{onDiscard&&<button type="button" disabled={saving||!dirty} onClick={()=>{onDiscard();setUndo(null);setNotice('Unsaved changes discarded.');}}>Discard Changes</button>}<button type="button" disabled={saving} onClick={onClose}>{onDiscard?'Keep Draft & Close':'Cancel'}</button><button type="button" className="dashboard-save" disabled={saving} onClick={onSave}>{saving?'Saving…':'Save Layout'}</button></footer>
  </dialog>;
}
