"use client";
import { useEffect, useId, useState } from "react";
import type { ExecutiveReport } from "../server/executive-report";
import type { ExecutiveKey } from "../domain/executive-metrics";
import { apiFetch } from "./supabase-browser";
import { MetricSparkline } from "./dashboard-charts";
import { useChartWidth } from "./use-chart-width";
import "./executive-overview.css";

const periods=[["today","Today"],["7d","7D"],["30d","30D"],["mtd","MTD"],["qtd","QTD"],["ytd","YTD"],["custom","Custom"]];
const cash=(v:number|null,currency:string)=>v===null?"Not available":new Intl.NumberFormat("en-CA",{style:"currency",currency,maximumFractionDigits:2}).format(v===0?0:v/100);
const number=(v:number|null)=>v===null?"Not available":v.toLocaleString("en-CA",{maximumFractionDigits:2});
const display=(v:number|null,unit:string,currency:string)=>v===null?"Not available":unit==="percent"?`${number(v*100)}%`:cash(v,currency);
const date=(value:string)=>new Intl.DateTimeFormat("en-CA",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(value+"T00:00:00Z"));

export default function ExecutiveOverview({currency,activeLocationId,basis="commerce",navigate,refreshKey,initialReport}:{currency:string;activeLocationId?:string|null;basis?:"commerce"|"ledger";navigate:(view:"Sales"|"BookLoQ"|"Integrations"|"Intelligence",period?:{from:string;to:string})=>void;refreshKey?:string|null;initialReport?:ExecutiveReport}) {
  const [preset,setPreset]=useState("30d"),[compare,setCompare]=useState("previous"),[range,setRange]=useState({from:"",to:""}),[appliedRange,setAppliedRange]=useState({from:"",to:""});
  const [storedReport,setReport]=useState<ExecutiveReport|null>(initialReport??null),[error,setError]=useState(""),[reload,setReload]=useState(0),[selected,setSelected]=useState<ExecutiveKey>("net_revenue"),[targets,setTargets]=useState<Partial<Record<ExecutiveKey,string>>>({});
  const [pending,setPending]=useState(!initialReport);
  const scope=JSON.stringify([preset,compare,appliedRange,activeLocationId,basis,reload,refreshKey]);
  const [responseScope,setResponseScope]=useState(scope);
  const report=initialReport??(responseScope===scope?storedReport:null);
  const visiblePending=!initialReport&&(pending||responseScope!==scope);
  const visibleError=responseScope===scope?error:"";
  useEffect(()=>{
    if(initialReport)return;
    const controller=new AbortController();
    const timeout=setTimeout(()=>controller.abort(),30000);
    let active=true;
    const params=new URLSearchParams({executive:"1",period:preset,compare,basis});
    if(activeLocationId)params.set("location",activeLocationId);
    if(preset==="custom"){params.set("from",appliedRange.from);params.set("to",appliedRange.to);}
    queueMicrotask(()=>{if(active){setPending(true);setResponseScope(scope);setReport(null);setError("");}});
    void apiFetch(`/api/v1/command-centre?${params}`,{signal:controller.signal,headers:{Accept:"application/json"}}).then(async response=>{
      const payload=await response.json();if(!response.ok)throw Error(payload.error?.message??"This overview could not load. Try again.");
      if(!payload.executiveReport)throw Error("The overview is unavailable. Refresh and try again.");
      if(active)setReport(payload.executiveReport);
    }).catch(cause=>{if(active)setError(cause instanceof Error&&cause.name!=="AbortError"?cause.message:"The request timed out. Try again.");}).finally(()=>{clearTimeout(timeout);if(active)setPending(false);});
    return()=>{active=false;controller.abort();clearTimeout(timeout);};
  },[preset,compare,appliedRange,activeLocationId,basis,reload,refreshKey,initialReport,scope]);
  const metric=report?.metrics.find(m=>m.key===selected);
  return <section className="executive-overview" aria-label="Executive overview">
    <header className="executive-heading"><div><p>EXECUTIVE OVERVIEW</p><h3>Performance at a glance.</h3><span>{basis==="commerce"?"Sales, profit and cash, with the evidence one click away.":"Posted results for your selected period."}</span></div><button type="button" onClick={()=>setReload(reload+1)} disabled={visiblePending}>Refresh</button></header>
    <div className="executive-filters"><div role="group" aria-label="Reporting period">{periods.map(([key,label])=><button key={key} type="button" aria-pressed={preset===key} onClick={()=>{if(key==="custom"){if(report)setRange({from:report.period.from,to:report.period.to});}else setPreset(key);}}>{label}</button>)}</div><label>Compare <select value={compare} onChange={e=>setCompare(e.target.value)}><option value="previous">Previous period</option><option value="yoy">Previous year</option><option value="budget">Budget</option><option value="target">Target</option></select></label></div>
    {(range.from||preset==="custom")&&<form className="executive-dates" onSubmit={e=>{e.preventDefault();setAppliedRange(range);setPreset("custom");}}><label>From <input type="date" required value={range.from} onChange={e=>setRange({...range,from:e.target.value})}/></label><label>To <input type="date" required min={range.from} value={range.to} onChange={e=>setRange({...range,to:e.target.value})}/></label><button type="submit">Apply Dates</button><button type="button" onClick={()=>{setRange({from:"",to:""});setPreset("30d");}}>Cancel</button></form>}
    {visiblePending?<div className="executive-loading" role="status" aria-label="Loading executive overview">{Array.from({length:8},(_,i)=><div key={i}><i/><b/><i/></div>)}</div>:visibleError?<div className="executive-error" role="alert"><p>{visibleError}</p><button onClick={()=>setReload(reload+1)}>Try Again</button></div>:report&&<>
      <div className="executive-period-label"><span>{date(report.period.from)} to {date(report.period.to)}, {report.period.to.slice(0,4)} · {currency}</span><span>{basis==="commerce"&&!report.sourceCoverage?"Some source dates are missing. Comparisons are withheld.":"Recorded results. Open a metric to inspect its basis."}</span></div>
      <div className="executive-kpis">{report.metrics.map(m=>{
        const target=compare==="target"?(targets[m.key]!==undefined&&targets[m.key]!==""?(m.unit==="percent"?Number(targets[m.key])*.01:Math.round(Number(targets[m.key])*100)):null):m.budget;
        const validTarget=target!==null&&Number.isFinite(target)?target:null;
        const benchmark=compare==="budget"||compare==="target"?validTarget:m.previous;
        const variance=m.value!==null&&benchmark!==null?m.value-benchmark:null;
        const percent=variance!==null&&benchmark!==null&&benchmark!==0?variance/Math.abs(benchmark)*100:null;
        return <button type="button" key={m.key} className={`executive-kpi ${selected===m.key?"selected":""}`} aria-pressed={selected===m.key} onClick={()=>setSelected(m.key)}><span className="executive-kpi-label">{m.label}<i aria-hidden="true">↗</i></span><strong className={m.value===null?"unavailable":""}>{display(m.value,m.unit,currency)}</strong><span className="executive-change">{percent===null?"Comparison unavailable":`${percent>0?"+":""}${number(percent)}%`}<small>{compare==="previous"?"vs previous period":compare==="yoy"?"vs previous year":compare==="target"?"vs your view target":"vs ledger budget"}</small></span><span className="executive-prior">Previous: {display(m.previous,m.unit,currency)}</span><span className="executive-target">{compare==="target"?"View target":"Budget"}: {validTarget===null?"Not set":display(validTarget,m.unit,currency)}{m.value!==null&&validTarget!==null?` · ${m.unit==="percent"?`${number((m.value-validTarget)*100)} pp`:display(m.value-validTarget,m.unit,currency)} variance`:""}</span><div className="executive-mini-chart">{m.trend.some(p=>p.value!==null)?<MetricSparkline values={m.trend.map(p=>p.value??NaN)} tone="indigo"/>:<small>{m.reason??"Trend requires dated source records"}</small>}</div><span className="executive-source">{m.source.replaceAll("_"," ")}<small>{m.sourceTimestamp?`Updated ${new Intl.DateTimeFormat("en-CA",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(m.sourceTimestamp))}`:m.value===null?"Awaiting source":"Update time unavailable"}</small></span></button>;
      })}</div>
      {metric&&<article className="executive-detail"><header><div><p>SELECTED METRIC</p><h3>{metric.label}</h3><span>{metric.formula}</span></div><button onClick={()=>navigate(metric.drill,{from:report.period.from,to:report.period.to})}>Open Source Records ↗</button></header>{compare==="target"&&<label className="executive-target-input">Comparison target ({metric.unit==="percent"?"%":currency})<input type="number" step="0.01" inputMode="decimal" value={targets[metric.key]??""} onChange={e=>setTargets({...targets,[metric.key]:e.target.value})}/><small>For this view only. This does not change your saved budget.</small></label>}<ExecutiveTrend key={metric.key+report.period.from+report.period.to} metric={metric} currency={currency}/><details><summary>Source, Coverage and Calculation</summary><p>{metric.reason??`Confidence: ${metric.confidence}.`}</p><p>Current: {report.period.from} to {report.period.to}. Comparison: {report.period.comparisonFrom} to {report.period.comparisonTo}.</p>{metric.limitations.map((line,i)=><p key={i}>{line}</p>)}<p>Budget variance requires a complete ledger budget covering these exact dates. POS and ledger totals are not interchangeable.</p></details></article>}
      <div className="executive-insights"><header><h3>What Needs Attention</h3><button onClick={()=>navigate("Intelligence")}>Explore Drivers ↗</button></header>{report.insights.length?report.insights.slice(0,3).map(item=><details key={item.id}><summary>{item.title}<small>{item.confidence} confidence</small></summary><p><b>What changed:</b> {item.whatHappened}</p><p><b>Possible driver:</b> {item.probableCause}</p><p><b>Financial impact:</b> {item.financialImpact}</p><p><b>Next step:</b> {item.recommendedAction}</p><p>These are patterns in recorded data, not proof of a cause.</p></details>):<p>More comparable records are needed before explaining a change. Open the sources to review coverage.</p>}</div>
      {report.finance?<FinanceDetails data={report.finance} currency={currency}/>:<details className="executive-financial-details"><summary>Financial Detail</summary><p>{report.financeReason??"Activate BookLoQ and post your reviewed records to see period-specific statements, aging and ratios."}</p><button onClick={()=>navigate("BookLoQ")}>Open BookLoQ</button></details>}
    </>}
  </section>;
}

function ExecutiveTrend({metric,currency}:{metric:ExecutiveReport["metrics"][number];currency:string}) {
  const {ref,width}=useChartWidth(780,320),id=useId().replaceAll(":",""),[hover,setHover]=useState<number|null>(null);
  const values=metric.trend.filter(p=>p.value!==null);
  if(!values.length)return <div className="executive-chart-empty"><span>No dated trend available</span><p>{metric.reason??"This source provides a balance, not a daily history. Its supporting records remain available."}</p></div>;
  const min=Math.min(0,...values.map(p=>p.value!)),max=Math.max(1,...values.map(p=>p.value!));
  const first=Date.parse(metric.trend[0].date),last=Date.parse(metric.trend.at(-1)!.date),plot=width-82;
  const x=(i:number)=>58+(last===first?plot/2:(Date.parse(metric.trend[i].date)-first)/(last-first)*plot),y=(v:number)=>22+(max-v)/(max-min)*145;
  const path=metric.trend.map((p,i)=>{if(p.value===null)return "";const previous=metric.trend[i-1];const contiguous=previous?.value!=null&&Date.parse(p.date)-Date.parse(previous.date)<=86400000;return `${contiguous?"L":"M"}${x(i)},${y(p.value)}`;}).join(" ");
  const point=hover===null?null:metric.trend[hover];
  return <div className="executive-chart" ref={ref}><div className="executive-chart-readout" aria-live="polite">{point?<><b>{date(point.date)}</b><span>{display(point.value,metric.unit,currency)}</span></>:<span>Recorded daily values. Gaps remain visible.</span>}</div><svg viewBox={`0 0 ${width} 204`} width={width} height="204" role="group" aria-label={`${metric.label} by recorded date`}><defs><linearGradient id={id} x1="0" x2="1"><stop stopColor="#1777ec"/><stop offset="1" stopColor="#514cc6"/></linearGradient></defs>{[0,.5,1].map(t=>{const val=min+(max-min)*t;return <g key={t}><line x1="58" x2={width-24} y1={y(val)} y2={y(val)} stroke="#dfe6ef"/><text x="50" y={y(val)+4} textAnchor="end" fill="#50627a" fontSize="11">{metric.unit==="percent"?`${Math.round(val*100)}%`:new Intl.NumberFormat("en-CA",{notation:"compact",maximumFractionDigits:1}).format(val/100)}</text></g>;})}<path d={path} fill="none" stroke={`url(#${id})`} strokeWidth="2.5"/>{metric.trend.map((p,i)=>p.value===null?null:<circle key={p.date} cx={x(i)} cy={y(p.value)} r={hover===i?5:3} fill="#2975e2" stroke="#fff" strokeWidth="1.5" tabIndex={hover===i||(hover===null&&p.date===values[0].date)?0:-1} role="button" aria-label={`${p.date}: ${display(p.value,metric.unit,currency)}`} onFocus={()=>setHover(i)} onMouseEnter={()=>setHover(i)} onKeyDown={e=>{if(e.key==="ArrowRight"||e.key==="ArrowLeft"){e.preventDefault();const points=Array.from(e.currentTarget.parentElement?.querySelectorAll('circle')??[]);const index=points.indexOf(e.currentTarget);const next=Math.max(0,Math.min(points.length-1,index+(e.key==="ArrowRight"?1:-1)));(points[next] as SVGElement|undefined)?.focus();}}}/>)}{[0,metric.trend.length-1].map((i,j)=><text key={j} x={x(i)} y="195" textAnchor={j?"end":"start"} fontSize="11" fill="#50627a">{date(metric.trend[i].date)}</text>)}</svg><details><summary>View Data Table</summary><table><thead><tr><th>Date</th><th>{metric.label}</th></tr></thead><tbody>{metric.trend.map(p=><tr key={p.date}><td>{p.date}</td><td>{display(p.value,metric.unit,currency)}</td></tr>)}</tbody></table></details></div>;
}

function FinanceDetails({data,currency}:{data:NonNullable<ExecutiveReport["finance"]>;currency:string}) {
  const f=data.current,b=data.closing;
  const rows=(items:[string,number|null][])=> <dl>{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{cash(value,currency)}</dd></div>)}</dl>;
  return <details className="executive-financial-details"><summary>Financial Detail <span>P&amp;L, cash flow, aging and working capital</span></summary><p>{data.boundary}</p><div className="executive-finance-grid"><article><h4>Profit and Loss</h4>{f?rows([["Operating revenue",f.operatingRevenueCents],["Cost of goods sold",data.accountCoverage.costs?-f.cogsCents:null],["Gross profit",data.accountCoverage.costs?f.grossProfitCents:null],["Operating expenses",-f.operatingExpensesCents],["Operating profit",data.accountCoverage.costs?f.operatingProfitCents:null],["Other income",f.otherIncomeCents],["Finance costs and income tax",-f.financeAndTaxCents],["Recorded net earnings",data.accountCoverage.costs?f.netProfitCents:null]]):<p>No posted entries in this period.</p>}</article><article><h4>Balance Sheet</h4>{rows([["Assets",b.assetsCents],["Liabilities",b.liabilitiesCents],["Equity including recorded earnings",b.equityCents],["Balance check",b.balanceDifferenceCents]])}<p>A balanced ledger is a bookkeeping check, not an audit.</p></article><article><h4>Cash Flow by Activity</h4>{data.cashClassification&&data.accountCoverage.cash?rows([["Operating",data.cashClassification.operating],["Investing",data.cashClassification.investing],["Financing",data.cashClassification.financing],["Needs classification review",data.cashClassification.unclassified],["Net recorded movement",data.cashClassification.total]]):<p>Use the detailed ledger to review this volume of entries.</p>}<p>Only unambiguous account classifications are assigned. Mixed journals, interest and income tax require review.</p></article><article><h4>Liquidity and Tax</h4>{rows([["Working capital",b.workingCapitalCents],["Monthly net cash burn",data.monthlyBurnCents],["GST collected",b.gstCollectedCents],["GST recoverable",b.gstRecoverableCents],["Net recorded GST",b.gstNetCents]])}<p>Current ratio: {number(b.currentRatio)} · Quick ratio: {number(b.quickRatio)}</p><p>Cash runway: {number(data.runwayMonths)}{data.runwayMonths===null?"":" months"}. Ratios require classified current balances. Tax figures are working papers, not a filed return.</p></article>{[["Receivables",data.receivables],["Payables",data.payables]].map(([label,buckets])=><article key={String(label)}><h4>{String(label)} Aging</h4>{Array.isArray(buckets)?rows(buckets.map(row=>[row.label,row.cents])):<p>{data.agingBoundary}</p>}</article>)}<article><h4>Expenses by Category</h4>{f?rows(f.expenseCategories.filter(r=>r.cents!==0).map(r=>[r.name,r.cents])):<p>No posted expense entries.</p>}</article><article><h4>Expenses by Supplier</h4>{data.vendors.length?rows(data.vendors.map(r=>[r.name,r.cents])):<p>Named supplier records require the appropriate contact permission.</p>}</article></div></details>;
}
