import { executiveDefinitions } from "../domain/executive-metrics";
import type { DashboardPreferences } from "../domain/dashboard-preferences";

/** The source gate stays closed. Only layout and next actions are rendered. */
export default function ExecutiveStatusFrame({ message, syncing, checking = false, preferences, onSources, onConnections = onSources, onRetry }: {
  message: string; syncing: boolean; checking?: boolean; preferences: DashboardPreferences; onSources: () => void; onConnections?: () => void; onRetry: () => void;
}) {
  return <div className="executive-status-frame">
    <div className="executive-refresh-notice" role="status"><span><b>{syncing ? "Your records are refreshing" : "Review your reporting sources"}</b><small>{message}</small></span><button type="button" onClick={onRetry} disabled={checking}>{checking ? "Checking…" : "Check Again"}</button></div>
    <div className="executive-kpis" aria-label="Dashboard metrics awaiting verified results">{preferences.widgets.filter(widget=>widget.visible).map(widget=><button type="button" className={`executive-kpi size-${widget.size}`} key={widget.id} onClick={onSources}><span className="executive-kpi-label">{executiveDefinitions.find(metric=>metric.key===widget.id)?.label}<i aria-hidden="true">↗</i></span><strong>—</strong><span className="executive-change">{syncing ? "Refreshing records" : "Review source selection"}</span><div className="executive-mini-chart"><span className="executive-empty-spark" aria-hidden="true"><i/><i/><i/></span></div><span className="executive-source">Results appear after verification</span></button>)}</div>
    <div className="executive-visual-grid"><article className="executive-detail"><header><div><p>PERIOD TREND</p><h3>Net Revenue</h3></div><button type="button" onClick={onSources}>Review Sources</button></header><div className="executive-trend-empty"><div className="executive-empty-axis" aria-hidden="true"><span>—</span><span>—</span><span>—</span></div><div className="executive-empty-plot"><div className="executive-empty-grid" aria-hidden="true"/><div className="executive-empty-message"><b>{syncing ? "Your trend will return here." : "Choose the source for these results."}</b><p>Totals are withheld until the source check completes. Your saved layout and goals are unchanged.</p></div></div></div></article><article className="executive-insights"><header><h3>Keep Your Work Moving</h3></header><div className="executive-insight-empty"><p>You can review connections or continue in BookLoQ while these records are checked.</p><button type="button" onClick={onConnections}>Review Connections</button></div></article></div>
  </div>;
}
