"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { apiFetch } from "./supabase-browser";
import { applyFoodModifiers, validateFoodModifiers, type FoodModifier } from "../domain/foodservice-modifiers";
import { foodAmountText, foodAmountToMinor, foodserviceRecordReport, type FoodSavedRecord, type FoodRecordContent, type FoodUnit } from "../domain/foodservice";

async function result(response:Response) {const body=await response.json();if(!response.ok)throw Error(body.error?.message??"The record could not be saved.");return body;}
const units:FoodUnit[]=["g","kg","ml","l","each","oz_mass","lb"];

export function FoodRecordHistory({record}:{record:FoodSavedRecord}) {
  const [history,setHistory]=useState<{version:number;recordedAt:number;record:FoodRecordContent;report:ReturnType<typeof foodserviceRecordReport>}[]|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[truncated,setTruncated]=useState(false);
  const request=useRef<AbortController|null>(null);
  useEffect(()=>()=>request.current?.abort(),[]);
  async function load(){request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setError("");try{const body=await result(await apiFetch(`/api/v1/foodservice?history=${encodeURIComponent(record.id)}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])}));if(!controller.signal.aborted){setHistory(body.revisions);setTruncated(Boolean(body.truncated));}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"History could not be loaded.");}finally{if(!controller.signal.aborted)setBusy(false);}}
  return <details className="foodservice-history" onToggle={e=>{if(e.currentTarget.open&&!history&&!busy)void load();}}><summary>Reviewed history</summary><p className="foodservice-note">Saved versions retain their entered quantities and costs. This history does not prove which recipe was used for an earlier sale.</p>{busy&&<p role="status">Loading retained versions…</p>}{error&&<p role="alert">{error}<button type="button" onClick={()=>void load()}>Retry</button></p>}{truncated&&<p className="foodservice-note">Showing the 100 most recent saved versions. Older versions remain retained but are not displayed here.</p>}{history?.length===0&&<p>History starts with the next reviewed save. Earlier overwritten versions are not available.</p>}{history?.map(item=><details key={item.version}><summary>Version {item.version} · {item.record.asOfDate} · {item.record.source}</summary><p className="foodservice-note">Retained {new Intl.DateTimeFormat("en-CA",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(new Date(item.recordedAt))} UTC. Source as-of date: {item.record.asOfDate}.</p>{item.record.kind==="recipe"?<><p>{item.record.payload.portions??"Unknown"} portions · {item.record.payload.currency}</p><ul>{item.record.payload.ingredients?.map(i=><li key={i.id}>{i.id}: {i.recipeQuantity?.amount??"Unknown"} {i.recipeQuantity?.unit} · purchased pack {i.purchaseQuantity?.amount??"Unknown"} {i.purchaseQuantity?.unit} · yield factor {i.preparationYield??"Unknown"} · pack cost {i.purchaseCost?foodAmountText(i.purchaseCost.minor,i.purchaseCost.currency):"unknown"}</li>)}</ul></>:<p>Period {item.record.from} to {item.record.to}. Retained input values are available in the download.</p>}<button type="button" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(item,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`foodservice-${record.id}-v${item.version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download version {item.version}</button></details>)}</details>;
}

export function FoodRecipeModifiers({record,canEdit,onSaved}:{record:FoodSavedRecord;canEdit:boolean;onSaved:()=>void}) {
  const [mappings,setMappings]=useState<FoodModifier[]>(record.kind==="recipe"?record.payload.modifiers??[]:[]),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState(false);
  const [draft,setDraft]=useState({id:"",label:"",operation:"add" as FoodModifier["operation"],targetId:"",ingredientId:"",amount:"",unit:"g" as FoodUnit,purchaseAmount:"",purchaseUnit:"g" as FoodUnit,cost:"",yield:"1"});
  const mappingError=useRef<HTMLParagraphElement|null>(null);
  const request=useRef<AbortController|null>(null);useEffect(()=>()=>request.current?.abort(),[]);
  if(record.kind!=="recipe")return null;
  const recipe=record.payload;
  let preview:ReturnType<typeof applyFoodModifiers>|null=null,previewError="";
  try{preview=applyFoodModifiers({...recipe,modifiers:mappings},selected);}catch(e){previewError=e instanceof Error?e.message:"Review this combination.";}
  const change=(next:Partial<typeof draft>)=>{setDraft({...draft,...next});setReviewed(false);};
  function add(event:FormEvent){event.preventDefault();try{const minor=foodAmountToMinor(draft.cost,recipe.currency);const mapping:FoodModifier={id:draft.id,label:draft.label,operation:draft.operation,targetId:draft.operation==="add"?null:draft.targetId,ingredient:draft.operation==="remove"?null:{id:draft.ingredientId,recipeQuantity:{amount:draft.amount||null,unit:draft.unit},purchaseQuantity:{amount:draft.purchaseAmount||null,unit:draft.purchaseUnit},purchaseCost:minor===null?null:{minor,currency:recipe.currency},preparationYield:draft.yield||null}};setMappings(validateFoodModifiers([...mappings,mapping],recipe));setSelected([]);setError("");setReviewed(false);setDraft({...draft,id:"",label:"",ingredientId:"",amount:"",cost:""});}catch(e){setError(e instanceof Error?e.message:"Review this mapping.");requestAnimationFrame(()=>mappingError.current?.focus());}}
  async function save(){if(!reviewed||busy)return;const controller=new AbortController();request.current=controller;setBusy(true);setError("");try{await result(await apiFetch("/api/v1/foodservice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save",id:record.id,locationId:record.locationId,expectedVersion:record.version,reviewed:true,record:{...record,payload:{...recipe,modifiers:mappings}}}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)])}));if(!controller.signal.aborted)onSaved();}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"The save could not be confirmed. Reload before retrying.");}finally{if(!controller.signal.aborted)setBusy(false);}}
  return <details className="foodservice-modifiers"><summary>Sizes, substitutions and extras</summary><p className="foodservice-note">Create a separate base recipe for each size. Modifiers apply to that recipe&apos;s full yielded quantity. This is a reviewed costing preview, not an automatic POS mapping or stock deduction.</p><fieldset disabled={busy}><legend>Preview a combination</legend>{mappings.length===0&&<p>No modifier mappings are saved yet.</p>}{mappings.map(m=><div className="foodservice-modifier-choice" key={m.id}><label><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(e.target.checked?[...selected,m.id]:selected.filter(id=>id!==m.id))}/>{m.label} <small>{m.operation}{m.targetId?` ${m.targetId}`:""}</small></label>{canEdit&&<button type="button" aria-label={`Remove mapping ${m.label}`} onClick={()=>{setMappings(mappings.filter(row=>row.id!==m.id));setSelected(selected.filter(id=>id!==m.id));setReviewed(false);}}>Remove mapping</button>}</div>)}{previewError&&<p role="alert">{previewError}</p>}{preview?.status==="incomplete_base"&&<p role="status">Add the base recipe ingredients before previewing extras. Missing ingredients cannot be treated as zero cost.</p>}{preview?.status==="mapped"&&<div className="foodservice-preview"><h4>Combination preview</h4><p className="foodservice-note">Expected quantities for the full recipe. Saved only when you confirm below.</p><ul>{preview.ingredients.map(i=><li key={i.id}>{i.id}: {i.recipeQuantity?.amount??"Unknown"} {i.recipeQuantity?.unit}</li>)}</ul><strong>{preview.cost.status==="available"?`${recipe.currency} ${foodAmountText(preview.cost.value.perPortionMinor,recipe.currency)} per portion`:"Cost incomplete. Review missing quantities or costs."}</strong></div>}
    {canEdit&&<details><summary>Add a modifier mapping</summary><form className="foodservice-mapping-form" onSubmit={add}><div className="foodservice-fields"><label>Modifier identifier<input required value={draft.id} maxLength={120} onChange={e=>change({id:e.target.value})}/></label><label>Customer-facing name<input required value={draft.label} maxLength={120} onChange={e=>change({label:e.target.value})}/></label><label>Effect<select value={draft.operation} onChange={e=>change({operation:e.target.value as FoodModifier["operation"]})}><option value="add">Add ingredient</option><option value="replace">Replace ingredient</option><option value="remove">Remove ingredient</option></select></label>{draft.operation!=="add"&&<label>Base ingredient<select required value={draft.targetId} onChange={e=>change({targetId:e.target.value})}><option value="">Choose ingredient</option>{recipe.ingredients?.map(i=><option key={i.id}>{i.id}</option>)}</select></label>}{draft.operation!=="remove"&&<>{([['ingredientId','Ingredient name / identifier'],['amount','Recipe quantity'],['purchaseAmount','Purchased pack quantity'],['cost',`Pack cost (${recipe.currency})`],['yield','Preparation yield factor']] as const).map(([key,label])=><label key={key}>{label}<input required={key==="ingredientId"} value={draft[key]} maxLength={120} inputMode={key==="ingredientId"?"text":"decimal"} onChange={e=>change({[key]:e.target.value})}/></label>)}{([['unit','Recipe unit'],['purchaseUnit','Purchase unit']] as const).map(([key,label])=><label key={key}>{label}<select value={draft[key]} onChange={e=>change({[key]:e.target.value as FoodUnit})}>{units.map(u=><option key={u} value={u}>{u}</option>)}</select></label>)}</>}</div><button type="submit">Add mapping to preview</button></form></details>}
    {canEdit&&<><label className="foodservice-review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed these mappings, including their quantities, cost basis and recipe yield.</label><button className="foodservice-primary" type="button" disabled={!reviewed||busy} onClick={()=>void save()}>{busy?"Saving…":"Save mappings as a new version"}</button></>}</fieldset>{error&&<p ref={mappingError} tabIndex={-1} role="alert" className="foodservice-error">{error}</p>}</details>;
}
