"use client";
import {lazy,Suspense,useEffect,useMemo,useState} from "react";
import {apiFetch} from "./supabase-browser";
import {defaultForecastSettings,forecastMetrics,shiftForecastDate,type ForecastMetric,type ForecastReport,type ForecastSettings} from "../domain/forecasting";
import {sampleForecast} from "../domain/forecast-sample";
import ForecastChart,{forecastFormat,forecastLabel} from "./forecast-chart";
import "./forecasting-workspace.css";
const Planning=lazy(()=>import("./forecast-planning-panels"));
type Preferences={pinned:boolean;views:{name:string;metric:ForecastMetric;horizon:7|28;locationId:string|null}[]};
type Payload={report:ForecastReport;capabilities:{configure:boolean;promotion:boolean;inventory:boolean;capacity:boolean;cash:boolean;export:boolean};locations:{id:string;name:string}[];preferences:Preferences;runs:{id:string;issuedAt:string;horizon:number}[]};
export async function forecastRequest(path:string,body?:unknown,signal?:AbortSignal){const response=await apiFetch(path,{signal,headers:{"Content-Type":"application/json",Accept:"application/json"},...(body?{method:"POST",body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error?.message??"Forecasting could not load. Please try again.");return data;}
type Props={activeLocationId:string|null;currency:string;navigate:(view:"Integrations"|"Data Quality"|"BookLoQ"|"Advisor")=>void};
export default function ForecastingWorkspace(props:Props){return <ForecastingContent key={props.activeLocationId??"all"} {...props}/>;}
function ForecastingContent({activeLocationId,currency,navigate}:Props){
 const [locationId,setLocation]=useState(activeLocationId),[horizon,setHorizon]=useState<7|28>(7),[metric,setMetric]=useState<ForecastMetric>("transactions"),[payloadState,setPayload]=useState<(Payload&{requestKey:string})|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[sample,setSample]=useState(false),[tab,setTab]=useState("Outlook"),[refresh,setRefresh]=useState(0),[viewName,setViewName]=useState(""),[snapshot,setSnapshot]=useState<ForecastReport|null>(null);
 const requestKey=`${locationId}:${horizon}:${refresh}`,payload=payloadState?.requestKey===requestKey?payloadState:null;
 useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted){setBusy(true);setError("");setSnapshot(null);}});forecastRequest(`/api/v1/forecasting?horizon=${horizon}${locationId?`&location=${encodeURIComponent(locationId)}`:""}`,undefined,controller.signal).then(d=>{if(!controller.signal.aborted)setPayload({...d,requestKey});}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[horizon,locationId,refresh,requestKey]);
 const sampleReport=useMemo(()=>sample?sampleForecast(horizon):null,[sample,horizon]);
 const report=sampleReport??(payload?snapshot??payload.report:null),cap=payload?.capabilities,locations=report?.locations??[],one=locations[0];
 const perform=async(action:()=>Promise<void>)=>{setBusy(true);setError("");try{await action();}catch(e){setError(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}};
 const prefs=async(preferences:Preferences)=>{await forecastRequest("/api/v1/forecasting",{action:"preferences",preferences});setPayload(p=>p?{...p,preferences}:p);};
 const allowedTabs=["Outlook",...(cap?.promotion?["Promotion"]:[]),...(cap?.inventory?["Stock"]:[]),...(cap?.capacity?["Capacity"]:[]),...(cap?.cash?["Cash"]:[])];
 const activeTab=allowedTabs.includes(tab)?tab:"Outlook";
 const saveView=()=>perform(async()=>{if(!viewName.trim()||!payload)return;await prefs({...payload.preferences,views:[...payload.preferences.views.filter(v=>v.name!==viewName.trim()).slice(-4),{name:viewName.trim(),horizon,metric,locationId}]});setViewName("");setNotice("Personal view saved.");});
 const saveRun=()=>perform(async()=>{await forecastRequest("/api/v1/forecasting",{action:"issue",locationId,horizon});setNotice("Forecast issued. Its inputs and original result are preserved.");setRefresh(x=>x+1);});
 const exportRun=(id:string)=>perform(async()=>{const response=await apiFetch(`/api/v1/forecasting?run=${encodeURIComponent(id)}&format=csv${locationId?`&location=${encodeURIComponent(locationId)}`:""}`);if(!response.ok)throw new Error("Export unavailable. Refresh your access and try again.");const url=URL.createObjectURL(await response.blob()),a=document.createElement("a");a.href=url;a.download="vanteloq-forecast.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 return <div className="fc-workspace"><header className="fc-head"><div><p className="fc-eyebrow">FORECASTING</p><h2>Prepare for what comes next.</h2><p>Plan busy days, protect contribution and review the cash behind your decisions.</p></div><button onClick={()=>setSample(v=>!v)}>{sample?"Return to my business":"Preview fictional sample"}</button></header>
 {sample&&<p className="fc-notice">Fictional sample preview. These figures are separate from your business and cannot be saved to your account.</p>}{snapshot&& !sample&&<p className="fc-notice">Original issued forecast · {new Date(snapshot.issuedAt).toLocaleString()} <button onClick={()=>setSnapshot(null)}>Return to current inputs</button></p>}
 <div className="fc-toolbar"><label>Location<select value={locationId??""} disabled={sample||busy} onChange={e=>setLocation(e.target.value||null)}><option value="">All permitted locations</option>{payload?.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Planning horizon<select value={snapshot&&!sample?snapshot.horizon:horizon} disabled={Boolean(snapshot)&&!sample} onChange={e=>setHorizon(Number(e.target.value) as 7|28)}><option value="7">Next 7 days</option><option value="28">Next 28 days</option></select></label><label>Chart metric<select value={metric} onChange={e=>setMetric(e.target.value as ForecastMetric)}>{forecastMetrics.map(m=><option key={m} value={m}>{forecastLabel[m]}</option>)}</select></label>{payload&&!sample&&<><button disabled={busy} onClick={()=>void perform(async()=>{await prefs({...payload.preferences,pinned:!payload.preferences.pinned});setNotice(payload.preferences.pinned?"Forecast unpinned.":"Seven-day forecast pinned to your dashboard.");})}>{payload.preferences.pinned?"Unpin overview":"Pin to dashboard"}</button><button className="fc-primary" disabled={busy||!locations.some(l=>Object.values(l.series).some(s=>s.available))||Boolean(snapshot)} onClick={()=>void saveRun()}>Issue forecast</button></>}</div>
 {error&&<p className="fc-notice fc-error" role="alert">{error} <button onClick={()=>setRefresh(x=>x+1)}>Retry</button></p>}{notice&&<p className="fc-notice" role="status">{notice}</p>}
 <nav className="fc-tabs" aria-label="Forecasting sections">{[...allowedTabs].map(t=><button key={t} aria-pressed={activeTab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {activeTab!=="Outlook"&&payload?<Suspense fallback={<div className="fc-skeleton" aria-label="Loading planner"/>}><Planning key={`${activeTab}:${sample}:${locationId}:${horizon}:${report?.issuedAt}`} mode={activeTab} currency={sample?"CAD":currency} report={report??null} sample={sample}/></Suspense>:<>
 {busy&&!report?<div className="fc-skeleton" role="status" aria-label="Loading reviewed forecast inputs"/>:<><section className="fc-kpis" aria-label="Upcoming period totals">{forecastMetrics.map(m=><article key={m}><span>{forecastLabel[m]}</span><strong>{report?.totals[m]===null||!report?"—":forecastFormat(report.totals[m],m,sample?"CAD":currency)}</strong><small>{report?.totals[m]===null?"Review the inputs below":snapshot&&!sample?`${snapshot.horizon} days from ${snapshot.locations[0]?.series[m].points[0]?.date??"original issue"}`:`Next ${report?.horizon??horizon} days, starting tomorrow`}</small></article>)}</section>{report?.aggregationReason&&<p className="fc-notice">{report.aggregationReason}</p>}
 {!locations.length&&<section className="fc-card"><h3>Your outlook starts with complete records.</h3><p>Connect a sales source, map its location, then review opening hours and import coverage. The forecast will appear here when its inputs support it.</p><button onClick={()=>navigate("Integrations")}>Review connections</button></section>}
 {locations.map(l=><section key={l.id} className="fc-result"><div className="fc-section-head"><h3>{l.name}</h3><small>Source updated {l.sourceCutoff?new Date(l.sourceCutoff).toLocaleString():"not yet"} · {l.timezone}</small></div><div className="fc-columns"><ForecastChart location={l} metric={metric}/><section className="fc-card"><p className="fc-eyebrow">ACTIONS TO REVIEW</p><h3>{l.series[metric].available?"Make room for the week ahead":"Complete your planning inputs"}</h3><ul>{l.series[metric].reasons.length?l.series[metric].reasons.map(r=><li key={r}>{r}</li>):<><li>Review {l.series.transactions.points.filter(p=>p.workload==="busier").length} potentially busier days against stock and coverage.</li><li>Check unusual dates, promotion costs and settlement timing before acting.</li></>}</ul><p>{snapshot&&!sample?`Observed on ${l.today}`:"Today’s observed"} {forecastLabel[metric].toLowerCase()}: <strong>{forecastFormat(l.observedToday?.[metric]??null,metric,l.currency)}</strong>. Partial activity is excluded from the future forecast.</p><details><summary>Method, assumptions and evaluation</summary><p>{l.series[metric].evaluation.basis}</p><dl><div><dt>Method</dt><dd>{l.series[metric].evaluation.method}</dd></div><div><dt>Held-out origins</dt><dd>{l.series[metric].evaluation.origins}</dd></div><div><dt>Daily MAE</dt><dd>{forecastFormat(l.series[metric].evaluation.mae,metric,l.currency)}</dd></div><div><dt>Seasonal benchmark MAE</dt><dd>{forecastFormat(l.series[metric].evaluation.baselineMae,metric,l.currency)}</dd></div><div><dt>Bias, actual minus forecast</dt><dd>{forecastFormat(l.series[metric].evaluation.bias,metric,l.currency)}</dd></div><div><dt>MASE</dt><dd>{l.series[metric].evaluation.mase??"Not defined"}</dd></div><div><dt>Later range coverage</dt><dd>{l.series[metric].evaluation.rangeCoverage===null?"Not calibrated":`${Math.round(l.series[metric].evaluation.rangeCoverage!*100)}% across ${l.series[metric].evaluation.rangeEvaluationOrigins} origins`}</dd></div></dl><p>{l.series[metric].evaluation.explanation}</p><ul>{l.notes.map(n=><li key={n}>{n}</li>)}</ul><p>{l.settings.notes}</p><small>{report?.modelVersion}</small></details></section></div>
 <section className="fc-card"><h3>Busy and quiet days</h3><p>Expected transactions relative to a normal open day. These are workload patterns, not foot traffic.</p><div className="fc-calendar">{l.series.transactions.points.map(d=><div key={d.date} className={`fc-day ${d.state} ${d.workload??""}`}><span>{new Date(d.date+"T12:00:00Z").toLocaleDateString("en-CA",{weekday:"short",month:"short",day:"numeric",timeZone:"UTC"})}</span><strong>{d.value===null?"—":forecastFormat(d.value,"transactions",l.currency)}</strong><span>{d.state==="ordinary"?d.workload:d.state==="unusual"?"Event to review":d.state}</span></div>)}</div><p className="fc-calendar-legend">Blue: busier · Pale blue: quieter · Grey: closed · Dashed: needs review. A 20% workload difference is a planning label, not a confidence score.</p><details><summary>Hourly and product detail</summary><p>This release forecasts reviewed daily location totals. Hourly forecasts, product-level demand and causal promotion effects stay unavailable until timestamped completeness, stock availability and matching evaluation support them. Current-day like-for-like comparisons remain in Sales.</p></details></section>
 {!sample&&!snapshot&&cap?.configure&&<ForecastSettingsEditor key={l.id+String(l.settings.reviewedAt)} location={l} busy={busy} save={settings=>perform(async()=>{await forecastRequest("/api/v1/forecasting",{action:"settings",locationId:l.id,settings,complete:true});setRefresh(x=>x+1);setNotice("Operating assumptions reviewed. Forecasts recalculated from the current records.");})}/>}</section>)}</>}
 {!sample&&payload&&<section className="fc-card"><h3>Your views and issued forecasts</h3><div className="fc-toolbar"><label>Save this view<input maxLength={40} value={viewName} onChange={e=>setViewName(e.target.value)} placeholder="For example, weekly stock review"/></label><button disabled={!viewName.trim()||busy} onClick={()=>void saveView()}>Save personal view</button>{payload.preferences.views.map(v=><button key={v.name} onClick={()=>{setLocation(v.locationId);setHorizon(v.horizon);setMetric(v.metric);setSnapshot(null);}}>{v.name}</button>)}</div><details><summary>Original forecasts ({payload.runs.length})</summary><p>Issued results remain unchanged when records or assumptions change. Access is checked again when you open them.</p>{payload.runs.map(r=><div className="fc-toolbar" key={r.id}><button onClick={()=>void perform(async()=>{const d=await forecastRequest(`/api/v1/forecasting?run=${encodeURIComponent(r.id)}${locationId?`&location=${encodeURIComponent(locationId)}`:""}`);setSnapshot(d.report);})}>{new Date(r.issuedAt).toLocaleString()} · {r.horizon} days</button>{cap?.export&&<button onClick={()=>void exportRun(r.id)}>Download CSV</button>}</div>)}</details></section>}
 </>}{one&&<small>Planning support only. No promotion, order, shift, advertising spend or accounting entry is created here.</small>}</div>;
}
function ForecastSettingsEditor({location,busy,save}:{location:ForecastReport["locations"][number];busy:boolean;save:(s:ForecastSettings)=>Promise<void>}){
 const [settings,setSettings]=useState<ForecastSettings>(()=>({...defaultForecastSettings(),...location.settings,hours:location.settings.hours.length?location.settings.hours:Array.from({length:7},()=>({open:true,from:"09:00",to:"17:00"})),reviewedFrom:location.settings.reviewedFrom||shiftForecastDate(location.today,-56),reviewedThrough:location.settings.reviewedThrough||shiftForecastDate(location.today,-1)})),[confirmed,setConfirmed]=useState(false);
 const update=<K extends keyof ForecastSettings>(key:K,value:ForecastSettings[K])=>setSettings(s=>({...s,[key]:value}));
 return <details className="fc-settings"><summary>Review location hours and source coverage</summary><p>Confirm completeness against your source reports. This review never creates sales. New or changed records invalidate the affected dates until reviewed again.</p><div className="fc-form-grid"><label>Review from<input type="date" value={settings.reviewedFrom} max={shiftForecastDate(location.today,-1)} onChange={e=>update("reviewedFrom",e.target.value)}/></label><label>Review through<input type="date" value={settings.reviewedThrough} max={shiftForecastDate(location.today,-1)} onChange={e=>update("reviewedThrough",e.target.value)}/></label><label>Current operating pattern began<input type="date" value={settings.regimeFrom} max={location.today} onChange={e=>update("regimeFrom",e.target.value)}/><small>Required when hours change. Older dates will be excluded.</small></label><label>Stock availability review<select value={settings.stockAvailability} onChange={e=>update("stockAvailability",e.target.value as ForecastSettings["stockAvailability"])}><option value="unknown">Stockouts may constrain recorded sales</option><option value="reviewed">Reviewed for known stock constraints</option></select></label></div>
 <fieldset><legend>Location hours, {location.timezone}</legend>{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((day,i)=><div className="fc-hours" key={day}><label className="fc-check"><input type="checkbox" checked={settings.hours[i].open} onChange={e=>update("hours",settings.hours.map((h,j)=>j===i?{...h,open:e.target.checked}:h))}/>{day.slice(0,3)}</label><input aria-label={`${day} opens`} type="time" value={settings.hours[i].from} onChange={e=>update("hours",settings.hours.map((h,j)=>j===i?{...h,from:e.target.value}:h))}/><input aria-label={`${day} closes`} type="time" value={settings.hours[i].to} onChange={e=>update("hours",settings.hours.map((h,j)=>j===i?{...h,to:e.target.value}:h))}/></div>)}</fieldset>
 <div className="fc-form-grid">{([['closures','Known closure dates'],['unusualDates','Holidays, promotions or stockout dates'],['zeroDates','Verified open dates with no sales']] as const).map(([key,label])=><label key={key}>{label}<textarea value={settings[key].join(", ")} onChange={e=>update(key,e.target.value.split(/[,\s]+/).filter(Boolean))} placeholder="YYYY-MM-DD, YYYY-MM-DD"/><small>Separate ISO dates with commas. Unusual dates are excluded from ordinary-day learning.</small></label>)}<label>Review notes<textarea value={settings.notes} maxLength={1000} onChange={e=>update("notes",e.target.value)}/></label></div><label className="fc-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the date range, source completeness, opening hours and exceptions.</label><button className="fc-primary" disabled={!confirmed||busy} onClick={()=>void save(settings)}>Save reviewed assumptions</button></details>;
}
