"use client";
import {useEffect,useState,type FormEvent,type ReactNode} from "react";
import {promotionScenario,inventoryProjection,capacityPlan,type PromotionPlan} from "../domain/forecast-planning";
import {forecastCashPreview,type CashAssumptions} from "../domain/forecast-cash";
import {shiftForecastDate,type ForecastReport} from "../domain/forecasting";
import type {ThirteenWeekCashFlow,ThirteenWeekCashFlowItem} from "../domain/thirteen-week-cash-flow";
import {apiFetch} from "./supabase-browser";
import FinanceChart from "./finance-chart";
import "./forecasting-workspace.css";
const numeric=(f:FormData,key:string,optional=false)=>{const value=String(f.get(key)??"").trim();if(!value){if(optional)return null;throw new Error("Complete the required assumptions. Blank costs are unknown; enter zero only when they do not apply.");}const n=Number(value);if(!Number.isFinite(n))throw new Error("Check the numerical assumptions.");return n;};
const requireGroup=(f:FormData,keys:string[],message:string)=>{const filled=keys.map(key=>String(f.get(key)??"").trim().length>0);if(filled.some(Boolean)&&!filled.every(Boolean))throw new Error(message);};
const cents=(f:FormData,key:string)=>{const n=numeric(f,key,true);return n===null?null:Math.round(n*100);};
const money=(n:number|null,currency:string)=>n===null?"Not available":new Intl.NumberFormat("en-CA",{style:"currency",currency}).format(n/100);
function Field({name,label,hint,type="number",optional=false,defaultValue,min="0",max,step="any"}:{name:string;label:string;hint?:string;type?:string;optional?:boolean;defaultValue?:string|number;min?:string;max?:string;step?:string}){return <label className="fc-field">{label}<input name={name} type={type} required={!optional} min={type==="number"?min:undefined} max={max} step={step} defaultValue={defaultValue}/>{hint&&<small>{hint}</small>}</label>;}
function Calculate({title,children,run,result}:{title:string;children:ReactNode;run:(f:FormData)=>void;result:ReactNode}){const [error,setError]=useState(""),[dirty,setDirty]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError("");try{run(new FormData(e.currentTarget));setDirty(false);}catch(e){setError(e instanceof Error?e.message:"Check the inputs.");}};return <section className="fc-plan"><h3>{title}</h3><p>Owner-entered assumptions. Results stay in this planning session and do not change your records.</p><form onSubmit={submit} onChange={()=>{setDirty(true);setError("");}}>{children}<button className="fc-primary">Calculate scenario</button></form>{error&&<p className="fc-notice fc-error" role="alert">{error}</p>}{dirty&&result&&<p className="fc-notice" role="status">Assumptions changed. Calculate again to update the results.</p>}{!error&&!dirty&&result}</section>;}
export function PromotionPlanner({currency}:{currency:string}){
 const [keys,setKeys]=useState([1]),[result,setResult]=useState<ReturnType<typeof promotionScenario>|null>(null),[scope,setScope]=useState("");
 return <Calculate title="Plan a promotion" run={f=>{const p:PromotionPlan={from:String(f.get("from")),to:String(f.get("to")),location:String(f.get("location")),channel:String(f.get("channel")),lines:keys.map(i=>({key:String(i),name:String(f.get(`name${i}`)),baselineUnits:numeric(f,`baseline${i}`)!,scenarioUnits:numeric(f,`scenario${i}`)!,priceCents:cents(f,`price${i}`)!,discountPercent:numeric(f,`discount${i}`)!,costCents:cents(f,`cost${i}`),variableCents:cents(f,`variable${i}`)})),advertisingCents:cents(f,"advertising"),staffingCents:cents(f,"staffing"),otherCents:cents(f,"other"),displacedContributionCents:cents(f,"displaced"),deferredContributionCents:cents(f,"deferred")};setResult(promotionScenario(p));setScope(`${p.location} · ${p.channel} · ${p.from} to ${p.to}`);}} result={result&&<div className="fc-result"><p className="fc-notice">{result.mode} · {scope}</p><div className="fc-table-scroll"><table><caption>Promotion compared with your baseline ({currency})</caption><thead><tr><th>Metric</th><th>Baseline</th><th>Promotion</th><th>Difference</th></tr></thead><tbody>{([['Units','units'],['Net sales','salesCents'],['Gross profit','grossCents'],['Contribution after costs','contributionCents']] as const).map(([label,key])=><tr key={key}><th>{label}</th><td>{key==="units"?result.baseline.units:money(result.baseline[key],currency)}</td><td>{key==="units"?result.scenario.units:money(result.scenario[key],currency)}</td><td>{key==="units"?result.scenario.units-result.baseline.units:result.baseline[key]===null||result.scenario[key]===null?"Not available":money(result.scenario[key]!-result.baseline[key]!,currency)}</td></tr>)}</tbody></table></div><p>{result.reason}</p><dl><div><dt>Units to preserve baseline contribution</dt><dd>{result.preserveContributionUnits??"Not defined for this mix or margin"}</dd></div><div><dt>Units to recover promotion costs only</dt><dd>{result.standaloneBreakEvenUnits??"Not defined"}</dd></div></dl><p>{result.boundary} Stock requirements equal scenario units. Review dated availability in Stock and settlement timing in Cash before acting.</p></div>}>
 <div className="fc-form-grid"><Field name="from" label="Starts" type="date"/><Field name="to" label="Ends, within 28 days" type="date"/><Field name="location" label="Location scope" type="text"/><Field name="channel" label="Channel scope" type="text"/></div>
 {keys.map((i,index)=><fieldset key={i}><legend>Product or category {index+1}</legend><div className="fc-form-grid"><Field name={`name${i}`} label="Product or category" type="text"/><Field name={`baseline${i}`} label="Baseline units without promotion" hint="Your assumption for this scope and date range."/><Field name={`scenario${i}`} label="Units with promotion" hint="Editable assumption, not an automatic discount uplift."/><Field name={`price${i}`} label={`Current price after ordinary discounts, before tax (${currency})`}/><Field name={`discount${i}`} label="Additional discount (%)" max="100"/><Field name={`cost${i}`} label={`Product cost per unit (${currency})`} optional/><Field name={`variable${i}`} label={`Other variable cost per unit (${currency})`} hint="Same cost assumed before and during the offer. Leave blank if unknown." optional/></div>{keys.length>1&&<button type="button" onClick={()=>{setKeys(k=>k.filter(x=>x!==i));setResult(null);}}>Remove this line</button>}</fieldset>)}<button type="button" disabled={keys.length>=10} onClick={()=>{setKeys(k=>[...k,Math.max(...k)+1]);setResult(null);}}>Add product or category</button>
 <div className="fc-form-grid">{[['advertising','Additional advertising spend'],['staffing','Additional staffing cost'],['other','Other additional costs'],['displaced','Contribution displaced from products outside these lines'],['deferred','Contribution shifted away from later weeks']] .map(([name,label])=><Field key={name} name={name} label={`${label} (${currency})`} optional hint="Unknown stays blank. Enter 0 only when reviewed and not applicable."/>)}</div><p>No causal promotion effect is inferred from before-and-after sales. Offers outside a comparable historical sample remain what-if scenarios.</p>
 </Calculate>;
}
function StockPlanner({currency}:{currency:string}){
 const [result,setResult]=useState<ReturnType<typeof inventoryProjection>|null>(null),[name,setName]=useState("");
 return <Calculate title="Stock and replenishment" run={f=>{requireGroup(f,["arrival","incoming"],"Enter both the delivery date and its units, or clear both.");requireGroup(f,["expiry","lot"],"Enter both the expiry date and its lot units, or clear both.");const start=String(f.get("start")),count=numeric(f,"days")!,demand=numeric(f,"daily")!,arrival=String(f.get("arrival")),expiry=String(f.get("expiry"));if(!Number.isInteger(count)||count<1||count>28)throw new Error("Choose one to 28 days.");setResult(inventoryProjection({start,units:numeric(f,"units")!,reserved:numeric(f,"reserved",true),demand:Array.from({length:count},(_,i)=>({date:shiftForecastDate(start,i),units:demand})),receipts:arrival?[{id:"planned-delivery",date:arrival,units:numeric(f,"incoming")!}]:[],lots:expiry?[{id:"expiring-lot",units:numeric(f,"lot")!,expires:expiry}]:[],pack:numeric(f,"pack")!,minimumUnits:numeric(f,"minimum")!,minimumSpendCents:cents(f,"minimumSpend")!,unitCostCents:cents(f,"cost"),cashCents:cents(f,"cash"),storageUnits:numeric(f,"storage",true),leadDays:numeric(f,"lead")!,bufferUnits:numeric(f,"buffer")!}));setName(String(f.get("product")));}} result={result&&<div className="fc-result"><h3>{name}</h3><p className="fc-notice">{result.reason}</p><dl><div><dt>First unmet-demand date</dt><dd>{result.firstStockout??"None under these assumptions"}</dd></div><div><dt>Unmet units</dt><dd>{result.unmetUnits??"Not available"}</dd></div><div><dt>Expiry exposure, units</dt><dd>{result.expiredUnits??"Not available"}</dd></div><div><dt>Additional order to review</dt><dd>{result.reorderUnits??"Complete constraints first"}</dd></div></dl><div className="fc-table-scroll"><table><caption>Demand versus achievable sales</caption><thead><tr><th>Date</th><th>Demand</th><th>Achievable</th><th>Unmet</th><th>Closing units</th></tr></thead><tbody>{result.days.map(d=><tr key={d.date}><th>{d.date}</th><td>{d.demand}</td><td>{d.achievable}</td><td>{d.unmet}</td><td>{d.closing}</td></tr>)}</tbody></table></div><p>Review expediting or rescheduling an existing delivery before adding another order. A suggested additional order can create a later surplus. No order is placed.</p></div>}>
 <div className="fc-form-grid"><Field name="product" label="Product, location and channel" type="text"/><Field name="start" label="Planning starts" type="date"/><Field name="days" label="Planning days" max="28" step="1"/><Field name="daily" label="Unconstrained daily unit demand" hint="Explicit flat demand assumption. Do not copy total store demand into one product."/><Field name="units" label="On-hand units"/><Field name="reserved" label="Reserved units" optional/><Field name="arrival" label="Expected delivery date" type="date" optional/><Field name="incoming" label="Units in that delivery" optional/><Field name="expiry" label="Existing lot expiry date" type="date" optional/><Field name="lot" label="On-hand units in that expiring lot" optional/><Field name="lead" label="New order lead time, days" step="1"/><Field name="buffer" label="Owner-selected buffer units"/><Field name="pack" label="Supplier pack size" min="1"/><Field name="minimum" label="Supplier minimum units"/><Field name="minimumSpend" label={`Supplier minimum spend (${currency})`}/><Field name="cost" label={`Unit purchasing cost (${currency})`} optional/><Field name="cash" label={`Cash available for this purchase (${currency})`} optional/><Field name="storage" label="Free storage headroom, additional units" hint="Subtract existing, reserved and other incoming stock first." optional/></div><p>Deliveries are assumed available before the day’s demand. Existing lots are unusable from their expiry date. Incoming expiry is unknown. Use a later arrival date if delivery timing is uncertain; stockout-constrained sales are not complete demand.</p>
 </Calculate>;
}
function CapacityPlanner(){const [result,setResult]=useState<ReturnType<typeof capacityPlan>>(null);return <Calculate title="Coverage to review" run={f=>setResult(capacityPlan({transactions:numeric(f,"transactions")!,openHours:numeric(f,"hours")!,minimumStaff:numeric(f,"staff")!,transactionsPerStaffHour:numeric(f,"productivity")!,fixedTaskHours:numeric(f,"tasks")!}))} result={result&&<div className="fc-result"><div className="fc-kpis"><article><span>Aggregate coverage</span><strong>{result.staffHours} staff-hours</strong><small>{result.label}</small></article></div><p>{result.boundary}</p></div>}><div className="fc-form-grid"><Field name="transactions" label="Expected transactions for this period"/><Field name="hours" label="Total opening hours for the same period"/><Field name="staff" label="Minimum staff present while open"/><Field name="productivity" label="Transactions handled per staff-hour" hint="Owner assumption, not an employee score."/><Field name="tasks" label="Additional fixed task staff-hours" hint="Exclude tasks already counted in transaction productivity."/></div></Calculate>;}
type CashData={currency:string;flow:ThirteenWeekCashFlow;schedule:ThirteenWeekCashFlowItem[]};
function CashPlanner({currency,report,sample}:{currency:string;report:ForecastReport|null;sample:boolean}){
 const [data,setData]=useState<CashData|null>(null),[error,setError]=useState(""),[result,setResult]=useState<{name:string;preview:ReturnType<typeof forecastCashPreview>}[]|null>(null);
 useEffect(()=>{if(sample)return;const controller=new AbortController();void apiFetch("/api/v1/bookloq",{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error?.message??"BookLoQ cash is unavailable.");setData({currency:d.bookloq.organization.currency,flow:d.bookloq.thirteenWeekCashFlow,schedule:d.bookloq.planningSchedule});}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[sample]);
 if(sample)return <section className="fc-card"><h3>Cash plans stay separate</h3><p>Return to your business to connect an authorized BookLoQ cash outlook. Fictional sales are never combined with live bank balances.</p></section>;
 if(error)return <p className="fc-notice fc-error" role="alert">{error}</p>;
 if(!data)return <div className="fc-skeleton" role="status" aria-label="Loading authorized BookLoQ cash plan"/>;
 if(data.currency!==currency)return <section className="fc-card"><h3>Cash and sales use different currencies</h3><p>BookLoQ uses {data.currency}; this workspace view uses {currency}. Reconcile the base currency before combining these plans. No conversion is assumed.</p></section>;
 if(data.flow.status!=="available")return <section className="fc-card"><h3>Review cash coverage in BookLoQ</h3><p>A verified opening balance, dated obligations and consistent currencies are required. {data.flow.boundary}</p></section>;
 const eligible=Boolean(report?.locations.length&&report.aggregationReason===null&&report.locations.every(l=>l.currency===currency&&l.series.netSalesCents.total!==null));
 return <Calculate title="Cash decisions, with the timing visible" run={f=>{requireGroup(f,["extraLabel","extraDate","extraAmount"],"Complete the additional outflow purpose, date and amount, or clear all three.");const useSales=f.get("useSales")==="on";if(useSales&&!eligible)throw new Error("This sales forecast does not have complete compatible location coverage.");const sales=useSales?report!.locations[0].series.netSalesCents.points.map((d,i)=>({date:d.date,netSalesCents:report!.locations.reduce((sum,l)=>sum+l.series.netSalesCents.points[i].value!,0)})):[];const common:CashAssumptions={additionalSalesConfirmed:f.get("confirmed")==="on",cashSharePercent:numeric(f,"share")!,feePercent:numeric(f,"fees")!,taxPercent:numeric(f,"tax")!,settlementDays:numeric(f,"settlement")!,collectionDelayDays:0,volumeChangePercent:0,bufferCents:cents(f,"buffer")!,additional:[]};const extra=String(f.get("extraDate"));if(extra&&cents(f,"extraAmount")===null)throw new Error("Enter the additional outflow amount, or remove its date.");if(extra)common.additional=[{id:"discretionary",dueDate:extra,amountCents:-cents(f,"extraAmount")!,label:String(f.get("extraLabel"))}];setResult([['Base',0,0],['Downside',numeric(f,"down")!,numeric(f,"delay")!],['Upside',numeric(f,"up")!,0]].map(([name,change,delay])=>({name:String(name),preview:forecastCashPreview(data.flow,data.schedule,sales,{...common,volumeChangePercent:Number(change),collectionDelayDays:Number(delay)})})));}} result={result&&<div className="fc-result"><FinanceChart title="13-week cash scenarios" description="Owner assumptions over the existing BookLoQ plan. These lines are not statistical ranges." currency={currency} forecast points={data.flow.weeks.map((w,i)=>({label:`W${w.index}`,detail:w.weekEnd,values:result.map(r=>r.preview.flow.weeks[i].planningClosingCashCents)}))} series={[{label:"Base",color:"blue",kind:"line",dashed:true},{label:"Downside",color:"coral",kind:"line",dashed:true},{label:"Upside",color:"mint",kind:"line",dashed:true}]}/><div className="fc-table-scroll"><table><caption>Daily cash pressure, {currency}</caption><thead><tr><th>Scenario</th><th>Lowest balance</th><th>Date</th><th>Days below buffer</th></tr></thead><tbody>{result.map(r=><tr key={r.name}><th>{r.name}</th><td>{money(r.preview.lowestCents,currency)}</td><td>{r.preview.lowestDate}</td><td>{r.preview.belowBufferDates.length}</td></tr>)}</tbody></table></div><p>{result[0].preview.boundary}</p><p>Sales coverage ends {result[0].preview.salesThrough??"with no additional forecast sales"}. {result[0].preview.excludedBeyondHorizon} movements fall beyond the displayed horizon.</p></div>}>
 <p>Existing invoices, bills and purchase commitments are reused once. Collection delays replace their timing, rather than adding duplicate receipts.</p><label className="fc-check"><input type="checkbox" name="useSales" disabled={!eligible}/>Include eligible future net sales through {report?.horizon??7} days</label><div className="fc-form-grid"><Field name="share" label="Additional cash-sales share (%)" max="100" hint="Exclude forecast sales already represented by invoices, payouts or deposits."/><Field name="fees" label="Effective processor fees on collected gross cash (%)" max="100"/><Field name="tax" label="Effective sales tax collected (%)" max="100" hint="This adds cash collected, not revenue or profit. Plan the remittance separately."/><Field name="settlement" label="Settlement lag, calendar days" step="1" max="90"/><Field name="buffer" label={`Minimum cash buffer (${currency})`}/><Field name="down" label="Downside future sales change (%)" min="-100" max="0"/><Field name="delay" label="Downside invoice collection delay, days" step="1" max="90"/><Field name="up" label="Upside future sales change (%)" max="1000"/><Field name="extraLabel" label="Additional outflow purpose" type="text" optional hint="For example, payroll, tax, capital spend or a new purchase."/><Field name="extraDate" label="Additional outflow date" type="date" optional/><Field name="extraAmount" label={`Additional outflow (${currency})`} optional/></div><label className="fc-check"><input type="checkbox" name="confirmed" required/>These future cash sales and additional plans exclude amounts already in invoices, payouts, bank deposits and commitments.</label><details><summary>Existing dated planning schedule</summary><div className="fc-table-scroll"><table><caption>BookLoQ commitments and expected movements</caption><thead><tr><th>Item</th><th>Due</th><th>Amount</th><th>Basis</th></tr></thead><tbody>{data.schedule.map(i=><tr key={i.id}><th>{i.label}</th><td>{i.dueDate}</td><td>{money(i.amountCents*(i.direction==="out"?-1:1),currency)}</td><td>{i.certainty}</td></tr>)}</tbody></table></div></details>
 </Calculate>;
}
export default function ForecastPlanningPanels({mode,currency,report,sample}:{mode:string;currency:string;report:ForecastReport|null;sample:boolean}){return mode==="Promotion"?<PromotionPlanner currency={currency}/>:mode==="Stock"?<StockPlanner currency={currency}/>:mode==="Capacity"?<CapacityPlanner/>:<CashPlanner currency={currency} report={report} sample={sample}/>;}
