"use client";

import { useEffect, useState } from "react";
import { apiFetch } from "./supabase-browser";

type GrowthData = { growth: { status: "available" | "unavailable"; reason: string | null; channels: { source: string; leads: number; customers: number; transactions: number; revenueCents: number; grossProfitCents: number | null }[]; insight: null | { title: string; explanation: string; estimatedDiscoveryActionChange: number | null; confidence: string } }; period: { since: string; through: string }; sourceBoundary: string };
const money = (cents: number, currency: string) => new Intl.NumberFormat("en-CA", { style: "currency", currency, maximumFractionDigits: 0 }).format(cents / 100);

export default function GrowthWorkspace({ currency, navigate }: { currency: string; navigate: (view: "Integrations") => void }) {
  const [data, setData] = useState<GrowthData | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); void apiFetch("/api/v1/growth", { headers: { Accept: "application/json" }, signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Growth intelligence could not be loaded."); setData(body); }).catch((caught) => { if (caught instanceof Error && caught.name !== "AbortError") setError(caught.message); }); return () => controller.abort(); }, []);
  return <div className="content module-page growth-page"><section className="module-hero"><div><p>LOCAL BUSINESS GROWTH INTELLIGENCE</p><h2>Connect discovery to customers and POS revenue.</h2><span>First-touch paths join Google, social, website and phone activity to customer and transaction records using a shared pseudonymous journey reference.</span></div><div className="module-signal"><small>ATTRIBUTION WINDOW</small><b>{data ? "12 months" : "Loading…"}</b><span>Verified events only</span></div></section>{error && <article className="card growth-empty"><b>Growth intelligence needs attention</b><span>{error}</span></article>}{data?.growth.status === "unavailable" && <article className="card growth-empty"><b>Attribution is unavailable</b><span>{data.growth.reason}</span><button onClick={() => navigate("Integrations")}>Connect verified sources →</button></article>}{data?.growth.status === "available" && <><article className="card growth-table"><div className="card-head"><div><p className="card-kicker">SOURCE → CUSTOMER → POS</p><h3>Revenue attribution</h3></div><span>{data.period.since} to {data.period.through}</span></div><div className="growth-row growth-head"><span>Source</span><span>Leads</span><span>Customers</span><span>Transactions</span><span>Revenue</span><span>Gross profit</span></div>{data.growth.channels.map((row) => <div className="growth-row" key={row.source}><b>{row.source}</b><span>{row.leads}</span><span>{row.customers}</span><span>{row.transactions}</span><strong>{money(row.revenueCents, currency)}</strong><span>{row.grossProfitCents === null ? "Unavailable" : money(row.grossProfitCents, currency)}</span></div>)}</article>{data.growth.insight && <article className="card growth-insight"><p className="card-kicker">SEARCH VISIBILITY</p><h3>{data.growth.insight.title}</h3><p>{data.growth.insight.estimatedDiscoveryActionChange === null ? "Discovery-action impact unavailable." : `${Math.abs(data.growth.insight.estimatedDiscoveryActionChange)} ${data.growth.insight.estimatedDiscoveryActionChange < 0 ? "fewer" : "more"} measured discovery actions.`}</p><span>{data.growth.insight.explanation}</span></article>}</>}<article className="card growth-boundary"><b>Evidence boundary</b><span>{data?.sourceBoundary ?? "Loading source contract…"}</span></article></div>;
}
