"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { apiFetch } from "./supabase-browser";
import { businessClock } from "../domain/intraday-sales";
import { parseMinorAmount, parseQuantityMilli, validateInventoryContent, supplierProposal, variantReturnReport, invoiceExceptions, type InventoryRecordKind, type SupplierPolicy, type VariantReturns, type InvoiceReview, type ReceiptLine } from "../domain/workflow-inventory";
import "./inventory-workflows.css";

type Position={id:string;sku:string;productName:string;unit:"each"|"g"|"ml";quantityMilli:number;version:number};
type OrderLine={id:string;orderNumber:string;supplierName:string;status:string;currency:string;lineId:string;sku:string;description:string;quantity:number;receivedQuantity:number;unitCostCents:number};
type Saved={id:string;kind:InventoryRecordKind;currency:string;version:number;updatedAt:number;payload:Record<string,unknown>;report:unknown};
type Receipt={id:string;purchaseOrderId:string;source:string;occurredDate:string;lines:ReceiptLine[];reversedAt:number|null;reversalReason:string|null};
type Data={location:{id:string;name:string;currency:string;timezone:string}|null;locations:{id:string;name:string}[];positions:Position[];records:Saved[];receipts:Receipt[];orders:OrderLine[];lots:{id:string;sku:string;productName:string;lotNumber:string;quantityRemaining:number;status:string}[];movements:{id:string;sku:string;unit:string;quantityDelta:number;reason:string;sourceReference:string;occurredDate:string}[];permissions:{stockWrite:boolean;receive:boolean;kinds:InventoryRecordKind[];editableKinds:InventoryRecordKind[]};boundary?:string;truncated?:boolean};
type Editor={locationId:string;action:"open_stock"|"count_stock"|"receive"|"reverse_receipt"|"save_record";kind?:InventoryRecordKind;id?:string;version?:number;fields:Record<string,string>;lines:Record<string,{accepted:string;rejected:string;billed:string;cost:string}>};
type Field={key:string;label:string;type?:"date"|"money"|"number"|"text"|"textarea";optional?:boolean};
const common:Field[]=[{key:"source",label:"Source or supporting document reference"},{key:"asOf",label:"Evidence date",type:"date"}];
const fieldsets:Record<InventoryRecordKind,Field[]>={
  supplier:[{key:"sku",label:"SKU"},{key:"supplier",label:"Supplier"},...common,{key:"soldUnits",label:"Units sold while in stock",type:"number"},{key:"sellingDays",label:"In-stock selling days",type:"number"},{key:"leadDays",label:"Supplier lead time (days)",type:"number"},{key:"reviewDays",label:"Days until your next buying review",type:"number"},{key:"safetyUnits",label:"Safety stock (units)",type:"number"},{key:"packSize",label:"Units per case",type:"number"},{key:"minimumOrder",label:"Minimum order (units)",type:"number"},{key:"onHand",label:"Usable on-hand units",type:"number"},{key:"inbound",label:"Confirmed inbound units",type:"number"},{key:"committed",label:"Units committed to customers",type:"number"},{key:"unitCostCents",label:"Unit cost, before tax and freight",type:"money"},{key:"cashBudgetCents",label:"Reviewed purchase cash budget",type:"money",optional:true},{key:"storageLimit",label:"Maximum units you can store",type:"number",optional:true},{key:"shelfDays",label:"Usable shelf life on arrival (days)",type:"number",optional:true}],
  lot_case:[...common,{key:"units",label:"Affected units",type:"number"},{key:"nextAction",label:"Next action and responsible person",type:"textarea"},{key:"resolution",label:"Resolution and supporting evidence",type:"textarea",optional:true},{key:"evidenceUrl",label:"Official notice or evidence link (HTTPS)",optional:true},{key:"creditCents",label:"Recorded supplier credit",type:"money",optional:true}],
  returns:[{key:"style",label:"Product style / family"},{key:"variant",label:"Variant SKU"},{key:"size",label:"Size",optional:true},{key:"colour",label:"Colour",optional:true},...common,{key:"from",label:"Sale-cohort start",type:"date"},{key:"to",label:"Sale-cohort end",type:"date"},{key:"returnWindowDays",label:"Return window (days)",type:"number"},{key:"soldUnits",label:"Units sold in this cohort",type:"number"},{key:"returnedUnits",label:"Returns matched to these sales",type:"number"},{key:"fitReturns",label:"Returns attributed to fit",type:"number"},{key:"defectReturns",label:"Returns attributed to defects",type:"number"},{key:"otherReturns",label:"Returns with another recorded reason",type:"number"},{key:"restockableUnits",label:"Returned units approved for resale",type:"number"},{key:"refundCents",label:"Matched refund amount",type:"money",optional:true}],
  invoice_review:[{key:"invoiceReference",label:"Supplier invoice reference"},...common],
};
const kindTitles:Record<InventoryRecordKind,string>={supplier:"Supplier planning",lot_case:"Lot action cases",returns:"Variant returns",invoice_review:"Invoice exceptions"};
const title=(editor:Editor)=>editor.action==="open_stock"?"Start a managed stock record":editor.action==="count_stock"?"Review a stock count":editor.action==="receive"?"Receive against a purchase order":editor.action==="reverse_receipt"?"Reverse a receipt":`${editor.id?"Review":"Add"} ${kindTitles[editor.kind!] .toLowerCase()}`;
const money=(value:number,currency:string)=>new Intl.NumberFormat("en-CA",{style:"currency",currency}).format(value/100);
const percent=(value:number|null)=>value===null?"Not measured":`${(value*100).toFixed(1)}%`;
const timestamp=(value:number)=>new Intl.DateTimeFormat("en-CA",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(new Date(value));
async function response(r:Response) { const body=await r.json();if(!r.ok)throw Error(body.error?.message||"The inventory workflow could not be loaded.");return body; }
function RecordSummary({record}: {record:Saved}) {
  if(record.kind==="supplier") {const r=supplierProposal(record.payload as unknown as SupplierPolicy);return <><strong>{r.proposedUnits} units to review</strong><p>{money(r.costCents,record.currency)} before tax and freight · {r.status==="blocked"?"Minimum order cannot fit your constraints":r.status==="constrained"?"Reduced by your constraints":"Ready for your review"}</p>{r.constraints.length>0&&<p>Limited by {r.constraints.join(", ").toLowerCase()}.</p>}{r.missingLimits.length>0&&<p>Not applied: {r.missingLimits.join(", ").toLowerCase()}.</p>}</>;}
  if(record.kind==="returns") {const r=variantReturnReport(record.payload as unknown as VariantReturns);return <><strong>{percent(r.returnRate)} observed return rate</strong><p>{r.cohortMature?"Return window complete":`${r.daysUntilMature} days remain in this cohort’s return window`}</p><p>{r.unclassified} unclassified returns · {r.unrestockableUnits} units not approved for resale</p><p>{r.attention}</p></>;}
  if(record.kind==="invoice_review") {const r=invoiceExceptions(record.payload as unknown as InvoiceReview),exceptions=r.filter(l=>l.status!=="matched");return <><strong>{exceptions.length} line exceptions</strong><p>Compared with accepted units and agreed unit costs when reviewed. This does not create or pay a bill.</p>{r.map(l=><p key={l.lineId}>Line {r.indexOf(l)+1}: {l.billed} billed / {l.accepted} accepted · Price difference {money(l.priceDifferenceCents,record.currency)}</p>)}</>;}
  return <><strong>{String(record.payload.status)} · {String(record.payload.units)} affected units</strong><p>{String(record.payload.nextAction)}</p>{record.payload.resolution?<p>{String(record.payload.resolution)}</p>:null}{record.payload.evidenceUrl?<a href={String(record.payload.evidenceUrl)} target="_blank" rel="noreferrer">Open supporting notice</a>:null}<p>Resolution does not release quarantined stock or post a supplier credit automatically.</p></>;
}

export function InventoryWorkflows({activeLocationId}:{activeLocationId?:string|null}) {
  const [data,setData]=useState<Data|null>(null),[locationId,setLocationId]=useState(activeLocationId??""),[tab,setTab]=useState("stock"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[editor,setEditor]=useState<Editor|null>(null),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState(false),[preview,setPreview]=useState<Saved|null>(null),[history,setHistory]=useState<{id:string;entries:{version:number;payloadJson:string;createdAt:number}[]}|null>(null);
  const read=useRef<AbortController|null>(null),write=useRef<AbortController|null>(null),mutation=useRef<string|null>(null),heading=useRef<HTMLHeadingElement|null>(null),returnFocus=useRef<HTMLElement|null>(null);
  const load=useCallback(()=>{
    read.current?.abort(); const controller=new AbortController(); read.current=controller; const query=activeLocationId||locationId;
    return apiFetch(`/api/v1/inventory-workflows${query?`?locationId=${encodeURIComponent(query)}`:""}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])}).then(response)
      .then((next:Data)=>{if(!controller.signal.aborted)setData(next);})
      .catch((error:unknown)=>{if(!controller.signal.aborted){setData(null);setError(error instanceof Error?error.message:"Unable to load inventory workflows.");}})
      .finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  },[activeLocationId,locationId]);
  useEffect(()=>{void load();return()=>{read.current?.abort();};},[load]);
  useEffect(()=>()=>{write.current?.abort();},[]);
  const editorFocusKey=editor?`${editor.action}:${editor.id??"new"}:${editor.kind??""}`:"";
  useEffect(()=>{if(editorFocusKey)heading.current?.focus();},[editorFocusKey]);
  function close(){if(busy)return;setEditor(null);setPreview(null);setReviewed(false);setHistory(null);mutation.current=null;requestAnimationFrame(()=>returnFocus.current?.focus());}
  function changed(next:Editor){setEditor(next);setReviewed(false);setPreview(null);setError("");mutation.current=null;}
  function begin(action:Editor["action"],kind?:InventoryRecordKind,row?:Saved|Position|Receipt){returnFocus.current=document.activeElement as HTMLElement;setError("");setMessage("");setReviewed(false);setPreview(null);setHistory(null);mutation.current=null;const date=data?.location?businessClock(new Date(),data.location.timezone)?.date??"":"";let fields:Record<string,string>={date,asOf:date,unit:"each",issue:"quality",status:"open"};let lines:Editor["lines"]={};
    if(row&&"payload" in row){fields={...fields,...Object.fromEntries(Object.entries(row.payload).filter(([key])=>key!=="lines").map(([key,value])=>[key,value===null?"":key.endsWith("Cents")?String(Number(value)/100):String(value)]))};if(kind==="invoice_review")lines=Object.fromEntries(((row.payload.lines??[]) as InvoiceReview["lines"]).map(l=>[l.lineId,{accepted:"",rejected:"",billed:String(l.billed),cost:String(l.billedUnitCostCents/100)}]));}
    if(row&&"quantityMilli" in row)fields={...fields,sku:row.sku,productName:row.productName,unit:row.unit,quantity:String(row.quantityMilli/1000)};
    setEditor({locationId:data?.location?.id??"",action,kind,id:row?.id,version:row&&"version" in row?row.version:undefined,fields,lines});
  }
  function field(key:string,value:string){if(editor)changed({...editor,fields:{...editor.fields,[key]:value}});}
  function recordContent(){if(!editor?.kind)throw Error("Choose a record type.");const result:Record<string,unknown>={...editor.fields};for(const f of fieldsets[editor.kind]){const value=editor.fields[f.key]??"";if(f.type==="money")result[f.key]=value===""&&f.optional?null:parseMinorAmount(value);if(f.type==="number")result[f.key]=value===""&&f.optional?null:/^\d+$/.test(value)?Number(value):NaN;}
    if(editor.kind==="invoice_review")result.lines=(data?.orders??[]).filter(l=>l.id===editor.fields.purchaseOrderId).filter(l=>(editor.lines[l.lineId]?.billed??"")!=="").map(l=>({lineId:l.lineId,ordered:l.quantity,accepted:l.receivedQuantity,billed:Number(editor.lines[l.lineId]?.billed),agreedUnitCostCents:l.unitCostCents,billedUnitCostCents:parseMinorAmount(editor.lines[l.lineId]?.cost??"")}));
    return validateInventoryContent(editor.kind,result);
  }
  async function save(event:FormEvent){event.preventDefault();if(!editor||!data?.location||busy||!reviewed)return;if(editor.locationId!==data.location.id){setError("Your location changed. Close this draft and return to its original location before saving.");return;}setBusy(true);setError("");const controller=new AbortController();write.current=controller;
    try {mutation.current??=crypto.randomUUID();const body:Record<string,unknown>={action:editor.action,mutationKey:mutation.current,locationId:data.location.id,reviewed:true,id:editor.id,expectedVersion:editor.version,...editor.fields};
      if(editor.action==="open_stock"||editor.action==="count_stock")body.quantityMilli=parseQuantityMilli(editor.fields.quantity??"");
      if(editor.action==="save_record"){body.kind=editor.kind;body.record=recordContent();delete body.date;}
      if(editor.action==="receive")body.lines=(data.orders??[]).filter(l=>l.id===editor.fields.purchaseOrderId).map(l=>({lineId:l.lineId,accepted:Number(editor.lines[l.lineId]?.accepted||0),rejected:Number(editor.lines[l.lineId]?.rejected||0)})).filter(l=>l.accepted||l.rejected);
      await response(await apiFetch("/api/v1/inventory-workflows",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(25000)])}));
      if(!controller.signal.aborted){setEditor(null);setPreview(null);setReviewed(false);mutation.current=null;setMessage("Reviewed activity saved. Its history is retained.");setLoading(true);await load();requestAnimationFrame(()=>returnFocus.current?.focus());}
    }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"The action could not be saved. Your entries remain available.");}finally{if(!controller.signal.aborted)setBusy(false);}
  }
  async function showHistory(row:Saved){setError("");try {const body=await response(await apiFetch(`/api/v1/inventory-workflows?history=${encodeURIComponent(row.id)}`));setHistory({id:row.id,entries:body.entries});}catch(e){setError(e instanceof Error?e.message:"History could not be loaded.");}}
  const orderGroups=[...new Map((data?.orders??[]).map(line=>[line.id,line])).values()],isRecord=editor?.action==="save_record",currency=data?.location?.currency??"CAD";
  const renderField=(f:Field)=><label key={f.key}>{f.label}{f.optional?<span className="inventory-workflows-optional">Optional</span>:null}{f.type==="textarea"?<textarea value={editor?.fields[f.key]??""} onChange={e=>field(f.key,e.target.value)} maxLength={600} required={!f.optional}/>:<input type={f.type==="date"?"date":"text"} inputMode={f.type==="money"?"decimal":f.type==="number"?"numeric":undefined} value={editor?.fields[f.key]??""} onChange={e=>field(f.key,e.target.value)} maxLength={f.type==="money"||f.type==="number"?16:300} required={!f.optional}/>}</label>;
  return <section className="inventory-workflows" aria-label="Inventory workflows">
    <header><div><p className="inventory-workflows-eyebrow">Stock, suppliers and follow-through</p><h2>Keep every movement accountable.</h2><p>Receive with confidence, review exceptions and decide what to buy next.</p></div>{data&&<label>Location<select value={activeLocationId||locationId||data.location?.id||""} disabled={Boolean(activeLocationId)||Boolean(editor)||busy} onChange={e=>{setLoading(true);setError("");setLocationId(e.target.value);setHistory(null);}}>{data.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}</header>
    <nav aria-label="Inventory workflow views">{[{id:"stock",label:"Managed stock"},{id:"receiving",label:"Receiving"},...(data?.permissions.kinds??[]).map(kind=>({id:kind,label:kindTitles[kind]}))].map(item=><button key={item.id} type="button" aria-pressed={tab===item.id} disabled={busy||Boolean(editor)} onClick={()=>{setTab(item.id);setHistory(null);setError("");}}>{item.label}</button>)}</nav>
    {error&&<div role="alert" className="inventory-workflows-error">{error}{!editor&&<button type="button" onClick={()=>{setLoading(true);setError("");void load();}}>Try again</button>}</div>}{message&&<p role="status" className="inventory-workflows-success">{message}</p>}
    {loading||(Boolean(activeLocationId||locationId)&&Boolean(data?.location)&&data?.location?.id!==(activeLocationId||locationId))?<p role="status">Loading your stock and review records…</p>:!data?.location?<p>Select an available business location to begin.</p>:<>
      <p className="inventory-workflows-boundary">{data.boundary}</p>{data.truncated&&<p className="inventory-workflows-boundary">This view is bounded to 500 records and the latest 100 movements or receipts. Earlier history is retained.</p>}
      {editor?<form className="inventory-workflows-editor" onSubmit={save} aria-busy={busy}>
        <div className="inventory-workflows-editor-heading"><h3 ref={heading} tabIndex={-1}>{title(editor)}</h3><button type="button" disabled={busy} onClick={close}>Close</button></div>
        <p>{data.location.name} · {currency}. Changes are recorded only after your review.</p>{editor.locationId!==data.location.id&&<p role="alert">This draft belongs to another location and cannot be saved here. Close it before continuing.</p>}
        <fieldset disabled={busy}>
          {(editor.action==="open_stock"||editor.action==="count_stock")&&<>{editor.action==="open_stock"?<>{renderField({key:"sku",label:"SKU"})}{renderField({key:"productName",label:"Product name"})}<label>Base unit<select value={editor.fields.unit} onChange={e=>field("unit",e.target.value)}><option value="each">Each</option><option value="g">Grams</option><option value="ml">Millilitres</option></select></label></>:<p><strong>{editor.fields.productName}</strong> · {editor.fields.sku} · {editor.fields.unit}</p>}{renderField({key:"quantity",label:"Physically counted quantity"})}{renderField({key:"source",label:"Count reference and reason"})}{renderField({key:"date",label:"Count date",type:"date"})}<p>Count only this managed stock. Do not copy a connected POS balance into a second stock record.</p></>}
          {(editor.action==="receive"||editor.kind==="invoice_review")&&<label>Purchase order<select value={editor.fields.purchaseOrderId??""} required onChange={e=>changed({...editor,fields:{...editor.fields,purchaseOrderId:e.target.value},lines:{}})}><option value="">Choose an order</option>{orderGroups.filter(o=>editor.kind==="invoice_review"||["sent","acknowledged","partially_received"].includes(o.status)).map(o=><option key={o.id} value={o.id}>{o.orderNumber} · {o.supplierName}</option>)}</select></label>}
          {editor.action==="receive"&&<>{renderField({key:"source",label:"Delivery note reference"})}{renderField({key:"date",label:"Received date",type:"date"})}<p>Accepted units enter your managed stock. Rejected units remain separate. Each accepted SKU requires an opening count in units of “Each”.</p></>}
          {editor.action==="reverse_receipt"&&<>{renderField({key:"source",label:"Why is this receipt being reversed?",type:"textarea"})}{renderField({key:"date",label:"Reversal date",type:"date"})}<p>The original receipt stays in history. Its accepted stock will be removed atomically. Reversal is blocked if stock is insufficient or the order has advanced to invoice matching.</p></>}
          {editor.kind==="lot_case"&&<><label>Lot<select required value={editor.fields.lotId??""} onChange={e=>field("lotId",e.target.value)}><option value="">Choose a recorded lot</option>{data.lots.map(l=><option key={l.id} value={l.id}>{l.productName} · {l.lotNumber||l.sku} · {l.quantityRemaining} units</option>)}</select></label><label>Issue<select value={editor.fields.issue} onChange={e=>field("issue",e.target.value)}><option value="quality">Quality / best-before review</option><option value="expiry">Actual expiry</option><option value="recall">Reviewed recall notice</option><option value="damage">Damage</option></select></label><label>Case status<select value={editor.fields.status} onChange={e=>field("status",e.target.value)}><option value="open">Open</option><option value="quarantined">Quarantine the whole recorded lot</option><option value="resolved">Resolved with evidence</option></select></label><p>Quarantine changes the recorded lot status. Resolution does not release it, change quantities or post credit. Use the lot record to review any release or disposal separately.</p></>}
          {isRecord&&fieldsets[editor.kind!].map(renderField)}
          {(editor.action==="receive"||editor.kind==="invoice_review")&&data.orders.filter(l=>l.id===editor.fields.purchaseOrderId).map(line=><fieldset key={line.lineId} className="inventory-workflows-line"><legend>{line.description} · {line.sku||"Missing SKU"}</legend><p>{line.quantity} ordered · {line.receivedQuantity} accepted so far · {money(line.unitCostCents,currency)} agreed per unit</p>{(editor.action==="receive"?[{key:"accepted",label:"Accept units"},{key:"rejected",label:"Reject units"}]:[{key:"billed",label:"Billed units"},{key:"cost",label:"Billed unit cost before tax"}]).map(f=><label key={f.key}>{f.label}<input inputMode={f.key==="cost"?"decimal":"numeric"} value={editor.lines[line.lineId]?.[f.key as "accepted"]??""} onChange={e=>changed({...editor,lines:{...editor.lines,[line.lineId]:{...(editor.lines[line.lineId]??{accepted:"",rejected:"",billed:"",cost:""}),[f.key]:e.target.value}}})}/></label>)}</fieldset>)}
        </fieldset>
        {isRecord&&editor.kind!=="lot_case"&&<button type="button" disabled={busy} onClick={()=>{setError("");try{const content=recordContent();setPreview({id:"preview",kind:editor.kind!,currency,version:1,updatedAt:Date.now(),payload:content as unknown as Record<string,unknown>,report:null});}catch(e){setError(e instanceof Error?e.message:"Review the fields.");}}}>Preview calculation</button>}
        {preview&&<div className="inventory-workflows-preview"><RecordSummary record={preview}/></div>}
        <label className="inventory-workflows-consent"><input type="checkbox" checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/><span>I checked the quantities, source and selected location. Save this reviewed action.</span></label>
        <footer><button type="button" disabled={busy} onClick={close}>Cancel</button><button type="submit" className="inventory-workflows-primary" disabled={busy||!reviewed||editor.locationId!==data.location.id}>{busy?"Saving…":"Save reviewed activity"}</button></footer>
      </form>:<>
        {tab==="stock"&&<><div className="inventory-workflows-toolbar"><h3>Managed stock</h3>{data.permissions.stockWrite&&<button type="button" className="inventory-workflows-primary" onClick={()=>begin("open_stock")}>Record opening count</button>}</div>{!data.positions.length?<div className="inventory-workflows-empty"><h3>Your stock record starts with a count.</h3><p>Enter one reviewed product and its base unit. Every receipt, correction and approved preparation movement will follow from that count.</p></div>:<div className="inventory-workflows-grid">{data.positions.map(p=><article key={p.id}><span>{p.sku} · {p.unit}</span><h4>{p.productName}</h4><strong>{(p.quantityMilli/1000).toLocaleString("en-CA")} {p.unit}</strong><p>Recorded stock · revision {p.version}</p>{data.permissions.stockWrite&&<button type="button" onClick={()=>begin("count_stock",undefined,p)}>Review count</button>}</article>)}</div>}<details className="inventory-workflows-history"><summary>Recent stock movements</summary>{data.movements.length?data.movements.map(m=><div key={m.id}><strong>{m.sku}: {m.quantityDelta>0?"+":""}{m.quantityDelta/1000} {m.unit}</strong><p>{m.reason} · {m.occurredDate}</p><small>{m.sourceReference}</small></div>):<p>No posted movements yet.</p>}</details></>}
        {tab==="receiving"&&<><div className="inventory-workflows-toolbar"><h3>Accepted, rejected and accounted for.</h3>{data.permissions.receive&&<button type="button" className="inventory-workflows-primary" onClick={()=>begin("receive")}>Receive an order</button>}</div>{!data.receipts.length?<div className="inventory-workflows-empty"><h3>No managed receipts yet.</h3><p>Create and send a purchase order in Purchasing with this delivery location, then receive accepted stock here. This view does not include earlier receipt-only records.</p></div>:<div className="inventory-workflows-grid">{data.receipts.map(r=><article key={r.id}><span>{r.occurredDate}</span><h4>{r.source}</h4><strong>{r.reversedAt?"Reversed":"Received"}</strong>{r.lines.map(l=><p key={l.lineId}>{l.sku}: {l.accepted} accepted · {l.rejected} rejected</p>)}{r.reversalReason&&<p>{r.reversalReason}</p>}{!r.reversedAt&&data.permissions.receive&&<button type="button" onClick={()=>begin("reverse_receipt",undefined,r)}>Review reversal</button>}</article>)}</div>}</>}
        {data.permissions.kinds.includes(tab as InventoryRecordKind)&&<><div className="inventory-workflows-toolbar"><h3>{kindTitles[tab as InventoryRecordKind]}</h3>{data.permissions.editableKinds.includes(tab as InventoryRecordKind)&&<button type="button" className="inventory-workflows-primary" onClick={()=>begin("save_record",tab as InventoryRecordKind)}>Add reviewed record</button>}</div>{!data.records.some(r=>r.kind===tab)?<div className="inventory-workflows-empty"><h3>Bring the evidence into your next decision.</h3><p>Add a source-backed record. Missing constraints stay visible; nothing sends, orders, pays or posts to your accounts automatically.</p></div>:<div className="inventory-workflows-grid">{data.records.filter(r=>r.kind===tab).map(r=><article key={r.id}><span>Revision {r.version} · {timestamp(r.updatedAt)} UTC</span><h4>{String(r.payload.sku??r.payload.variant??r.payload.invoiceReference??"Lot action")}</h4><RecordSummary record={r}/><div className="inventory-workflows-actions">{data.permissions.editableKinds.includes(r.kind)&&<button type="button" onClick={()=>begin("save_record",r.kind,r)}>Review record</button>}<button type="button" onClick={()=>void showHistory(r)}>History</button></div>{history?.id===r.id&&<div className="inventory-workflows-history" role="region" aria-label="Record revisions"><button type="button" onClick={()=>setHistory(null)}>Close history</button>{history.entries.map(h=><details key={h.version}><summary>Revision {h.version} · {timestamp(h.createdAt)} UTC</summary><RecordSummary record={{...r,payload:JSON.parse(h.payloadJson)}}/><p>Source: {String(JSON.parse(h.payloadJson).source)}</p></details>)}<small>Latest 100 revisions; earlier history is retained.</small></div>}</article>)}</div>}</>}
      </>}
    </>}
  </section>;
}

export default InventoryWorkflows;
