"use client";

import { useState } from "react";

type Start = (mode: "signin" | "signup") => void;

const faqs = [
  ["What does Lexedge Consulting do?", "We help ambitious businesses sharpen their positioning, build dependable growth systems, improve conversion and create the operating rhythm required to scale with confidence."],
  ["Who do you work with?", "We partner with founders and leadership teams who already have something valuable in market and want a clearer, more repeatable path to the next stage of growth."],
  ["How does the first conversation work?", "VanTalk asks a few focused questions about your business, identifies the highest leverage opportunities and helps you book a conversation with the Lexedge team."],
  ["Is Lexedge an agency or a consultancy?", "Lexedge is a strategic growth consultancy. We combine senior thinking with practical implementation so recommendations become systems your team can actually use."],
  ["What kind of results should we expect?", "Every engagement is shaped around the business, so we avoid generic promises. The goal is a stronger offer, cleaner conversion path, better systems and measurable progress against agreed priorities."],
];

export default function LexedgeLanding({ start }: { start: Start }) {
  const [talkOpen, setTalkOpen] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });

  return <div className="lexedge-site">
    <div className="lexedge-announcement"><span>LEXEDGE CONSULTING</span><b>Growth systems for businesses ready for their next edge.</b><button onClick={() => setTalkOpen(true)}>Meet VanTalk <span>↗</span></button></div>
    <header className="lexedge-nav">
      <a className="lexedge-logo" href="#top" aria-label="Lexedge Consulting home"><img src="/brand/lexedge-logo.png" alt="Lexedge Consulting"/></a>
      <nav aria-label="Main navigation"><a href="#approach">Approach</a><a href="#capabilities">Capabilities</a><a href="#insights">Insights</a><a href="#faq">FAQ</a></nav>
      <div className="lexedge-nav-actions"><button className="lexedge-quiet" onClick={() => setTalkOpen(true)}>Talk to VanTalk</button><button className="lexedge-button small" onClick={() => scrollTo("contact")}>Book a strategy call <span>↗</span></button></div>
    </header>

    <main id="top">
      <section className="lexedge-hero">
        <div className="lexedge-hero-copy"><p className="lexedge-kicker"><i/> STRATEGY · SYSTEMS · SCALE</p><h1>Make your next<br/><em>move matter.</em></h1><p className="lexedge-lead">Lexedge helps ambitious businesses turn good ideas into durable growth. Sharper positioning, stronger conversion and proven operating systems, built for the stage you are entering.</p><div className="lexedge-hero-actions"><button className="lexedge-button" onClick={() => setTalkOpen(true)}>Start with VanTalk <span>↗</span></button><button className="lexedge-text-button" onClick={() => scrollTo("approach")}>See how we think <span>↓</span></button></div><div className="lexedge-signal"><span><b>01</b> Clearer positioning</span><span><b>02</b> Better conversion</span><span><b>03</b> Repeatable growth</span></div></div>
        <div className="lexedge-hero-art" aria-label="Lexedge growth system visual"><div className="lexedge-orbit orbit-one"/><div className="lexedge-orbit orbit-two"/><div className="lexedge-orbit orbit-three"/><div className="lexedge-core"><span>LEX</span><b>EDGE</b><small>THE GROWTH SYSTEM</small></div><span className="lexedge-art-note note-one">SIGNAL<br/><b>01</b></span><span className="lexedge-art-note note-two">MOMENTUM<br/><b>03</b></span><span className="lexedge-art-note note-three">LEVERAGE<br/><b>02</b></span></div>
      </section>

      <section className="lexedge-marquee" aria-label="Lexedge principles"><div>BUILD WITH INTENT <i>✳</i> MARKET WITH CLARITY <i>✳</i> SCALE WITH CONTROL <i>✳</i> BUILD WITH INTENT <i>✳</i></div></section>

      <section className="lexedge-intro" id="approach"><div className="lexedge-section-label">THE LEXEDGE POINT OF VIEW</div><div><h2>Growth is not a moment.<br/><em>It is a system.</em></h2><p>Most businesses do not need more noise. They need the right message, the right motion and a system that turns attention into momentum. Lexedge brings the strategic clarity and practical structure to make that happen.</p><button className="lexedge-link" onClick={() => scrollTo("capabilities")}>Explore the approach <span>↗</span></button></div></section>

      <section className="lexedge-capabilities" id="capabilities"><div className="lexedge-section-top"><div className="lexedge-section-label">WHAT WE DO</div><h2>The edge is in the<br/><em>details that compound.</em></h2></div><div className="lexedge-capability-grid"><article><span>01</span><h3>Positioning<br/>that lands.</h3><p>Define the sharpest expression of your value, so the right people understand why you are different and why now.</p><a href="#contact">Discover more ↗</a></article><article><span>02</span><h3>Conversion<br/>that moves.</h3><p>Turn attention into action with a customer journey that feels obvious, credible and built to remove friction.</p><a href="#contact">Discover more ↗</a></article><article><span>03</span><h3>Systems<br/>that scale.</h3><p>Install the operating models, playbooks and feedback loops that make growth repeatable beyond the founder.</p><a href="#contact">Discover more ↗</a></article></div></section>

      <section className="lexedge-proof"><div className="lexedge-proof-card"><div className="lexedge-section-label">THE LEXEDGE METHOD</div><h2>From scattered effort<br/>to <em>strategic motion.</em></h2><p>We work across the full growth picture, because the strongest results happen when the parts reinforce each other.</p><div className="lexedge-method"><div><b>01</b><span>Diagnose</span><small>Find the constraint.</small></div><div><b>02</b><span>Design</span><small>Build the advantage.</small></div><div><b>03</b><span>Deploy</span><small>Make it operational.</small></div><div><b>04</b><span>Compound</span><small>Keep the edge.</small></div></div></div><div className="lexedge-quote"><div className="lexedge-quote-mark">“</div><p>We believe the best growth strategy is one your team can explain, execute and improve.</p><span>LEXEDGE PRINCIPLE 01</span></div></section>

      <section className="lexedge-insights" id="insights"><div className="lexedge-section-top"><div className="lexedge-section-label">INSIGHTS FOR THE NEXT STAGE</div><h2>Questions worth<br/><em>asking early.</em></h2></div><div className="lexedge-article-grid"><article><div className="article-number">01</div><span>GROWTH SYSTEMS</span><h3>Why growth stalls after the first wave of traction</h3><p>The signals that tell you it is time to replace founder instinct with an operating model.</p><a href="#contact">Read the perspective ↗</a></article><article><div className="article-number">02</div><span>CONVERSION</span><h3>What a premium customer journey actually feels like</h3><p>Trust is built in the details between the first impression and the final decision.</p><a href="#contact">Read the perspective ↗</a></article><article><div className="article-number">03</div><span>POSITIONING</span><h3>How to become the obvious choice in a crowded market</h3><p>Clarity is not a branding exercise. It is a commercial advantage.</p><a href="#contact">Read the perspective ↗</a></article></div></section>

      <section className="lexedge-faq" id="faq"><div className="lexedge-section-label">COMMON QUESTIONS</div><div><h2>A considered start<br/><em>starts here.</em></h2><p className="lexedge-faq-intro">A few of the questions we hear most often from teams preparing for meaningful growth.</p>{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>

      <section className="lexedge-contact" id="contact"><div className="lexedge-contact-copy"><div className="lexedge-section-label">MAKE THE NEXT MOVE</div><h2>Ready to find<br/>your <em>edge?</em></h2><p>Tell us where you are headed. We will help you see what it will take to get there with more clarity, more control and more momentum.</p><button className="lexedge-button" onClick={() => setTalkOpen(true)}>Start with VanTalk <span>↗</span></button></div><div className="lexedge-contact-panel"><span>DIRECT LINE</span><a href="mailto:hussienissa@lexedgeconsulting.com">hussienissa@lexedgeconsulting.com</a><span className="panel-rule"/><span>YOUR NEXT STEP</span><button onClick={() => setTalkOpen(true)}>Book a strategy conversation <b>↗</b></button><small>VanTalk will guide the first few questions and help you find the right starting point.</small></div></section>
    </main>

    <footer className="lexedge-footer"><div><a className="lexedge-footer-logo" href="#top"><img src="/brand/lexedge-logo.png" alt="Lexedge Consulting"/></a><p>Premium growth strategy for businesses ready to scale with intent.</p></div><div className="lexedge-footer-links"><span>EXPLORE</span><a href="#approach">Approach</a><a href="#capabilities">Capabilities</a><a href="#insights">Insights</a><a href="#faq">FAQ</a></div><div className="lexedge-footer-links"><span>CONNECT</span><button onClick={() => setTalkOpen(true)}>Talk to VanTalk</button><a href="mailto:hussienissa@lexedgeconsulting.com">Email Lexedge</a><a href="#contact">Book a call</a></div><div className="lexedge-footer-links"><span>LEGAL</span><a href="/privacy">Privacy policy</a><a href="/terms">Terms of use</a><a href="/cookies">Cookie policy</a></div><div className="lexedge-footer-bottom"><span>© {new Date().getFullYear()} Lexedge Consulting. All rights reserved.</span><span>Built for the next edge.</span></div></footer>

    {talkOpen && <div className="vantalk-backdrop" role="presentation" onClick={() => setTalkOpen(false)}><section className="vantalk-modal" role="dialog" aria-modal="true" aria-labelledby="vantalk-title" onClick={event => event.stopPropagation()}><button className="vantalk-close" aria-label="Close VanTalk" onClick={() => setTalkOpen(false)}>×</button>{submitted ? <div className="vantalk-success"><span>✳</span><h2>Your next move is in motion.</h2><p>Thanks for reaching out. We will follow up at <b>hussienissa@lexedgeconsulting.com</b>.</p><button className="lexedge-button" onClick={() => setTalkOpen(false)}>Close VanTalk</button></div> : <><div className="vantalk-avatar">VT</div><span className="lexedge-section-label">VANTALK · LEXEDGE CONCIERGE</span><h2 id="vantalk-title">Let us find your<br/><em>highest-leverage move.</em></h2><p>In one sentence, what are you trying to make happen in the next 6 to 12 months?</p><textarea aria-label="Your growth goal" placeholder="We want to…"/><button className="lexedge-button full" onClick={() => setSubmitted(true)}>Continue the conversation <span>↗</span></button><small>Your note stays with Lexedge and is used only to shape the first conversation.</small></>}</section></div>}
  </div>;
}
