"use client";

import { useId, useMemo, useState } from "react";
import type { RetailAccess, RetailReport } from "../domain/retail-intelligence";
import VanteloqAiLogo from "./vanteloq-ai-logo";

export type { RetailAccess, RetailReport } from "../domain/retail-intelligence";
export const retailSections = ["Why it changed", "Products", "Baskets", "Inventory", "Customers", "Operations"] as const;
const number = (value: number | null, digits = 1) => value == null ? "Unavailable" : value.toLocaleString("en-CA", { maximumFractionDigits: digits });
const rate = (value: number | null) => value == null ? "Unavailable" : (value * 100).toFixed(1) + "%";
const Card = ({ label, value, note }: { label: string; value: string; note: string }) => <article className="retail-kpi"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;

function HourChart({ hours, money }: { hours: RetailReport["hours"]; money: (value: number | null, digits?: number) => string }) {
  const [selected, setSelected] = useState<number | null>(null);
  const [allHours, setAllHours] = useState(false);
  const shown = allHours ? hours : hours.filter(row => row.netCents != null);
  const maximum = Math.max(1, ...hours.map(row => Math.abs(row.netCents ?? 0)));
  const hour = selected == null ? null : hours.find(row => row.hour === selected);
  return <div className="retail-hour-explorer">
    <div className="retail-hour-options"><p className="retail-note">Select an hour for exact values. Blue bars show positive revenue above zero; red bars show negative revenue below zero. A dash means no records.</p><button type="button" aria-pressed={allHours} onClick={() => setAllHours(value => !value)}>{allHours ? "Show recorded hours" : "Show all 24 hours"}</button></div>
    {!shown.length && <p className="retail-empty">No hourly records in this selection.</p>}
    {shown.length > 0 && <div className="retail-hour-scroll" role="region" aria-label="Interactive hourly revenue" tabIndex={0}><div className="retail-hour-chart" style={{ gridTemplateColumns: `repeat(${shown.length}, minmax(44px, 1fr))`, minWidth: shown.length * 44 }}>{shown.map(row => <button type="button" key={row.hour} aria-pressed={selected === row.hour} aria-label={row.hour + ":00, " + (row.netCents == null ? "no records" : money(row.netCents, 2) + " net revenue") + ", " + row.purchaseBaskets + " purchase baskets"} onClick={() => setSelected(row.hour)}>
      <span className="retail-hour-positive">{row.netCents != null && row.netCents > 0 && <i style={{ height: (row.netCents / maximum * 100) + "%" }}/>}</span>
      <span className="retail-hour-negative">{row.netCents != null && row.netCents < 0 && <i style={{ height: (Math.abs(row.netCents) / maximum * 100) + "%" }}/>}</span>
      <span className="retail-hour-missing">{row.netCents == null ? "–" : row.netCents === 0 ? "0" : ""}</span><small>{String(row.hour).padStart(2, "0")}</small>
    </button>)}</div></div>}
    <div className="retail-hour-detail" aria-live="polite">{hour ? <><strong>{String(hour.hour).padStart(2, "0")}:00 to {String(hour.hour).padStart(2, "0")}:59</strong><span>{hour.netCents == null ? "No records" : money(hour.netCents, 2) + " net revenue"}</span><span>{hour.purchaseBaskets} purchase baskets across the selected period</span></> : "Choose a bar to see its exact values."}</div>
  </div>;
}

export default function RetailIntelligencePanel({ report: data, currency, access, onAsk, onTask, onInputs, onExpiry, demo = false, initialSection = "Why it changed" }: {
  report: RetailReport; currency: string; access: RetailAccess; demo?: boolean;
  initialSection?: typeof retailSections[number];
  onAsk?: (question: string) => void; onTask?: (title: string, detail: string) => void; onInputs?: () => void; onExpiry?: () => void;
}) {
  const id = useId(), [section, setSection] = useState<typeof retailSections[number]>(initialSection);
  const [query, setQuery] = useState(""), [category, setCategory] = useState("all"), [itemType, setItemType] = useState("all"), [page, setPage] = useState(0);
  const [pairKind, setPairKind] = useState<"products" | "categories">("products");
  const money = (value: number | null, digits = 0) => value == null ? "Unavailable" : new Intl.NumberFormat("en-CA", { style: "currency", currency, maximumFractionDigits: digits, minimumFractionDigits: digits }).format(value / 100);
  const products = useMemo(() => data.products.filter(p => (category === "all" || p.category === category) && (itemType === "all" || p.itemType === itemType) && (!query.trim() || (p.name + " " + p.sku).toLowerCase().includes(query.trim().toLowerCase()))), [data.products, category, itemType, query]);
  const available = retailSections.filter(s => s !== "Inventory" || access.inventory).filter(s => s !== "Customers" || access.customers).filter(s => s !== "Operations" || access.labour || data.hours.some(h => h.netCents != null));
  const chosen = available.includes(section) ? section : available[0];
  const choose = (value: typeof section) => { setSection(value); setPage(0); };
  const maxImpact = Math.max(1, ...data.bridge?.map(row => Math.abs(row.impactCents)) ?? []);
  const sortedHours = data.hours.filter(h => h.netCents != null).sort((a, b) => b.netCents! - a.netCents!);
  const pairs = data.baskets[pairKind];
  const opportunity = data.products.find(p => p.discountRate != null && p.discountRate > .15 && p.basketCount >= 10);
  return <section className="retail-intelligence" aria-labelledby={id + "-title"}>
    <header className="retail-heading"><div><span className="retail-eyebrow">RETAIL INTELLIGENCE {demo ? "· SAMPLE" : ""}</span><h2 id={id + "-title"}>From the sale to the decision.</h2><p>Products, baskets and the drivers behind performance.</p></div><span className="retail-period">{data.period.from} to {data.period.to}<small>{data.timeZone} · {number(data.current.lineCount, 0)} line records</small></span></header>
    <div className="retail-kpis">
      <Card label="Recorded net sales" value={data.current.lineCount ? money(data.current.netCents) : "No sale records"} note={data.comparison.growthRate == null ? "Comparison needs matched records" : (data.comparison.growthRate > 0 ? "+" : "") + rate(data.comparison.growthRate) + " vs prior period"}/>
      <Card label="Items per basket" value={number(data.current.itemsPerBasket, 2)} note={number(data.current.purchaseBaskets, 0) + " purchase baskets"}/>
      <Card label="Discount dependency" value={rate(data.current.discountedBasketRate)} note="Share of purchase baskets with a discount"/>
      <Card label="Recorded gross profit" value={money(data.current.grossProfitCents)} note={!access.profit ? "Profit access is required" : data.current.costCoverage === 1 ? "After recorded product costs; before overhead" : "Complete line-level costs are required"}/>
    </div>
    {data.dataQualityWarnings.length > 0 && <div className="retail-quality-notice" role="status"><strong>Evidence needs attention</strong>{data.dataQualityWarnings.map(warning => <p key={warning}>{warning}</p>)}</div>}
    <nav className="retail-tabs" aria-label="Retail intelligence views">{available.map(value => <button key={value} type="button" aria-pressed={chosen === value} onClick={() => choose(value)}>{value === "Why it changed" ? "Why?" : value}</button>)}</nav>
    <div className="retail-view" aria-live="polite">
      {chosen === "Why it changed" && <>
        <div className="retail-view-heading"><div><h3>{data.comparison.deltaCents == null ? "Build a comparable picture." : data.comparison.deltaCents < 0 ? "What accounts for the decline?" : "What accounts for the change?"}</h3><p>Arithmetic drivers reconcile to the recorded revenue change. They do not establish a cause.</p></div><b>{data.comparison.deltaCents == null ? "Baseline needed" : money(data.comparison.deltaCents, 2)}</b></div>
        <div className="retail-split"><div className="retail-drivers">{data.bridge ? data.bridge.map(row => <article key={row.label}><header><strong>{row.label}</strong><b className={row.impactCents < 0 ? "retail-down" : "retail-up"}>{row.impactCents > 0 ? "+" : ""}{money(row.impactCents, 2)}</b></header><div className="retail-bar-track"><i className={row.impactCents < 0 ? "retail-negative-bar" : ""} style={{ width: Math.abs(row.impactCents) / maxImpact * 100 + "%" }}/></div><p>{row.detail}</p></article>) : <div className="retail-empty"><h4>A responsible answer needs a baseline.</h4><p>Both periods need purchase records from the same source accounts. An empty feed may mean a closed store or an incomplete sync.</p></div>}</div><aside className="retail-evidence"><span className="retail-eyebrow">CHECK THE EVIDENCE</span><h4>What to investigate next</h4><ul><li>Confirm that the same outlets and dates have finished syncing.</li><li>Compare category mix, units per basket and discount share.</li><li>Check stockouts, opening hours and campaigns before attributing a cause.</li></ul><dl><div><dt>Current days with records</dt><dd>{data.comparison.currentObservedDays} / {data.period.days}</dd></div><div><dt>Prior days with records</dt><dd>{data.comparison.priorObservedDays} / {data.period.days}</dd></div><div><dt>Purchase basket value</dt><dd>{money(data.current.averageBasketCents, 2)}</dd></div></dl></aside></div>
        {data.categories.length > 0 && <>
          <div className="retail-table-wrap retail-category-table" role="region" tabIndex={0} aria-label="Category revenue drivers">
            <table aria-describedby={id + "-net-units-note"}>
              <caption>Category revenue and contribution to the change</caption>
              <thead><tr><th scope="col">Category</th><th scope="col">Net Revenue</th><th scope="col">Net Units</th><th scope="col">Change</th><th scope="col">Growth</th></tr></thead>
              <tbody>{data.categories.map(row => <tr key={row.name}><th scope="row">{row.name}</th><td>{money(row.netCents, 2)}</td><td>{number(row.units)}</td><td>{data.comparison.comparable ? money(row.impactCents, 2) : "Unavailable"}</td><td>{rate(row.growthRate)}</td></tr>)}</tbody>
            </table>
          </div>
          <p id={id + "-net-units-note"} className="retail-table-help">Net Units = units sold minus units returned in the selected period.</p>
        </>}
        <p className="retail-note">{data.comparison.note}</p>
      </>}
      {chosen === "Products" && <>
        <div className="retail-view-heading"><div><h3>Know what earns its shelf space.</h3><p>Ranked by recorded net revenue. Returns remain in net units and revenue.</p></div><span>{number(products.length, 0)} {products.length === 1 ? "product" : "products"}</span></div>
        <div className="retail-filters"><label>Search product or SKU<input value={query} placeholder="Search products" onChange={e => { setQuery(e.target.value); setPage(0); }}/></label><label>Category<select value={category} onChange={e => { setCategory(e.target.value); setPage(0); }}><option value="all">All categories</option>{[...new Set(data.products.map(p => p.category))].map(c => <option key={c}>{c}</option>)}</select></label><label>Item type<select value={itemType} onChange={e => { setItemType(e.target.value); setPage(0); }}><option value="all">All item types</option>{[...new Set(data.products.map(p => p.itemType))].map(c => <option key={c}>{c}</option>)}</select></label></div>
        <div className="retail-table-wrap" role="region" tabIndex={0} aria-label="Product performance table"><table><caption>Product performance in the selected period</caption><thead><tr><th>Product / SKU</th><th>Category / type</th><th>Net units</th><th>Net revenue</th><th>Gross margin</th><th>Discount rate</th><th>Repeat rate</th><th>Sales score</th></tr></thead><tbody>{products.slice(page * 12, page * 12 + 12).map(row => <tr key={row.key}><th>{row.name}<small>{row.sku || "No SKU"} · {row.provider}</small></th><td>{row.category}<small>{row.itemType}</small></td><td>{number(row.unitsMilli / 1000)}</td><td>{money(row.netCents, 2)}</td><td>{rate(row.marginRate)}</td><td>{rate(row.discountRate)}</td><td>{rate(row.repeatPurchaseRate)}<small>{access.customers ? row.identifiedBuyers + " identified buyers" : "Customer analytics access required"}</small></td><td><span className="retail-score">{row.score == null ? "Needs data" : row.score + " / 100"}</span></td></tr>)}</tbody></table>{!products.length && <p className="retail-empty">No matching product records in this selection.</p>}</div>
        {products.length > 12 && <div className="retail-pagination"><button disabled={page === 0} onClick={() => setPage(p => p - 1)}>Previous</button><span>Page {page + 1} of {Math.ceil(products.length / 12)}</span><button disabled={(page + 1) * 12 >= products.length} onClick={() => setPage(p => p + 1)}>Next</button></div>}
        {opportunity && <div className="retail-opportunity"><div><strong>Review discount reliance: {opportunity.name}</strong><p>{rate(opportunity.discountRate)} of its pre-discount purchase revenue was discounted across {opportunity.basketCount} baskets. Test full-price demand before changing the promotion.</p></div>{onTask && <button onClick={() => onTask("Review discount reliance: " + opportunity.name, rate(opportunity.discountRate) + " discount rate in " + data.period.from + " to " + data.period.to + ". Review margin and full-price demand; do not assume removing discounts preserves volume.")}>Create review task</button>}</div>}
        <details className="retail-method"><summary>How the score and product metrics work</summary><p>{data.methodology.score}</p><p>Discount rate = purchase discounts / purchase revenue before discounts. Gross margin requires costs on every line. Repeat rates use identified buyers only.</p></details>
      </>}
      {chosen === "Baskets" && <>
        <div className="retail-view-heading"><div><h3>Find the connections inside a basket.</h3><p>Discover observed combinations and evaluate an offer before testing it.</p></div><div className="retail-segment"><button aria-pressed={pairKind === "products"} onClick={() => setPairKind("products")}>Products</button><button aria-pressed={pairKind === "categories"} onClick={() => setPairKind("categories")}>Categories</button></div></div>
        <div className="retail-mini-kpis"><Card label="Average purchase basket" value={money(data.current.averageBasketCents, 2)} note="Positive-quantity purchase lines"/><Card label="Items per basket" value={number(data.current.itemsPerBasket, 2)} note="Purchased units / purchase baskets"/><Card label="Purchase discount rate" value={rate(data.current.discountRate)} note="Discounts / pre-discount purchase revenue"/></div>
        {pairs.pairs.length ? <div className="retail-pairs">{pairs.pairs.slice(0, 12).map(pair => <article key={pair.source + pair.a + pair.b}><header><span>{pair.aName}</span><i aria-hidden="true">+</i><span>{pair.bName}</span></header><dl><div><dt>Purchased together</dt><dd>{pair.count} baskets</dd></div><div><dt>Support</dt><dd>{rate(pair.support)}</dd></div><div><dt>A → B confidence</dt><dd>{rate(pair.confidence)}</dd></div><div><dt>Lift</dt><dd>{number(pair.lift, 2)}×</dd></div></dl><p>Among {pair.baskets} baskets in the same source account. {pair.aCount} contained the first item; {pair.bCount} contained the second.</p>{onTask && <button onClick={() => onTask("Review a cross-sell test", pair.aName + " and " + pair.bName + " appeared together in " + pair.count + " of " + pair.baskets + " source baskets, " + data.period.from + " to " + data.period.to + ". Association is not proof of incremental demand. Review margins, then run a controlled test.")}>Review an opportunity</button>}</article>)}</div> : <div className="retail-empty"><h4>{pairs.status === "available" ? "More basket evidence is needed." : "This selection is too large for pair analysis."}</h4><p>{pairs.status === "available" ? "A pair appears after at least three distinct baskets. Anonymous purchases still contribute. Category pairs also need classified products." : "Use a narrower date range. Other metrics still use the complete selection."}</p></div>}
        <details className="retail-method"><summary>Support, confidence and lift explained</summary><p>Support is paired baskets divided by source baskets. Confidence is paired baskets divided by baskets containing the first item. Lift compares that confidence with how often the second item appears overall. A lift above 1 means they co-occur more often than independence would imply.</p><p>{data.methodology.baskets}</p></details>
      </>}
      {chosen === "Inventory" && <>
        <div className="retail-view-heading"><div><h3>Balance availability, cash and shelf life.</h3><p>Velocity uses the selected period and the exact source outlet. Current stock is shown with its timestamp.</p></div>{onInputs && <button onClick={onInputs}>Add inventory evidence</button>}</div>
        <div className="retail-table-wrap" role="region" tabIndex={0} aria-label="Inventory intelligence table"><table><caption>Inventory calculations and review signals</caption><thead><tr><th>Item / location</th><th>On hand</th><th>Units/day</th><th>Forward cover</th><th>Turnover</th><th>Days on hand</th><th>Sell-through</th><th>Order review</th></tr></thead><tbody>{data.inventory.slice(0, 200).map(row => <tr key={row.key}><th>{row.name}<small>{row.sku} · {row.outletRef}</small><small>{new Date(row.updatedAt).toLocaleString("en-CA", { timeZone: data.timeZone })}</small></th><td>{number(row.onHand)}{row.overstock && <small className="retail-down">Overstock review</small>}</td><td>{number(row.dailyVelocity, 2)}</td><td>{number(row.daysOfCover)}{row.daysOfCover != null ? " days" : ""}</td><td>{number(row.turnover, 2)}</td><td>{number(row.daysOnHand)}</td><td>{rate(row.sellThrough)}{row.stockInputIssue && <small>{row.stockInputIssue}</small>}</td><td>{row.reorderUnits == null ? "Needs current evidence" : number(row.reorderUnits, 0) + " units"}<small>{row.measurementSource || "Opening stock evidence needed"}</small></td></tr>)}</tbody></table>{!data.inventory.length && <p className="retail-empty">Connect and approve an inventory source for this location.</p>}</div>
        {data.inventory.length > 200 && <p className="retail-note">Showing the first 200 inventory items. Narrow the location to review a smaller stock list.</p>}
        {access.expiry && <div className="retail-expiry"><header><div><h4>Expiry watch</h4><p>Recorded lots expiring within 30 days, including overdue stock. Review quantities before taking action.</p></div>{onExpiry && <button onClick={onExpiry}>Manage lots & expiry</button>}</header>{data.expiry.length ? data.expiry.slice(0, 30).map((lot, index) => <article key={index}><span><strong>{lot.name}</strong><small>{lot.sku} · {lot.locationRef}</small></span><b>{number(lot.quantity)} units</b><span className={lot.daysToExpiry <= 7 ? "retail-down" : ""}>{lot.daysToExpiry < 0 ? Math.abs(lot.daysToExpiry) + " days overdue" : lot.daysToExpiry + " days left"}</span><span>{money(lot.valueAtRiskCents, 2)} recorded cost</span></article>) : <p>No dated lots fall in this window. Undated or unrecorded stock cannot be assessed.</p>}</div>}
        <details className="retail-method"><summary>Inventory formulas and planning assumptions</summary><p>{data.methodology.inventory}</p><p>{data.methodology.planning}</p></details>
      </>}
      {chosen === "Customers" && data.customers && <>
        <div className="retail-view-heading"><div><h3>Understand repeat activity, with context.</h3><p>Customer references are scoped to their source account. Guests are not treated as one customer.</p></div>{onInputs && <button onClick={onInputs}>Add loyalty evidence</button>}</div>
        <div className="retail-mini-kpis"><Card label="Observed repeat rate" value={rate(data.customers.repeatPurchaseRate)} note={data.customers.repeatBuyers + " returning buyers in this period"}/><Card label="Identified buyers" value={number(data.customers.identifiedBuyers, 0)} note="Distinct provider customer references"/><Card label="Identity coverage" value={rate(data.customers.identityCoverage)} note="Purchase baskets with one known customer"/></div>
        <div className="retail-table-wrap"><table><caption>Loyalty activity by verified enrollment date</caption><thead><tr><th>Group</th><th>Baskets</th><th>Purchase revenue</th><th>Average basket</th></tr></thead><tbody>{([["After enrollment", data.customers.loyalty.member], ["Before enrollment", data.customers.loyalty.beforeEnrollment], ["Membership unknown", data.customers.loyalty.unknown]] as const).map(([label, row]) => <tr key={label}><th>{label}</th><td>{row.baskets}</td><td>{money(row.netCents, 2)}</td><td>{money(row.averageBasketCents, 2)}</td></tr>)}</tbody></table></div>
        <p className="retail-note">Different basket values do not prove the loyalty program caused a lift. Enrollment timing, selection and other changes can explain the difference. Rewards balances and redemptions require a loyalty-provider connection.</p>
        <details className="retail-method"><summary>How repeat activity is measured</summary><p>{data.methodology.repeat}</p></details>
      </>}
      {chosen === "Operations" && <>
        <div className="retail-view-heading"><div><h3>See when demand needs coverage.</h3><p>Hourly revenue in {data.timeZone}. Unknown hours remain visibly distinct.</p></div>{onInputs && access.labour && <button onClick={onInputs}>Add labour evidence</button>}</div>
        <HourChart hours={data.hours} money={money}/>
        <div className="retail-mini-kpis"><Card label="Strongest recorded hour" value={sortedHours[0] ? sortedHours[0].hour + ":00" : "Unavailable"} note={money(sortedHours[0]?.netCents ?? null) + " across the period"}/><Card label="Slowest recorded hour" value={sortedHours.at(-1) ? sortedHours.at(-1)!.hour + ":00" : "Unavailable"} note="Among hours with records only"/><Card label="Sales per paid labour hour" value={money(data.operations?.salesPerLabourHourCents ?? null, 2)} note={data.operations?.labourComplete ? "Complete reviewed outlet hours" : "Complete paid hours are required"}/></div>
        {access.labour && data.operations && <div className="retail-mini-kpis"><Card label="Paid hours" value={number(data.operations.paidHours, 2)} note="Reviewed manual or imported evidence"/><Card label="Average paid rate" value={money(data.operations.averagePaidRateCents, 2)} note="Recorded wages / paid hours"/><Card label="Staff-attributed basket value" value={money(data.operations.attributedAverageBasketCents, 2)} note="Attributed sales / attributed transactions"/></div>}
        <div className="retail-anomalies"><h4>Unusual recorded days</h4>{data.anomalies.length ? data.anomalies.slice(-12).reverse().map(day => <article key={day.date}><b>{day.date}</b><span>{money(day.netCents, 2)}</span><p>{money(day.differenceCents, 2)} from the same-weekday median, using {day.observations} earlier observations. Check coverage and operational context.</p></article>) : <p>No supported flags in this selection. At least four earlier observations of the same weekday and a non-zero baseline spread are required.</p>}</div>
        <details className="retail-method"><summary>Hourly, labour and anomaly calculations</summary><p>{data.methodology.hours}</p><p>{data.methodology.anomalies}</p></details>
      </>}
    </div>
    <footer className="retail-footer"><div><VanteloqAiLogo size={27} decorative/><span><strong>{demo ? "The same calculation engine as your workspace." : "Take the evidence into Vanteloq AI."}</strong><small>{demo ? "Fictional records. No live AI request." : "Ask for an interpretation. Review every proposed action."}</small></span></div>{onAsk && <button onClick={() => onAsk("Explain the " + chosen.toLowerCase() + " evidence for " + data.period.from + " to " + data.period.to + ". Identify the largest measured drivers, missing data and three practical review actions. Separate observations from possible causes.")}>Ask Vanteloq AI →</button>}{onInputs && access.edit && <button className="retail-quiet" onClick={onInputs}>Evidence settings</button>}</footer>
  </section>;
}
