"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { apiFetch } from "./supabase-browser";
import { SECTOR_DEFINITIONS, sectorDecimal, sectorReport, sectorScaled, validateSectorContent, type SectorAction, type SectorBatch, type SectorContent, type SectorField, type SectorKind, type SectorRecord, type SectorReport, type SectorStockLine } from "../domain/sector-operations";
import "./sector-operations.css";
import FoodOperationsOverview from "./food-operations-overview";
type Link={id:string;label:string;type:string;version:number|null};
type Saved=SectorRecord&{report:SectorReport;links:Link[]};
type Data={locationId:string|null;locations:{id:string;name:string;currency:string;timezone:string}[];kinds:SectorKind[];writable:SectorKind[];records:Saved[];references:Record<string,{id:string;label:string}[]>;referenceLimit:number;nextCursor:string|null};
type Draft={kind:SectorKind;title:string;source:string;sourceDate:string;dueDate:string;notes:string;values:Record<string,string>;batch:SectorBatch|null};
type History={version:number;action:string;reason:string;state:string;createdAt:number;content:SectorContent;links:Link[]};
const empty=(kind:SectorKind):Draft=>({kind,title:"",source:"",sourceDate:"",dueDate:"",notes:"",values:{},batch:null});
const digits=(currency:string)=>new Intl.NumberFormat("en-CA",{style:"currency",currency}).resolvedOptions().maximumFractionDigits??2;
const pretty=(value:string)=>value.replaceAll("_"," ").replace(/^./,s=>s.toUpperCase());
async function response(r:Response){const b=await r.json();if(!r.ok)throw Error(b.error?.message||"The workflow could not be loaded.");return b;}
function Metrics({report,currency}:{report:SectorReport;currency:string}){return <><dl className="sector-metrics">{report.metrics.map(m=><div key={m.label}><dt>{m.label}</dt><dd>{m.value===null?"Awaiting input":m.unit==="money"?new Intl.NumberFormat("en-CA",{style:"currency",currency}).format(m.value/10**digits(currency)):m.unit==="quantity"?new Intl.NumberFormat("en-CA",{maximumFractionDigits:3}).format(m.value/1000):m.unit==="percent"?`${(m.value/100).toFixed(1)}%`:new Intl.NumberFormat("en-CA").format(m.value)}</dd>{m.detail&&<small>{m.detail}</small>}</div>)}</dl>{report.attention.length>0&&<ul className="sector-attention">{report.attention.map(line=><li key={line}>{line}</li>)}</ul>}<p className="sector-note">{report.boundary}</p></>;}
function StockLine({line,onChange,label}:{line:SectorStockLine;onChange:(value:SectorStockLine)=>void;label:string}){
  const [quantity,setQuantity]=useState(sectorDecimal(line.quantityMilli,3)),[error,setError]=useState("");
  return <div className="sector-stock-line"><label>{label} SKU<input value={line.sku} maxLength={100} onChange={e=>onChange({...line,sku:e.target.value})}/></label><label>{label} unit<select value={line.unit} onChange={e=>onChange({...line,unit:e.target.value as SectorStockLine["unit"]})}><option value="each">Each</option><option value="g">Grams</option><option value="ml">Millilitres</option></select></label><label>{label} quantity<input inputMode="decimal" value={quantity} aria-invalid={!!error} onChange={e=>{setQuantity(e.target.value);try{const n=sectorScaled(e.target.value,3);setError("");onChange({...line,quantityMilli:n??0});}catch(caught){setError(caught instanceof Error?caught.message:"Check the quantity.");onChange({...line,quantityMilli:0});}}}/>{error&&<small role="alert">{error}</small>}</label></div>;
}
export default function SectorOperations(props:{activeLocationId?:string|null}){return <SectorPanel key={props.activeLocationId??"choose"} {...props}/>;}
function SectorPanel({activeLocationId=null}:{activeLocationId?:string|null}){
  const [data,setData]=useState<Data|null>(null),[locationId,setLocationId]=useState(activeLocationId??""),[kind,setKind]=useState<SectorKind|"">("");
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [stockRevision,setStockRevision]=useState(0);
  const [draft,setDraft]=useState<Draft|null>(null),[editing,setEditing]=useState<Saved|null>(null),[preview,setPreview]=useState<SectorReport|null>(null);
  const [selected,setSelected]=useState<Saved|null>(null),[action,setAction]=useState<Exclude<SectorAction,"save">|null>(null),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false),[history,setHistory]=useState<History[]|null>(null),[historyTruncated,setHistoryTruncated]=useState(false);
  const read=useRef<AbortController|null>(null),write=useRef<AbortController|null>(null),historyRead=useRef<AbortController|null>(null),heading=useRef<HTMLHeadingElement>(null),detailHeading=useRef<HTMLHeadingElement>(null),attempt=useRef<{body:string;key:string}|null>(null);
  const location=data?.locations.find(l=>l.id===(activeLocationId||locationId||data.locationId));
  const load=useCallback(async(after?:string)=>{read.current?.abort();const controller=new AbortController();read.current=controller;const params=new URLSearchParams();if(activeLocationId||locationId)params.set("locationId",activeLocationId||locationId);if(kind)params.set("kind",kind);if(after)params.set("after",after);try{const next:Data=await response(await apiFetch(`/api/v1/sector-operations?${params}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])}));if(!controller.signal.aborted){setData(old=>after&&old?{...next,records:[...old.records,...next.records]}:next);setSelected(current=>current?next.records.find(row=>row.id===current.id)??current:null);}}catch(caught){if(!controller.signal.aborted)setError(caught instanceof Error?caught.message:"Workflows could not load.");}finally{if(!controller.signal.aborted)setLoading(false);}},[activeLocationId,locationId,kind]);
  useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)void load();});return()=>{active=false;read.current?.abort();write.current?.abort();historyRead.current?.abort();};},[load]);
  const draftFocusKey=draft?`${draft.kind}:${editing?.id??"new"}`:"",selectedId=selected?.id;
  useEffect(()=>{if(draftFocusKey)heading.current?.focus();},[draftFocusKey]);
  useEffect(()=>{historyRead.current?.abort();if(selectedId)detailHeading.current?.focus();},[selectedId]);
  function change(next:Draft){setDraft(next);setPreview(null);setMessage("");attempt.current=null;}
  function startEdit(row?:Saved){const target=row?.kind||kind||data?.writable[0];if(!target)return;setSelected(null);setEditing(row??null);setConfirmed(false);setError("");setMessage("");setPreview(null);attempt.current=null;
    const next=empty(target);if(row){Object.assign(next,{title:row.title,source:row.source,sourceDate:row.sourceDate,dueDate:row.dueDate,notes:row.notes,batch:row.batch});for(const f of SECTOR_DEFINITIONS[target].fields){const v=row.values[f.key];next.values[f.key]=v===null?"":typeof v==="number"&&(f.type==="money"||f.type==="quantity")?sectorDecimal(v,f.type==="money"?digits(row.currency):3):String(v);}}setDraft(next);
  }
  function content():SectorContent{if(!draft||!location)throw Error("Choose a location.");const values:Record<string,unknown>={};for(const f of SECTOR_DEFINITIONS[draft.kind].fields){const v=draft.values[f.key]??"";values[f.key]=v===""?null:f.type==="boolean"?v==="true":f.type==="money"?sectorScaled(v,digits(location.currency)):f.type==="quantity"?sectorScaled(v,3):f.type==="integer"?/^\d+$/.test(v)?Number(v):NaN:v;}return validateSectorContent({...draft,currency:location.currency,values});}
  async function mutate(payload:Record<string,unknown>){if(busy)return;const serialized=JSON.stringify(payload);if(attempt.current?.body!==serialized)attempt.current={body:serialized,key:crypto.randomUUID()};setBusy(true);setError("");setMessage("");const controller=new AbortController();write.current=controller;try{const result=await response(await apiFetch("/api/v1/sector-operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,requestKey:attempt.current.key}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(25000)])}));if(!controller.signal.aborted){attempt.current=null;setDraft(null);setEditing(null);setPreview(null);setSelected(result.record);setHistory(null);setAction(null);setConfirmed(false);setMessage(result.replayed?"The earlier action was already saved. No duplicate change was made.":"Saved. The workflow and its review history are up to date.");await load();}}catch(caught){if(!controller.signal.aborted)setError(caught instanceof Error?caught.message:"The save could not be confirmed. Retry the same action safely or reload.");}finally{if(!controller.signal.aborted)setBusy(false);}}
  function save(event:FormEvent){event.preventDefault();try{const record=content();setPreview(sectorReport(record));void mutate({action:editing?.state==="active"?"amend":"save",confirmed:editing?.state==="active"?confirmed:undefined,locationId:location!.id,id:editing?.id??null,expectedVersion:editing?.version??null,record});}catch(caught){setError(caught instanceof Error?caught.message:"Check the form.");}}
  async function viewHistory(){if(!selected)return;setError("");historyRead.current?.abort();const controller=new AbortController();historyRead.current=controller;try{const result=await response(await apiFetch(`/api/v1/sector-operations?history=${encodeURIComponent(selected.id)}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])}));if(!controller.signal.aborted){setHistory(result.revisions);setHistoryTruncated(result.truncated);}}catch(caught){if(!controller.signal.aborted)setError(caught instanceof Error?caught.message:"History could not load.");}}
  function control(f:SectorField){const value=draft!.values[f.key]??"",set=(next:string)=>change({...draft!,values:{...draft!.values,[f.key]:next}}),labelId=`sector-field-${f.key}`;
    const refs=data?.references[f.type];return <label key={f.key} htmlFor={labelId}>{f.label}{f.optional&&<span className="sector-optional">Optional</span>}{f.type==="boolean"?<select id={labelId} value={value} onChange={e=>set(e.target.value)}><option value="">Not yet reviewed</option><option value="true">Yes</option><option value="false">No</option></select>:f.type==="choice"||refs?<select id={labelId} value={value} onChange={e=>set(e.target.value)}><option value="">{refs?"Choose a saved source":"Choose an option"}</option>{refs?refs.map(r=><option key={r.id} value={r.id}>{r.label}</option>):f.options?.map(option=><option key={option} value={option}>{pretty(option)}</option>)}</select>:<input id={labelId} type={f.type==="date"?"date":"text"} inputMode={["money","quantity"].includes(f.type)?"decimal":f.type==="integer"?"numeric":"text"} maxLength={200} value={value} onChange={e=>set(e.target.value)}/>}<small>{f.help||(["money","quantity","integer"].includes(f.type)?`Leave blank if unknown.${f.type==="money"?` Amount in ${location?.currency}.`:""}`:refs?"Linked to a saved record in this location.":"")}</small></label>;
  }
  const records=data?.records??[],attentionCount=records.filter(r=>!["completed","cancelled"].includes(r.state)&&r.report.attention.length>0).length;
  return <section className="sector-operations" aria-label="Business workflows"><header><div><p className="sector-eyebrow">Operations, connected to the evidence</p><h2>Move the work forward.</h2><p>Keep the next action, linked records and reviewed figures together.</p></div>{data&&<span className="sector-count">{attentionCount} need attention in this view</span>}</header>
    {loading&&<p role="status">Loading your business workflows…</p>}{error&&<p role="alert" className="sector-error">{error}</p>}{message&&<p role="status" className="sector-success">{message}</p>}
    {!loading&&!data&&<button type="button" onClick={()=>void load()}>Try again</button>}
    {data&&<><div className="sector-controls">{!activeLocationId&&<label>Location<select disabled={busy||!!draft} value={locationId||data.locationId||""} onChange={e=>{setLocationId(e.target.value);setSelected(null);setData(null);setLoading(true);}}><option value="">Choose one location</option>{data.locations.map(l=><option key={l.id} value={l.id}>{l.name} ({l.currency})</option>)}</select></label>}<label>Workflow<select disabled={busy||!!draft} value={kind} onChange={e=>{setKind(e.target.value as SectorKind);setSelected(null);setData(null);setLoading(true);}}><option value="">All business workflows</option>{data.kinds.map(k=><option key={k} value={k}>{SECTOR_DEFINITIONS[k].title}</option>)}</select></label><button type="button" className="sector-primary" disabled={!location||!data.writable.length||busy||!!draft||!!kind&&!data.writable.includes(kind)} onClick={()=>startEdit()}>New {kind?SECTOR_DEFINITIONS[kind].title.toLowerCase():"record"}</button><button type="button" disabled={busy} onClick={()=>void load()}>Refresh</button></div>
    {!data.kinds.length&&<div className="sector-empty"><h3>Your business tools are organised by activity.</h3><p>No sector workflow is available for this business type and role. Review Business type & tools in Settings, or use the general operating workspaces.</p></div>}
    {!draft&&!selected&&location&&<FoodOperationsOverview key={location.id} records={records} kinds={kind?[kind]:data.kinds} partial={Boolean(data.nextCursor)} location={location} recipes={data.references.recipe??[]} onOpen={record=>{setSelected(records.find(row=>row.id===record.id)??null);setAction(null);setHistory(null);setError("");}}/>}
    {draft&&<form onSubmit={save}><fieldset disabled={busy}><div className="sector-form-heading"><h3 ref={heading} tabIndex={-1}>{editing?"Edit":"New"} {SECTOR_DEFINITIONS[draft.kind].title.toLowerCase()}</h3><p>{SECTOR_DEFINITIONS[draft.kind].description}</p></div><div className="sector-fields">
      {!editing&&<label>Record type<select value={draft.kind} onChange={e=>change(empty(e.target.value as SectorKind))}>{data.writable.map(k=><option key={k} value={k}>{SECTOR_DEFINITIONS[k].title}</option>)}</select></label>}
      <label>Title<input required maxLength={120} value={draft.title} onChange={e=>change({...draft,title:e.target.value})}/></label><label>Source reference<input required maxLength={240} value={draft.source} onChange={e=>change({...draft,source:e.target.value})}/><small>Use a source document, count sheet or report reference. Do not enter card details or identity documents.</small></label><label>Source as-of date<input required type="date" value={draft.sourceDate} onChange={e=>change({...draft,sourceDate:e.target.value})}/></label><label>Next action due date<span className="sector-optional">Optional</span><input type="date" value={draft.dueDate} onChange={e=>change({...draft,dueDate:e.target.value})}/></label>
      {SECTOR_DEFINITIONS[draft.kind].fields.map(control)}<label>Resolution or working notes<textarea maxLength={1000} rows={3} value={draft.notes} onChange={e=>change({...draft,notes:e.target.value})}/></label>
    </div>
    {draft.kind==="prep_batch"&&<div className="sector-batch"><h4>Managed-stock transformation</h4><p>Open ingredient and prepared-stock positions in Inventory first. Imported POS balances are not changed.</p>{draft.batch?<><StockLine key="output" label="Prepared output" line={draft.batch.output} onChange={output=>change({...draft,batch:{...draft.batch!,output}})}/>{draft.batch.inputs.map((line,index)=><div key={`${stockRevision}-${index}`}><StockLine label={`Ingredient ${index+1}`} line={line} onChange={value=>change({...draft,batch:{...draft.batch!,inputs:draft.batch!.inputs.map((row,n)=>n===index?value:row)}})}/><button type="button" disabled={draft.batch!.inputs.length===1} onClick={()=>{setStockRevision(v=>v+1);change({...draft,batch:{...draft.batch!,inputs:draft.batch!.inputs.filter((_,n)=>n!==index)}});}}>Remove ingredient {index+1}</button></div>)}<button type="button" disabled={draft.batch.inputs.length>=40} onClick={()=>change({...draft,batch:{...draft.batch!,inputs:[...draft.batch!.inputs,{sku:"",unit:"g",quantityMilli:0}]}})}>Add ingredient</button></>:<button type="button" onClick={()=>change({...draft,batch:{output:{sku:"",unit:"each",quantityMilli:0},inputs:[{sku:"",unit:"g",quantityMilli:0}]}})}>Add stock transformation</button>}</div>}
    <div className="sector-actions">{editing?.state==="active"&&<label className="sector-checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this folio and departure update against its source.</label>}<button type="button" onClick={()=>{setError("");try{setPreview(sectorReport(content()));}catch(caught){setError(caught instanceof Error?caught.message:"Review the input fields.");}}}>Calculate preview</button><button type="submit" className="sector-primary">{busy?"Saving…":editing?.state==="active"?"Save reviewed update":"Save draft"}</button><button type="button" onClick={()=>{setDraft(null);setPreview(null);setEditing(null);}}>Cancel edit</button></div>{preview&&<Metrics report={preview} currency={location!.currency}/>}<p className="sector-note">{editing?.state==="active"?"A reviewed update retains the active stay and its room. Original values remain in review history.":"Save a draft to keep your work. Review and approval are separate steps."}</p></fieldset></form>}
    {!draft&&selected&&<article className="sector-detail"><header><div><p className="sector-eyebrow">{SECTOR_DEFINITIONS[selected.kind].title} · {pretty(selected.state)}</p><h3 ref={detailHeading} tabIndex={-1}>{selected.title}</h3><p>{selected.source} · Source date {selected.sourceDate} · Revision {selected.version}</p></div><button type="button" disabled={busy} aria-label="Close workflow detail" onClick={()=>{setSelected(null);setAction(null);setHistory(null);}}>Close</button></header><Metrics report={selected.report} currency={selected.currency}/>
      {selected.links.length>0&&<ul className="sector-links">{selected.links.map(link=><li key={link.id}>{pretty(link.type)}: <strong>{link.label}</strong>{link.version!==null?` · linked revision ${link.version}`:""}</li>)}</ul>}
      <details><summary>Recorded fields</summary><dl className="sector-evidence">{SECTOR_DEFINITIONS[selected.kind].fields.map(f=><div key={f.key}><dt>{f.label}</dt><dd>{selected.values[f.key]===null?"Not recorded":["recipe","stock","purchase","room"].includes(f.type)?selected.links.find(l=>l.id===selected.values[f.key])?.label??"Saved source":f.type==="money"?`${selected.currency} ${sectorDecimal(selected.values[f.key] as number,digits(selected.currency))}`:f.type==="quantity"?sectorDecimal(selected.values[f.key] as number,3):typeof selected.values[f.key]==="boolean"?selected.values[f.key]?"Yes":"No":pretty(String(selected.values[f.key]))}</dd></div>)}</dl>{selected.notes&&<p>{selected.notes}</p>}</details>
      <div className="sector-actions">{data.writable.includes(selected.kind)&&<>{selected.state==="draft"&&<><button type="button" disabled={busy} onClick={()=>startEdit(selected)}>Edit draft</button><button type="button" disabled={busy||selected.report.missing.length>0} onClick={()=>{setAction("review");setConfirmed(false);}}>Review & approve</button></>}{selected.kind==="reservation"&&selected.state==="active"&&<button type="button" disabled={busy} onClick={()=>startEdit(selected)}>Update folio / departure</button>}{selected.kind==="reservation"&&selected.state==="reviewed"&&<button type="button" disabled={busy} onClick={()=>{setAction("start");setConfirmed(false);}}>Check in</button>}{(selected.state==="reviewed"&&selected.kind!=="reservation"||selected.state==="active")&&<button type="button" disabled={busy||!selected.report.canComplete} onClick={()=>{setAction("complete");setConfirmed(false);}}>{selected.kind==="reservation"?"Complete departure":"Mark complete"}</button>}{selected.state!=="draft"&&<button type="button" disabled={busy} onClick={()=>{setAction("reopen");setReason("");setConfirmed(false);}}>Reopen</button>}{["draft","reviewed"].includes(selected.state)&&<button type="button" disabled={busy} onClick={()=>{setAction("cancel");setConfirmed(false);}}>Cancel record</button>}</>}<button type="button" disabled={busy} onClick={()=>void viewHistory()}>Review history</button></div>
      {action&&<form className="sector-confirm" onSubmit={e=>{e.preventDefault();void mutate({action,id:selected.id,expectedVersion:selected.version,locationId:selected.locationId,confirmed,reason:action==="reopen"?reason:undefined});}}><fieldset disabled={busy}><h4>{pretty(action)} this record</h4>{selected.kind==="prep_batch"&&["review","reopen","cancel"].includes(action)&&<p>{action==="review"?"This consumes the listed ingredients and adds prepared output in managed inventory.":"This reverses any approved batch stock movement. Reversal is blocked if it would leave negative stock."}</p>}{action==="start"&&<p>The room needs today&apos;s inspected, unblocked, unoccupied readiness review.</p>}{action==="reopen"&&<label>Reason for reopening<textarea required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label>}<label className="sector-checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the linked records and confirm this action.</label><div className="sector-actions"><button type="submit" className="sector-primary" disabled={!confirmed}>{busy?"Saving…":"Confirm"}</button><button type="button" onClick={()=>setAction(null)}>Keep current state</button></div></fieldset></form>}
      {history&&<div className="sector-history"><h4>Retained review history</h4>{historyTruncated&&<p>Showing the latest 100 revisions.</p>}{history.map(h=><details key={h.version}><summary>Revision {h.version} · {pretty(h.action)} · {pretty(h.state)} · {new Date(h.createdAt).toLocaleString("en-CA",{timeZone:"UTC"})} UTC</summary><p>{h.content.title} · {h.content.source} · {h.content.sourceDate}</p>{h.reason&&<p>Reason: {h.reason}</p>}<Metrics report={sectorReport(h.content)} currency={h.content.currency}/><dl className="sector-evidence">{SECTOR_DEFINITIONS[h.content.kind].fields.map(f=><div key={f.key}><dt>{f.label}</dt><dd>{h.content.values[f.key]===null?"Not recorded":f.type==="money"?`${h.content.currency} ${sectorDecimal(h.content.values[f.key] as number,digits(h.content.currency))}`:f.type==="quantity"?sectorDecimal(h.content.values[f.key] as number,3):String(h.content.values[f.key])}</dd></div>)}</dl></details>)}</div>}
    </article>}
    {!draft&&!selected&&<div className="sector-records">{records.length?records.map(record=><button type="button" className="sector-record" key={record.id} onClick={()=>{setSelected(record);setAction(null);setHistory(null);setError("");}}><span><small>{SECTOR_DEFINITIONS[record.kind].title}</small><strong>{record.title}</strong><span>{record.dueDate?`Next action ${record.dueDate}`:`Source ${record.sourceDate}`}</span></span><span className={`sector-state sector-state-${record.state}`}>{pretty(record.state)}</span></button>):location&&data.kinds.length>0&&<div className="sector-empty"><h3>Start with the next piece of work.</h3><p>Save a source-backed draft, review its figures, then follow it through completion. Only workflows relevant to your business and permissions appear here.</p></div>}{data.nextCursor&&<button type="button" disabled={busy} onClick={()=>void load(data.nextCursor!)}>Load more records</button>}</div>}
    </>}
  </section>;
}
