"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { apiFetch } from "./supabase-browser";
import { defaultFollowupNote, type FollowupNote, type FollowupPreferences } from "../domain/workflow-followup";
import "./workflow-followup.css";

type InvoiceRow = { id: string; reference: string; contact: string; recipient: string; currency: string; totalCents: number; paidCents: number; status: string; dueDate: string; demo: boolean; followup: FollowupNote; version: number };
type DeliveryRow = { id: string; kind: string; businessDate: string; status: string; attempts: number; errorCode: string | null; acknowledgedAt: number | null; acceptedAt: number | null; createdAt: number; invoiceReference: string | null; summary: { title: string; items: string[]; preparedAt: number } | null };
type Payload = { records: InvoiceRow[]; truncated: boolean; preferences: FollowupPreferences; preferenceVersion: number; schedulingActive: boolean; deliveries: DeliveryRow[]; events: { invoiceId: string; version: number; payloadJson: string; createdAt: number }[]; canEdit: boolean; canAuthorize: boolean; timezone: string; ownerEmail: string | null; mailReady: boolean; schedulerConfigured: boolean };
type Save = (body: Record<string, unknown>) => Promise<void>;
const money = (cents: number, currency: string) => new Intl.NumberFormat("en-CA", { style: "currency", currency }).format(cents / 100);
const stamp = (value: number) => new Intl.DateTimeFormat("en-CA", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value)) + " UTC";
const deliveryLabels: Record<string, string> = { pending: "Queued for delivery", sending: "Send in progress", accepted: "Accepted by email provider", ready: "Ready in Vanteloq", suppressed: "Not sent: eligibility changed", failed: "Needs delivery review" };

export default function WorkflowFollowupPanel({ mode = "briefings" }: { mode?: "collections" | "briefings" }) {
  const [payload, setPayload] = useState<Payload | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [page, setPage] = useState(0), [notice, setNotice] = useState("");
  const active = useRef<AbortController | null>(null), alive = useRef(true);
  const load = useCallback(async () => {
    active.current?.abort(); const controller = new AbortController(); active.current = controller;
    try { const response = await apiFetch(`/api/v1/workflow-followup?mode=${mode}`, { signal: AbortSignal.any([controller.signal, AbortSignal.timeout(20_000)]) }); const body = await response.json(); if (!response.ok) throw Error(body.error?.message ?? "Follow-up could not be loaded."); if (!controller.signal.aborted) { setPayload(body); setError(""); } }
    catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : "Follow-up could not be loaded."); }
    finally { if (!controller.signal.aborted) setLoading(false); }
  }, [mode]);
  useEffect(() => { alive.current = true; let cancelled = false; void Promise.resolve().then(() => { if (!cancelled) void load(); }); return () => { cancelled = true; alive.current = false; active.current?.abort(); }; }, [load]);
  async function save(body: Record<string, unknown>) {
    const response = await apiFetch("/api/v1/workflow-followup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...body, mode }), signal: AbortSignal.timeout(20_000) });
    const result = await response.json(); if (!response.ok) throw Error(result.error?.message ?? "The save could not be confirmed. Reload before retrying.");
    if (alive.current) { setNotice(body.action === "acknowledge" ? "Briefing acknowledged." : "Saved. Existing payment and accounting records are unchanged."); await load(); }
  }
  return <section className="workflow-followup" aria-label={mode === "collections" ? "Collection follow-through" : "Daily follow-through"}>
    <header><div><p className="wf-eyebrow">{mode === "collections" ? "BOOKLOQ" : "YOUR BUSINESS DAY"}</p><h2>{mode === "collections" ? "Keep the next conversation clear" : "Daily follow-through"}</h2><p>{mode === "collections" ? "Promises, contact notes and the next action beside each invoice." : "Opening and closing briefings, ready for review on your schedule."}</p></div><button type="button" onClick={() => { setLoading(true); setError(""); void load(); }} disabled={loading}>Refresh</button></header>
    {notice && <p role="status" className="wf-success">{notice}</p>}{error && <p role="alert" className="wf-error">{error}</p>}
    {loading && !payload && <p role="status">Loading your saved follow-through…</p>}
    {payload && <>
      {payload.canAuthorize && <PreferenceForm key={payload.preferenceVersion} data={payload} mode={mode} save={save} />}
      {mode === "collections" && <div className="wf-invoices">{payload.records.length === 0 ? <div className="wf-empty"><h3>No invoices need follow-up yet</h3><p>Create and review an invoice in BookLoQ. Its contact details and current balance will appear here.</p></div> : payload.records.slice(page * 20, page * 20 + 20).map(row => <details className="wf-invoice" key={row.id}><summary><span><strong>{row.reference}</strong><small>{row.contact} · Due {row.dueDate}</small></span><span><strong>{money(row.totalCents - row.paidCents, row.currency)}</strong><small>{row.status.replaceAll("_", " ")}{row.followup.paused ? " · Follow-up paused" : ""}</small></span></summary><CollectionForm key={`${row.id}:${row.version}`} invoice={row} canEdit={payload.canEdit} canAuthorize={payload.canAuthorize} save={save} /><details className="wf-history"><summary>Saved follow-up history</summary>{payload.events.filter(e => e.invoiceId === row.id).map(e => { const note = JSON.parse(e.payloadJson) as FollowupNote; return <article key={e.version}><strong>Version {e.version} · {stamp(e.createdAt)}</strong><p>{note.contactNote || "No contact note."}</p><p>{note.nextAction || "No next action saved."}{note.nextActionDate ? ` Due ${note.nextActionDate}.` : ""}</p>{note.promisedDate && <p>Promise: {money(note.promisedCents!, row.currency)} on {note.promisedDate}.</p>}</article>; })}<p className="wf-note">The latest 100 workspace follow-up events are shown here. Saving does not record a payment.</p></details></details>)}
        {payload.records.length > 20 && <nav aria-label="Invoice pages"><button disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page + 1} of {Math.ceil(payload.records.length / 20)}</span><button disabled={(page + 1) * 20 >= payload.records.length} onClick={() => setPage(page + 1)}>Next</button></nav>}{payload.truncated && <p className="wf-note">The first 200 invoices are shown by due date. Use the full invoice view to review additional records.</p>}
      </div>}
      <div className="wf-receipts"><h3>{mode === "collections" ? "Reminder attempts" : "Prepared briefings"}</h3><p className="wf-note">Provider acceptance confirms an email submission, not that someone received or read it.</p>{payload.deliveries.length === 0 && <p>No delivery attempts yet. Nothing is sent until you explicitly enable the relevant preference.</p>}{payload.deliveries.map(row => <details key={row.id}><summary><span>{row.summary?.title ?? row.invoiceReference ?? "Invoice reminder"}<small>{row.businessDate}</small></span><span>{deliveryLabels[row.status] ?? row.status}</span></summary>{row.summary && <><p className="wf-note">Prepared {stamp(row.summary.preparedAt)}. Open current records before acting.</p><ul>{row.summary.items.map((item, i) => <li key={i}>{item}</li>)}</ul></>}{row.errorCode && <p className="wf-note">{row.errorCode.replace("FOLLOWUP_", "").replaceAll("_", " ").toLowerCase()}. Current eligibility is checked before any retry.</p>}<p className="wf-note">{row.attempts} attempt{row.attempts === 1 ? "" : "s"}{row.acceptedAt ? ` · Accepted ${stamp(row.acceptedAt)}` : ""}</p>{row.kind !== "reminder" && ["accepted", "ready"].includes(row.status) && (row.acknowledgedAt ? <p>Reviewed {stamp(row.acknowledgedAt)}</p> : <Acknowledge id={row.id} save={save} />)}</details>)}</div>
    </>}
  </section>;
}
function Acknowledge({ id, save }: { id: string; save: Save }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  return <><button disabled={busy} onClick={async () => { setBusy(true); try { await save({ action: "acknowledge", id }); } catch (e) { setError(e instanceof Error ? e.message : "Acknowledgement could not be saved."); } finally { setBusy(false); } }}>Mark reviewed</button>{error && <p role="alert">{error}</p>}</>;
}
function CollectionForm({ invoice, canEdit, canAuthorize, save }: { invoice: InvoiceRow; canEdit: boolean; canAuthorize: boolean; save: Save }) {
  const [note, setNote] = useState({ ...(invoice.followup ?? defaultFollowupNote) }), [promise, setPromise] = useState(invoice.followup.promisedCents == null ? "" : (invoice.followup.promisedCents / 100).toFixed(2)), [reviewed, setReviewed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const key = useRef(crypto.randomUUID());
  function change(value: Partial<FollowupNote>) { setNote(p => ({ ...p, ...value })); setReviewed(false); key.current = crypto.randomUUID(); }
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { if (promise && !/^\d{1,10}(?:\.\d{1,2})?$/.test(promise)) throw Error("Enter the promised amount with up to two decimal places."); const [whole, fraction = ""] = promise.split("."); const promisedCents = promise ? Number(whole) * 100 + Number(fraction.padEnd(2, "0")) : null; await save({ action: "save_followup", invoiceId: invoice.id, expectedVersion: invoice.version, mutationKey: key.current, record: { ...note, promisedCents }, reviewed }); } catch (e) { setError(e instanceof Error ? e.message : "The follow-up could not be saved. Your entries remain here."); } finally { setBusy(false); } }
  return <form onSubmit={submit}><fieldset disabled={!canEdit || busy}><legend>Next step for {invoice.reference}</legend><p className="wf-note">Customer email: {invoice.recipient || "Add an email to the invoice first."} · {invoice.demo ? "Demonstration invoice. Reminders cannot be enabled." : "Reminders use this saved address."}</p><label>Last contact date<input type="date" value={note.lastContactDate ?? ""} onChange={e => change({ lastContactDate: e.target.value || null })} /></label><label>Contact note<textarea maxLength={1000} value={note.contactNote} onChange={e => change({ contactNote: e.target.value })} /></label><label>Promised payment date<input type="date" value={note.promisedDate ?? ""} onChange={e => change({ promisedDate: e.target.value || null })} /></label><label>Promised amount ({invoice.currency})<input inputMode="decimal" value={promise} onChange={e => { setPromise(e.target.value); setReviewed(false); key.current = crypto.randomUUID(); }} /></label><label>Dispute owner, if disputed<input maxLength={120} value={note.disputeOwner} onChange={e => change({ disputeOwner: e.target.value })} /></label><label>Next action<textarea maxLength={500} value={note.nextAction} onChange={e => change({ nextAction: e.target.value })} /></label><label>Next action date<input type="date" value={note.nextActionDate ?? ""} onChange={e => change({ nextActionDate: e.target.value || null })} /></label><label className="wf-check"><input type="checkbox" checked={note.paused} onChange={e => change({ paused: e.target.checked })} />Pause invoice reminders</label>{canAuthorize && <><label className="wf-check"><input type="checkbox" disabled={Boolean(invoice.demo) || !invoice.recipient} checked={note.remindersEnabled} onChange={e => change({ remindersEnabled: e.target.checked })} />Approve reminders for this invoice and its saved customer email</label><label>Minimum days between contacts<select value={note.reminderIntervalDays} onChange={e => change({ reminderIntervalDays: Number(e.target.value) })}>{[1, 3, 7, 14, 21, 30].map(d => <option key={d} value={d}>{d} days</option>)}</select></label><p className="wf-note">Your reminder schedule must also be enabled above. Payments, disputes, future promises and changed invoice details suppress scheduled messages.</p></>}{canEdit && <><label className="wf-check"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I reviewed the contact information, promise and next action.</label><button className="wf-primary" disabled={!reviewed || busy}>Save follow-up</button></>}</fieldset>{error && <p role="alert" className="wf-error">{error}</p>}</form>;
}
function PreferenceForm({ data, mode, save }: { data: Payload; mode: "collections" | "briefings"; save: Save }) {
  const [prefs, setPrefs] = useState<FollowupPreferences>({ ...data.preferences }), [reviewed, setReviewed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [exception, setException] = useState({ date: "", open: "09:00", close: "17:00", closed: true }), key = useRef(crypto.randomUUID());
  function change(value: Partial<FollowupPreferences>) { setPrefs(p => ({ ...p, ...value })); setReviewed(false); key.current = crypto.randomUUID(); }
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { await save({ action: "save_preferences", preferences: prefs, expectedVersion: data.preferenceVersion, mutationKey: key.current, reviewed }); } catch (e) { setError(e instanceof Error ? e.message : "Preferences could not be saved. Your entries remain here."); } finally { setBusy(false); } }
  return <details className="wf-preferences"><summary><span>Delivery preferences<small>{data.timezone} · Owner-controlled delivery</small></span><span>{mode === "collections" ? prefs.invoiceReminders && data.schedulingActive ? "Reminders enabled" : "Reminders off" : (prefs.opening || prefs.closing) && data.schedulingActive ? "Briefings enabled" : "Briefings off"}</span></summary><form onSubmit={submit}><fieldset disabled={busy}><legend>Your delivery choices</legend><button type="button" onClick={() => change({ opening: false, closing: false, emailBriefings: false, invoiceReminders: false })}>Turn off all delivery choices</button>{!data.schedulingActive && (data.preferences.opening || data.preferences.closing || data.preferences.invoiceReminders) && <p className="wf-note">Scheduling is paused. Review your current access and save these choices to renew authorization.</p>}{!data.schedulerConfigured && <p className="wf-note">Background delivery is not configured yet. Tracking and saved notes remain available.</p>}{mode === "collections" ? <label className="wf-check"><input type="checkbox" checked={prefs.invoiceReminders} onChange={e => change({ invoiceReminders: e.target.checked })} />Enable scheduled customer reminders for individually approved invoices</label> : <><label className="wf-check"><input type="checkbox" checked={prefs.opening} onChange={e => change({ opening: e.target.checked })} />Prepare an opening briefing</label><label>Minutes before opening<select value={prefs.openingLeadMinutes} onChange={e => change({ openingLeadMinutes: Number(e.target.value) })}>{[0, 15, 30, 60, 120].map(n => <option key={n}>{n}</option>)}</select></label><label className="wf-check"><input type="checkbox" checked={prefs.closing} onChange={e => change({ closing: e.target.checked })} />Prepare a closing briefing</label><label>Minutes after closing<select value={prefs.closingDelayMinutes} onChange={e => change({ closingDelayMinutes: Number(e.target.value) })}>{[0, 15, 30, 60, 120].map(n => <option key={n}>{n}</option>)}</select></label><label className="wf-check"><input type="checkbox" checked={prefs.emailBriefings} onChange={e => change({ emailBriefings: e.target.checked })} />Email me a sign-in link when my briefing is ready</label><p className="wf-note">Links go only to your verified owner address: {data.ownerEmail}. Financial and customer details stay inside Vanteloq.</p></>}
      <label>Quiet hours start<input type="time" value={prefs.quietStart} onChange={e => change({ quietStart: e.target.value })} /></label><label>Quiet hours end<input type="time" value={prefs.quietEnd} onChange={e => change({ quietEnd: e.target.value })} /></label>{!data.mailReady && <p className="wf-note">Email is not configured. Leave email and customer reminders off; in-app briefings can still run if scheduling is available.</p>}
      {mode === "briefings" && <details><summary>Holidays and exceptional hours</summary><p className="wf-note">Regular hours come from your saved business profile. These dated exceptions apply only to briefing timing.</p><label>Exception date<input type="date" value={exception.date} onChange={e => setException({ ...exception, date: e.target.value })} /></label><label className="wf-check"><input type="checkbox" checked={exception.closed} onChange={e => setException({ ...exception, closed: e.target.checked })} />Closed on this date</label>{!exception.closed && <><label>Opens<input type="time" value={exception.open} onChange={e => setException({ ...exception, open: e.target.value })} /></label><label>Closes<input type="time" value={exception.close} onChange={e => setException({ ...exception, close: e.target.value })} /></label></>}<button type="button" disabled={!exception.date || prefs.exceptions.length >= 40} onClick={() => { change({ exceptions: [...prefs.exceptions.filter(r => r.date !== exception.date), exception] }); setException({ ...exception, date: "" }); }}>Add date to preferences</button>{prefs.exceptions.map(row => <div className="wf-exception" key={row.date}><span>{row.date} · {row.closed ? "Closed" : `${row.open} to ${row.close}`}</span><button type="button" onClick={() => change({ exceptions: prefs.exceptions.filter(r => r.date !== row.date) })} aria-label={`Remove exception ${row.date}`}>Remove</button></div>)}</details>}
      <label className="wf-check"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I approve these recurring actions. I can disable them here. Emails are only sent for enabled choices.</label><button className="wf-primary" disabled={!reviewed || busy}>Save delivery preferences</button></fieldset>{error && <p role="alert" className="wf-error">{error}</p>}</form></details>;
}
