import { sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// Legacy prototype tables are retained so existing data is not destructively
// dropped by the first secure migration. Application routes no longer use them.
export const legacyTasks = sqliteTable("tasks", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: text("organization_id").notNull(),
  title: text("title").notNull(),
  detail: text("detail").notNull().default(""),
  priority: text("priority").notNull().default("medium"),
  status: text("status").notNull().default("open"),
  assignee: text("assignee").notNull().default("Owner"),
  dueDate: text("due_date"),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const legacyOrganizations = sqliteTable("organizations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ownerEmail: text("owner_email").notNull().unique(),
  ownerName: text("owner_name").notNull(),
  businessName: text("business_name").notNull(),
  legalName: text("legal_name").notNull(),
  businessEmail: text("business_email").notNull(),
  phone: text("phone").notNull().default(""),
  website: text("website").notNull().default(""),
  industry: text("industry").notNull(),
  country: text("country").notNull().default("Canada"),
  province: text("province").notNull().default(""),
  city: text("city").notNull(),
  address: text("address").notNull(),
  postalCode: text("postal_code").notNull(),
  timezone: text("timezone").notNull().default("America/Toronto"),
  currency: text("currency").notNull().default("CAD"),
  fiscalYearStart: text("fiscal_year_start").notNull().default("January"),
  taxNumber: text("tax_number").notNull().default(""),
  hoursJson: text("hours_json").notNull(),
  sourceMode: text("source_mode").notNull().default("connect_later"),
  selectedPos: text("selected_pos").notNull().default(""),
  setupComplete: integer("setup_complete", { mode: "boolean" }).notNull().default(true),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const users = sqliteTable(
  "users",
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    displayName: text("display_name").notNull(),
    status: text("status", { enum: ["active", "suspended"] }).notNull().default("active"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("users_email_unique").on(table.email),
    check("users_status_check", sql`${table.status} in ('active', 'suspended')`),
  ],
);

export const workspaces = sqliteTable(
  "workspaces",
  {
    id: text("id").primaryKey(),
    ownerName: text("owner_name").notNull(),
    businessName: text("business_name").notNull(),
    legalName: text("legal_name").notNull(),
    businessEmail: text("business_email").notNull(),
    phone: text("phone").notNull().default(""),
    website: text("website").notNull().default(""),
    industry: text("industry").notNull(),
    country: text("country").notNull().default("Canada"),
    province: text("province").notNull().default(""),
    city: text("city").notNull(),
    address: text("address").notNull(),
    postalCode: text("postal_code").notNull(),
    timezone: text("timezone").notNull().default("America/Toronto"),
    currency: text("currency").notNull().default("CAD"),
    fiscalYearStart: text("fiscal_year_start").notNull().default("January"),
    taxNumber: text("tax_number").notNull().default(""),
    hoursJson: text("hours_json").notNull(),
    sourceMode: text("source_mode", { enum: ["connect_later", "csv", "live"] }).notNull().default("connect_later"),
    selectedPos: text("selected_pos").notNull().default(""),
    setupComplete: integer("setup_complete", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    index("workspaces_business_name_idx").on(table.businessName),
    check("workspaces_source_mode_check", sql`${table.sourceMode} in ('connect_later', 'csv', 'live')`),
  ],
);

export const memberships = sqliteTable(
  "memberships",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    role: text("role", { enum: ["owner", "admin", "manager", "employee", "read_only", "integration"] }).notNull(),
    status: text("status", { enum: ["active", "suspended"] }).notNull().default("active"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("memberships_user_unique").on(table.userId),
    uniqueIndex("memberships_user_workspace_unique").on(table.userId, table.organizationId),
    index("memberships_workspace_idx").on(table.organizationId),
    check("memberships_role_check", sql`${table.role} in ('owner', 'admin', 'manager', 'employee', 'read_only', 'integration')`),
    check("memberships_status_check", sql`${table.status} in ('active', 'suspended')`),
  ],
);

export const workspaceTasks = sqliteTable(
  "workspace_tasks",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    detail: text("detail").notNull().default(""),
    priority: text("priority", { enum: ["high", "medium", "low"] }).notNull().default("medium"),
    status: text("status", { enum: ["open", "in_progress", "done"] }).notNull().default("open"),
    assignee: text("assignee").notNull().default("Owner"),
    dueDate: text("due_date"),
    sourceType: text("source_type", { enum: ["manual", "insight", "alert", "decision"] }).notNull().default("manual"),
    sourceRef: text("source_ref"),
    expectedImpact: text("expected_impact").notNull().default(""),
    createdByUserId: text("created_by_user_id").notNull().references(() => users.id),
    idempotencyKey: text("idempotency_key").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("workspace_tasks_idempotency_unique").on(table.organizationId, table.idempotencyKey),
    index("workspace_tasks_workspace_status_idx").on(table.organizationId, table.status),
    index("workspace_tasks_workspace_created_idx").on(table.organizationId, table.createdAt),
    check("workspace_tasks_priority_check", sql`${table.priority} in ('high', 'medium', 'low')`),
    check("workspace_tasks_status_check", sql`${table.status} in ('open', 'in_progress', 'done')`),
    check("workspace_tasks_source_type_check", sql`${table.sourceType} in ('manual', 'insight', 'alert', 'decision')`),
  ],
);

export const dataImports = sqliteTable(
  "data_imports",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    importType: text("import_type", { enum: ["daily_summary_csv", "manual_entry"] }).notNull(),
    status: text("status", { enum: ["processing", "completed", "failed"] }).notNull(),
    fileName: text("file_name").notNull().default(""),
    rowCount: integer("row_count").notNull().default(0),
    idempotencyKey: text("idempotency_key").notNull(),
    importedByUserId: text("imported_by_user_id").notNull().references(() => users.id),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("data_imports_workspace_idempotency_unique").on(table.organizationId, table.idempotencyKey),
    index("data_imports_workspace_created_idx").on(table.organizationId, table.createdAt),
    check("data_imports_type_check", sql`${table.importType} in ('daily_summary_csv', 'manual_entry')`),
    check("data_imports_status_check", sql`${table.status} in ('processing', 'completed', 'failed')`),
    check("data_imports_row_count_check", sql`${table.rowCount} >= 0`),
  ],
);

export const dailyBusinessMetrics = sqliteTable(
  "daily_business_metrics",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    businessDate: text("business_date").notNull(),
    locationRef: text("location_ref").notNull().default("all"),
    grossSalesCents: integer("gross_sales_cents").notNull(),
    netSalesCents: integer("net_sales_cents").notNull(),
    costOfGoodsCents: integer("cost_of_goods_cents").notNull(),
    transactionCount: integer("transaction_count").notNull(),
    unitsSold: integer("units_sold").notNull(),
    refundsCents: integer("refunds_cents").notNull().default(0),
    discountsCents: integer("discounts_cents").notNull().default(0),
    labourCostCents: integer("labour_cost_cents").notNull().default(0),
    inventoryValueCents: integer("inventory_value_cents"),
    cashBalanceCents: integer("cash_balance_cents"),
    accountsPayableCents: integer("accounts_payable_cents"),
    sourceImportId: text("source_import_id").references(() => dataImports.id, { onDelete: "set null" }),
    createdByUserId: text("created_by_user_id").notNull().references(() => users.id),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("daily_metrics_workspace_date_location_unique").on(table.organizationId, table.businessDate, table.locationRef),
    index("daily_metrics_workspace_date_idx").on(table.organizationId, table.businessDate),
    check("daily_metrics_nonnegative_amounts_check", sql`${table.grossSalesCents} >= 0 and ${table.netSalesCents} >= 0 and ${table.costOfGoodsCents} >= 0 and ${table.refundsCents} >= 0 and ${table.discountsCents} >= 0 and ${table.labourCostCents} >= 0`),
    check("daily_metrics_nonnegative_counts_check", sql`${table.transactionCount} >= 0 and ${table.unitsSold} >= 0`),
  ],
);

export const businessEvents = sqliteTable(
  "business_events",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    eventType: text("event_type", { enum: ["decision", "promotion", "hours", "staffing", "supplier_price", "stockout", "competitor", "construction", "other"] }).notNull(),
    title: text("title").notNull(),
    detail: text("detail").notNull().default(""),
    eventDate: text("event_date").notNull(),
    expectedOutcome: text("expected_outcome").notNull().default(""),
    reviewDate: text("review_date"),
    status: text("status", { enum: ["active", "reviewed"] }).notNull().default("active"),
    createdByUserId: text("created_by_user_id").notNull().references(() => users.id),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    index("business_events_workspace_date_idx").on(table.organizationId, table.eventDate),
    check("business_events_type_check", sql`${table.eventType} in ('decision', 'promotion', 'hours', 'staffing', 'supplier_price', 'stockout', 'competitor', 'construction', 'other')`),
    check("business_events_status_check", sql`${table.status} in ('active', 'reviewed')`),
  ],
);

export const integrationConnections = sqliteTable(
  "integration_connections",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    provider: text("provider").notNull(),
    status: text("status", { enum: ["not_connected", "pending", "connected", "error", "revoked"] }).notNull().default("not_connected"),
    externalAccountRef: text("external_account_ref"),
    scopesJson: text("scopes_json").notNull().default("[]"),
    lastSuccessfulSyncAt: integer("last_successful_sync_at", { mode: "timestamp" }),
    lastErrorCode: text("last_error_code"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("integration_connections_workspace_provider_unique").on(table.organizationId, table.provider),
    check("integration_connections_status_check", sql`${table.status} in ('not_connected', 'pending', 'connected', 'error', 'revoked')`),
  ],
);

// BookLoQ stores every monetary amount as an integer number of minor currency
// units (for example, Canadian cents). Rates use integer basis points or parts
// per million. JavaScript floating-point values are never persisted as money.
export const bookloqSettings = sqliteTable(
  "bookloq_settings",
  {
    organizationId: text("organization_id").primaryKey().references(() => workspaces.id, { onDelete: "cascade" }),
    baseCurrency: text("base_currency").notNull().default("CAD"),
    countryCode: text("country_code").notNull().default("CA"),
    provinceCode: text("province_code").notNull().default("AB"),
    accountingBasis: text("accounting_basis", { enum: ["accrual", "cash"] }).notNull().default("accrual"),
    fiscalYearStartMonth: integer("fiscal_year_start_month").notNull().default(1),
    cashSafetyThresholdCents: integer("cash_safety_threshold_cents").notNull().default(0),
    status: text("status", { enum: ["not_configured", "active", "suspended"] }).notNull().default("not_configured"),
    dataMode: text("data_mode", { enum: ["live", "demonstration"] }).notNull().default("live"),
    updatedByUserId: text("updated_by_user_id").notNull().references(() => users.id),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    check("bookloq_settings_basis_check", sql`${table.accountingBasis} in ('accrual', 'cash')`),
    check("bookloq_settings_status_check", sql`${table.status} in ('not_configured', 'active', 'suspended')`),
    check("bookloq_settings_mode_check", sql`${table.dataMode} in ('live', 'demonstration')`),
    check("bookloq_settings_fiscal_month_check", sql`${table.fiscalYearStartMonth} between 1 and 12`),
    check("bookloq_settings_threshold_check", sql`${table.cashSafetyThresholdCents} >= 0`),
  ],
);

export const bookloqRoleAssignments = sqliteTable(
  "bookloq_role_assignments",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    role: text("role", { enum: ["owner", "administrator", "finance_manager", "store_manager", "accountant", "bookkeeper", "ap_clerk", "ar_clerk", "employee", "read_only_auditor"] }).notNull(),
    permissionsJson: text("permissions_json").notNull().default("[]"),
    createdByUserId: text("created_by_user_id").notNull().references(() => users.id),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("bookloq_roles_workspace_user_unique").on(table.organizationId, table.userId),
    index("bookloq_roles_workspace_role_idx").on(table.organizationId, table.role),
    check("bookloq_roles_role_check", sql`${table.role} in ('owner', 'administrator', 'finance_manager', 'store_manager', 'accountant', 'bookkeeper', 'ap_clerk', 'ar_clerk', 'employee', 'read_only_auditor')`),
  ],
);

export const financialAccounts = sqliteTable(
  "financial_accounts",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    code: text("code").notNull(),
    name: text("name").notNull(),
    accountType: text("account_type", { enum: ["asset", "liability", "equity", "revenue", "expense"] }).notNull(),
    accountSubtype: text("account_subtype").notNull(),
    normalBalance: text("normal_balance", { enum: ["debit", "credit"] }).notNull(),
    systemKey: text("system_key"),
    parentAccountId: text("parent_account_id"),
    description: text("description").notNull().default(""),
    plainLanguage: text("plain_language").notNull().default(""),
    taxTreatment: text("tax_treatment").notNull().default("none"),
    restricted: integer("restricted", { mode: "boolean" }).notNull().default(false),
    active: integer("active", { mode: "boolean" }).notNull().default(true),
    archivedAt: integer("archived_at", { mode: "timestamp" }),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("financial_accounts_workspace_code_unique").on(table.organizationId, table.code),
    uniqueIndex("financial_accounts_workspace_system_unique").on(table.organizationId, table.systemKey),
    index("financial_accounts_workspace_type_idx").on(table.organizationId, table.accountType),
    check("financial_accounts_type_check", sql`${table.accountType} in ('asset', 'liability', 'equity', 'revenue', 'expense')`),
    check("financial_accounts_normal_balance_check", sql`${table.normalBalance} in ('debit', 'credit')`),
  ],
);

export const accountingPeriods = sqliteTable(
  "accounting_periods",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    startDate: text("start_date").notNull(),
    endDate: text("end_date").notNull(),
    status: text("status", { enum: ["open", "review", "locked"] }).notNull().default("open"),
    lockedAt: integer("locked_at", { mode: "timestamp" }),
    lockedByUserId: text("locked_by_user_id").references(() => users.id),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("accounting_periods_workspace_dates_unique").on(table.organizationId, table.startDate, table.endDate),
    index("accounting_periods_workspace_status_idx").on(table.organizationId, table.status),
    check("accounting_periods_status_check", sql`${table.status} in ('open', 'review', 'locked')`),
    check("accounting_periods_dates_check", sql`${table.startDate} <= ${table.endDate}`),
  ],
);

export const bookloqContacts = sqliteTable(
  "bookloq_contacts",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    contactType: text("contact_type", { enum: ["customer", "supplier", "both"] }).notNull(),
    name: text("name").notNull(),
    email: text("email").notNull().default(""),
    phone: text("phone").notNull().default(""),
    billingAddress: text("billing_address").notNull().default(""),
    paymentTermsDays: integer("payment_terms_days").notNull().default(30),
    creditLimitCents: integer("credit_limit_cents").notNull().default(0),
    taxRegistrationNumber: text("tax_registration_number").notNull().default(""),
    notes: text("notes").notNull().default(""),
    active: integer("active", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    index("bookloq_contacts_workspace_type_idx").on(table.organizationId, table.contactType),
    check("bookloq_contacts_type_check", sql`${table.contactType} in ('customer', 'supplier', 'both')`),
    check("bookloq_contacts_terms_check", sql`${table.paymentTermsDays} between 0 and 365`),
    check("bookloq_contacts_credit_check", sql`${table.creditLimitCents} >= 0`),
  ],
);

export const journalEntries = sqliteTable(
  "journal_entries",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    entryNumber: text("entry_number").notNull(),
    entryDate: text("entry_date").notNull(),
    postingDate: text("posting_date").notNull(),
    periodId: text("period_id").references(() => accountingPeriods.id),
    status: text("status", { enum: ["draft", "posted", "reversed", "void"] }).notNull().default("draft"),
    sourceType: text("source_type").notNull().default("manual"),
    sourceRef: text("source_ref"),
    memo: text("memo").notNull(),
    currency: text("currency").notNull().default("CAD"),
    exchangeRatePpm: integer("exchange_rate_ppm").notNull().default(1_000_000),
    totalDebitCents: integer("total_debit_cents").notNull(),
    totalCreditCents: integer("total_credit_cents").notNull(),
    reversalOfEntryId: text("reversal_of_entry_id"),
    idempotencyKey: text("idempotency_key").notNull(),
    preparedByUserId: text("prepared_by_user_id").notNull().references(() => users.id),
    approvedByUserId: text("approved_by_user_id").references(() => users.id),
    postedAt: integer("posted_at", { mode: "timestamp" }),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("journal_entries_workspace_number_unique").on(table.organizationId, table.entryNumber),
    uniqueIndex("journal_entries_workspace_idempotency_unique").on(table.organizationId, table.idempotencyKey),
    uniqueIndex("journal_entries_workspace_reversal_unique").on(table.organizationId, table.reversalOfEntryId),
    index("journal_entries_workspace_date_idx").on(table.organizationId, table.postingDate),
    index("journal_entries_workspace_status_idx").on(table.organizationId, table.status),
    check("journal_entries_status_check", sql`${table.status} in ('draft', 'posted', 'reversed', 'void')`),
    check("journal_entries_money_check", sql`${table.totalDebitCents} >= 0 and ${table.totalCreditCents} >= 0`),
    check("journal_entries_balance_check", sql`${table.status} != 'posted' or ${table.totalDebitCents} = ${table.totalCreditCents}`),
    check("journal_entries_rate_check", sql`${table.exchangeRatePpm} > 0`),
  ],
);

export const journalLines = sqliteTable(
  "journal_lines",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    journalEntryId: text("journal_entry_id").notNull().references(() => journalEntries.id, { onDelete: "cascade" }),
    lineNumber: integer("line_number").notNull(),
    accountId: text("account_id").notNull().references(() => financialAccounts.id),
    description: text("description").notNull().default(""),
    debitCents: integer("debit_cents").notNull().default(0),
    creditCents: integer("credit_cents").notNull().default(0),
    taxCode: text("tax_code"),
    taxAmountCents: integer("tax_amount_cents").notNull().default(0),
    contactId: text("contact_id").references(() => bookloqContacts.id),
    locationRef: text("location_ref").notNull().default("all"),
    departmentRef: text("department_ref"),
    projectRef: text("project_ref"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("journal_lines_entry_line_unique").on(table.journalEntryId, table.lineNumber),
    index("journal_lines_workspace_account_idx").on(table.organizationId, table.accountId),
    check("journal_lines_amount_check", sql`${table.debitCents} >= 0 and ${table.creditCents} >= 0 and ((${table.debitCents} > 0 and ${table.creditCents} = 0) or (${table.creditCents} > 0 and ${table.debitCents} = 0))`),
    check("journal_lines_tax_check", sql`${table.taxAmountCents} >= 0`),
  ],
);

export const financialTransactions = sqliteTable(
  "financial_transactions",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    transactionDate: text("transaction_date").notNull(),
    postingDate: text("posting_date").notNull(),
    description: text("description").notNull(),
    originalDescription: text("original_description").notNull().default(""),
    amountCents: integer("amount_cents").notNull(),
    currency: text("currency").notNull().default("CAD"),
    exchangeRatePpm: integer("exchange_rate_ppm").notNull().default(1_000_000),
    taxAmountCents: integer("tax_amount_cents").notNull().default(0),
    accountId: text("account_id").references(() => financialAccounts.id),
    contactId: text("contact_id").references(() => bookloqContacts.id),
    sourceSystem: text("source_system").notNull(),
    externalSourceId: text("external_source_id").notNull(),
    locationRef: text("location_ref").notNull().default("all"),
    departmentRef: text("department_ref"),
    projectRef: text("project_ref"),
    reconciliationStatus: text("reconciliation_status", { enum: ["unreconciled", "matched", "reconciled"] }).notNull().default("unreconciled"),
    categorizationStatus: text("categorization_status", { enum: ["confirmed", "suggested", "missing", "issue", "accountant_review"] }).notNull().default("missing"),
    confidenceBasisPoints: integer("confidence_basis_points").notNull().default(0),
    approvalStatus: text("approval_status", { enum: ["not_required", "pending", "approved", "rejected"] }).notNull().default("not_required"),
    journalEntryId: text("journal_entry_id").references(() => journalEntries.id),
    demoRecord: integer("demo_record", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("financial_transactions_source_unique").on(table.organizationId, table.sourceSystem, table.externalSourceId),
    index("financial_transactions_workspace_date_idx").on(table.organizationId, table.postingDate),
    index("financial_transactions_workspace_review_idx").on(table.organizationId, table.categorizationStatus, table.reconciliationStatus),
    check("financial_transactions_reconciliation_check", sql`${table.reconciliationStatus} in ('unreconciled', 'matched', 'reconciled')`),
    check("financial_transactions_categorization_check", sql`${table.categorizationStatus} in ('confirmed', 'suggested', 'missing', 'issue', 'accountant_review')`),
    check("financial_transactions_confidence_check", sql`${table.confidenceBasisPoints} between 0 and 10000`),
  ],
);

export const bankAccounts = sqliteTable(
  "bank_accounts",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    financialAccountId: text("financial_account_id").notNull().references(() => financialAccounts.id),
    name: text("name").notNull(),
    accountType: text("account_type", { enum: ["chequing", "savings", "credit_card", "line_of_credit", "merchant", "loan"] }).notNull(),
    institutionName: text("institution_name").notNull(),
    maskedNumber: text("masked_number").notNull(),
    liveBalanceCents: integer("live_balance_cents"),
    availableBalanceCents: integer("available_balance_cents"),
    bookBalanceCents: integer("book_balance_cents").notNull().default(0),
    availableCreditCents: integer("available_credit_cents"),
    connectionStatus: text("connection_status", { enum: ["manual", "healthy", "delayed", "error"] }).notNull().default("manual"),
    lastSyncAt: integer("last_sync_at", { mode: "timestamp" }),
    lastReconciledAt: integer("last_reconciled_at", { mode: "timestamp" }),
    demoRecord: integer("demo_record", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("bank_accounts_workspace_ledger_unique").on(table.organizationId, table.financialAccountId),
    check("bank_accounts_type_check", sql`${table.accountType} in ('chequing', 'savings', 'credit_card', 'line_of_credit', 'merchant', 'loan')`),
    check("bank_accounts_connection_check", sql`${table.connectionStatus} in ('manual', 'healthy', 'delayed', 'error')`),
  ],
);

export const reconciliations = sqliteTable(
  "reconciliations",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    accountId: text("account_id").notNull().references(() => financialAccounts.id),
    reconciliationType: text("reconciliation_type").notNull(),
    startDate: text("start_date").notNull(),
    endDate: text("end_date").notNull(),
    openingBalanceCents: integer("opening_balance_cents").notNull(),
    closingBalanceCents: integer("closing_balance_cents").notNull(),
    bookBalanceCents: integer("book_balance_cents").notNull(),
    differenceCents: integer("difference_cents").notNull(),
    status: text("status", { enum: ["draft", "prepared", "reviewed", "completed", "locked"] }).notNull().default("draft"),
    preparedByUserId: text("prepared_by_user_id").references(() => users.id),
    reviewedByUserId: text("reviewed_by_user_id").references(() => users.id),
    completedAt: integer("completed_at", { mode: "timestamp" }),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("reconciliations_workspace_account_period_unique").on(table.organizationId, table.accountId, table.startDate, table.endDate),
    index("reconciliations_workspace_status_idx").on(table.organizationId, table.status),
    check("reconciliations_status_check", sql`${table.status} in ('draft', 'prepared', 'reviewed', 'completed', 'locked')`),
    check("reconciliations_dates_check", sql`${table.startDate} <= ${table.endDate}`),
  ],
);

export const supplierBills = sqliteTable(
  "supplier_bills",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    supplierId: text("supplier_id").notNull().references(() => bookloqContacts.id),
    billNumber: text("bill_number").notNull(),
    invoiceDate: text("invoice_date").notNull(),
    dueDate: text("due_date").notNull(),
    status: text("status", { enum: ["draft", "received", "extracted", "under_review", "matched", "awaiting_approval", "approved", "scheduled", "partially_paid", "paid", "reconciled", "disputed", "void"] }).notNull().default("draft"),
    subtotalCents: integer("subtotal_cents").notNull(),
    taxCents: integer("tax_cents").notNull().default(0),
    totalCents: integer("total_cents").notNull(),
    paidCents: integer("paid_cents").notNull().default(0),
    currency: text("currency").notNull().default("CAD"),
    purchaseOrderRef: text("purchase_order_ref"),
    locationRef: text("location_ref").notNull().default("all"),
    approvalStatus: text("approval_status", { enum: ["not_required", "pending", "approved", "rejected"] }).notNull().default("pending"),
    journalEntryId: text("journal_entry_id").references(() => journalEntries.id),
    demoRecord: integer("demo_record", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("supplier_bills_workspace_number_unique").on(table.organizationId, table.supplierId, table.billNumber),
    index("supplier_bills_workspace_due_idx").on(table.organizationId, table.dueDate, table.status),
    check("supplier_bills_amount_check", sql`${table.subtotalCents} >= 0 and ${table.taxCents} >= 0 and ${table.totalCents} = ${table.subtotalCents} + ${table.taxCents} and ${table.paidCents} >= 0 and ${table.paidCents} <= ${table.totalCents}`),
  ],
);

export const customerInvoices = sqliteTable(
  "customer_invoices",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    customerId: text("customer_id").notNull().references(() => bookloqContacts.id),
    invoiceNumber: text("invoice_number").notNull(),
    invoiceDate: text("invoice_date").notNull(),
    dueDate: text("due_date").notNull(),
    status: text("status", { enum: ["draft", "approved", "sent", "viewed", "due", "partially_paid", "paid", "overdue", "disputed", "written_off", "void"] }).notNull().default("draft"),
    subtotalCents: integer("subtotal_cents").notNull(),
    taxCents: integer("tax_cents").notNull().default(0),
    totalCents: integer("total_cents").notNull(),
    paidCents: integer("paid_cents").notNull().default(0),
    currency: text("currency").notNull().default("CAD"),
    locationRef: text("location_ref").notNull().default("all"),
    journalEntryId: text("journal_entry_id").references(() => journalEntries.id),
    demoRecord: integer("demo_record", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("customer_invoices_workspace_number_unique").on(table.organizationId, table.invoiceNumber),
    index("customer_invoices_workspace_due_idx").on(table.organizationId, table.dueDate, table.status),
    check("customer_invoices_amount_check", sql`${table.subtotalCents} >= 0 and ${table.taxCents} >= 0 and ${table.totalCents} = ${table.subtotalCents} + ${table.taxCents} and ${table.paidCents} >= 0 and ${table.paidCents} <= ${table.totalCents}`),
  ],
);

export const bookloqAlerts = sqliteTable(
  "bookloq_alerts",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    severity: text("severity", { enum: ["critical", "attention", "opportunity", "informational"] }).notNull(),
    alertType: text("alert_type").notNull(),
    title: text("title").notNull(),
    explanation: text("explanation").notNull(),
    dollarImpactCents: integer("dollar_impact_cents"),
    confidence: text("confidence", { enum: ["high", "medium", "low"] }).notNull(),
    supportingRecordsJson: text("supporting_records_json").notNull().default("[]"),
    recommendedAction: text("recommended_action").notNull(),
    assignedUserId: text("assigned_user_id").references(() => users.id),
    dueDate: text("due_date"),
    status: text("status", { enum: ["open", "in_progress", "resolved", "dismissed"] }).notNull().default("open"),
    resolutionHistoryJson: text("resolution_history_json").notNull().default("[]"),
    demoRecord: integer("demo_record", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    index("bookloq_alerts_workspace_status_idx").on(table.organizationId, table.status, table.severity),
    check("bookloq_alerts_severity_check", sql`${table.severity} in ('critical', 'attention', 'opportunity', 'informational')`),
    check("bookloq_alerts_confidence_check", sql`${table.confidence} in ('high', 'medium', 'low')`),
    check("bookloq_alerts_status_check", sql`${table.status} in ('open', 'in_progress', 'resolved', 'dismissed')`),
  ],
);

export const bookloqBudgets = sqliteTable(
  "bookloq_budgets",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    accountId: text("account_id").notNull().references(() => financialAccounts.id),
    periodStart: text("period_start").notNull(),
    periodEnd: text("period_end").notNull(),
    locationRef: text("location_ref").notNull().default("all"),
    departmentRef: text("department_ref").notNull().default("all"),
    budgetCents: integer("budget_cents").notNull(),
    committedCents: integer("committed_cents").notNull().default(0),
    forecastCents: integer("forecast_cents").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("bookloq_budgets_scope_unique").on(table.organizationId, table.accountId, table.periodStart, table.periodEnd, table.locationRef, table.departmentRef),
    check("bookloq_budgets_amount_check", sql`${table.budgetCents} >= 0 and ${table.committedCents} >= 0 and ${table.forecastCents} >= 0`),
  ],
);

export const monthEndItems = sqliteTable(
  "month_end_items",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
    periodId: text("period_id").notNull().references(() => accountingPeriods.id, { onDelete: "cascade" }),
    itemKey: text("item_key").notNull(),
    title: text("title").notNull(),
    status: text("status", { enum: ["not_started", "in_progress", "blocked", "complete"] }).notNull().default("not_started"),
    assignedUserId: text("assigned_user_id").references(() => users.id),
    dueDate: text("due_date"),
    blocker: text("blocker").notNull().default(""),
    completedAt: integer("completed_at", { mode: "timestamp" }),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    uniqueIndex("month_end_items_period_key_unique").on(table.periodId, table.itemKey),
    index("month_end_items_workspace_status_idx").on(table.organizationId, table.status),
    check("month_end_items_status_check", sql`${table.status} in ('not_started', 'in_progress', 'blocked', 'complete')`),
  ],
);

export const auditEvents = sqliteTable(
  "audit_events",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").references(() => workspaces.id, { onDelete: "set null" }),
    actorUserId: text("actor_user_id").references(() => users.id, { onDelete: "set null" }),
    action: text("action").notNull(),
    resourceType: text("resource_type").notNull(),
    resourceId: text("resource_id"),
    outcome: text("outcome", { enum: ["success", "failure"] }).notNull(),
    requestId: text("request_id").notNull(),
    sourceHash: text("source_hash"),
    detailsJson: text("details_json").notNull().default("{}"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    index("audit_events_workspace_created_idx").on(table.organizationId, table.createdAt),
    index("audit_events_actor_created_idx").on(table.actorUserId, table.createdAt),
    check("audit_events_outcome_check", sql`${table.outcome} in ('success', 'failure')`),
  ],
);

export const rateLimitBuckets = sqliteTable("rate_limit_buckets", {
  bucketKey: text("bucket_key").primaryKey(),
  scope: text("scope").notNull(),
  actorHash: text("actor_hash").notNull(),
  windowStart: integer("window_start").notNull(),
  requestCount: integer("request_count").notNull().default(1),
  expiresAt: integer("expires_at").notNull(),
});
