// Loopback-only fictional UI fixture. Never connects to authentication or production records.
import {createServer} from "node:http";
import {readFile} from "node:fs/promises";
import {build} from "esbuild";
import {sampleForecast} from "../domain/forecast-sample.ts";
import {buildThirteenWeekCashFlow} from "../domain/thirteen-week-cash-flow.ts";
const bundle=await build({entryPoints:["tests/fixtures/forecast-preview.tsx"],bundle:true,write:false,format:"esm",platform:"browser",jsx:"automatic",loader:{".css":"empty"},plugins:[{name:"fixture-api",setup(b){b.onResolve({filter:/^\.\/supabase-browser$/},()=>({path:"fixture",namespace:"fixture"}));b.onLoad({filter:/.*/,namespace:"fixture"},()=>({contents:'export const apiFetch=(path,init)=>{const url=new URL(path,location.origin);url.searchParams.set("state",new URLSearchParams(location.search).get("state")||"ready");return fetch(url,init)};'}));}}]});
const css=await readFile("app/forecasting-workspace.css","utf8");
const server=createServer(async(req,res)=>{const url=new URL(req.url,"http://127.0.0.1:5188"),send=(body,type="application/json")=>{res.writeHead(200,{"content-type":type+"; charset=utf-8","cache-control":"no-store"});res.end(type==="application/json"?JSON.stringify(body):body);};
if(url.pathname==="/preview.js")return send(bundle.outputFiles[0].text,"text/javascript");
if(url.pathname==="/api/v1/forecasting"){const report=sampleForecast(url.searchParams.get("horizon")==="28"?28:7);if(url.searchParams.get("state")==="empty"){report.totals={transactions:null,units:null,netSalesCents:null};for(const l of report.locations){l.history=l.history.map(d=>({...d,status:"missing",transactions:null,units:null,netSalesCents:null}));for(const s of Object.values(l.series)){s.available=false;s.total=null;s.low=null;s.high=null;s.points=s.points.map(p=>({...p,value:null,low:null,high:null,state:"unavailable",workload:null}));s.reasons=["Review operating hours and source completeness."];}}}return send({report,capabilities:{configure:true,promotion:true,inventory:true,capacity:true,cash:true,export:true},locations:[{id:"fictional",name:"Sample retail store"}],preferences:{pinned:false,views:[]},runs:[]});}
if(url.pathname==="/api/v1/bookloq"){const asOf=new Date().toISOString().slice(0,10),schedule=[{id:"sample-bill",dueDate:asOf,amountCents:300000,direction:"out",certainty:"confirmed",label:"Fictional supplier bill"}];return send({bookloq:{organization:{currency:"CAD"},planningSchedule:schedule,thirteenWeekCashFlow:buildThirteenWeekCashFlow({asOf,openingCashCents:2000000,safetyThresholdCents:500000,actualTransactions:[],forecastItems:schedule})}});}
if(url.searchParams.has("mobile"))return send('<!doctype html><html><head><title>Forecasting mobile review</title></head><body style="margin:0;background:#dfe7f1"><iframe title="Mobile forecasting" style="border:0;width:390px;height:860px" src="/?state='+ (url.searchParams.get("state")||"ready")+'"></iframe></body></html>',"text/html");
return send('<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width, initial-scale=1"><title>Vanteloq forecasting verification</title><style>*{box-sizing:border-box}body{margin:0;background:#f2f6fb;font-family:Inter,Arial,sans-serif}button,input,select{font:inherit}'+css+'</style></head><body><div style="background:#102947;color:white;padding:13px 28px;font-size:13px">Vanteloq · Local verification · Fictional data only</div><div id="root"></div><script type="module" src="/preview.js"></script></body></html>',"text/html");});
server.listen(5188,"127.0.0.1",()=>console.log("Forecast preview: http://127.0.0.1:5188"));
