export const FEATURE_GUIDES = {
  "retail-intelligence": {
    title: "Retail analytics that explain the change",
    description: "Investigate revenue, category performance, discounts and basket patterns with visible calculations and source records.",
    question: "Sales are down. Which part of the business changed?",
    demo: "/demo#retail",
    lead: "A sales total starts the conversation. Vanteloq helps you follow it into completed purchases, basket value, categories and discounts, so you can decide what to investigate next.",
    steps: [
      ["Use a comparable period", "Choose the location and dates. Confirm that both periods include the intended sources and that imports are complete. A missing day is not evidence that the store had no sales."],
      ["Separate the drivers", "The revenue breakdown separates changes in purchase counts, average purchase value and adjustments. Category contributions help locate the movement. These are numerical contributions, not proof that a promotion, employee or event caused it."],
      ["Inspect products and baskets", "Review units, category revenue, discount reliance and recorded margin. Basket analysis shows observed product and category combinations, sample counts and association measures. A common combination suggests a test; it does not guarantee that a bundle will increase demand."],
      ["Turn the finding into a review", "Ask Vanteloq AI to explain the permitted evidence, create a review task and record the decision. Compare the outcome with the original hypothesis once sufficient new records are available."],
    ],
    calculation: "Gross profit = net sales − recorded product cost. Gross margin = gross profit ÷ net sales. Missing product costs make margin unavailable instead of silently overstating profit.",
    limits: "Product and basket analysis require line-item records. Daily summary imports can support daily totals but do not establish which products were bought together. Customer repeat measures require consistent customer identifiers and sufficient history.",
    resource: "/resources/how-to-calculate-gross-margin-small-business",
    resourceLabel: "Read the gross margin guide",
  },
  "inventory-and-cash": {
    title: "Connect inventory decisions to cash",
    description: "Review stock cover, sell-through, expiry and reorder inputs, then test a proposed purchase against a BookLoQ cash scenario.",
    question: "Which stock needs attention before the next order?",
    demo: "/demo#inventory",
    lead: "Inventory represents both a customer promise and committed cash. Review observed demand, current stock and supplier constraints before deciding what to order.",
    steps: [
      ["Check the stock evidence", "Use a dated stock snapshot, reviewed sales and known product costs. Record or import supported opening stock, receipts, inventory valuation and expiry inputs when the source does not supply them."],
      ["Look at movement and time", "Compare sell-through, turnover and days of stock cover. A slow-moving item may tie up cash, while short stock cover may create a shortage before the next supplier delivery. Seasonal demand and promotions need explicit consideration."],
      ["Review expiry and reorder constraints", "Use lot dates and quantities to prioritize stock at risk. Check lead time, case packs, minimum orders and product demand. A suggested quantity is a review input, not an automatically approved purchase."],
      ["Test the cash impact", "Add the proposed purchase to a BookLoQ cash scenario. Compare confirmed commitments with expected receipts and a cash floor. Keep forecast assumptions separate from the bank balance and posted accounting records."],
    ],
    calculation: "Days of cover = on-hand units ÷ observed units sold per day. Sell-through = units sold ÷ units available for sale. Turnover needs a compatible cost-of-sales period and reviewed average inventory value.",
    limits: "Zero observed demand does not imply infinite certainty about cover. Missing valuation, unknown supplier timing, incomplete imports and unreliable expiry quantities limit the recommendation. Bank-based measures require a verified production connection; Plaid production activation is still pending.",
    resource: "/resources/how-to-track-inventory-small-business",
    resourceLabel: "Read the inventory guide",
  },
  "financial-review": {
    title: "BookLoQ Accounting and Cash Flow for Small Businesses",
    description: "Explore BookLoQ bookkeeping, transaction review, evidence matching, financial statements and 13-week cash flow forecasts. Try a working example without signing up.",
    question: "Can the business afford the next commitment?",
    demo: "/demo#bookloq",
    lead: "Understand profit, review what you owe and plan the next cash commitment. BookLoQ brings bookkeeping, financial statements, transaction review, evidence matching and cash flow forecasting into your Vanteloq workspace.",
    steps: [
      ["Review Bookkeeping and Financial Statements", "Follow posted journals into the trial balance, profit and loss statement and balance sheet. See how revenue, cost of goods sold and other posted expenses contribute to profit. Keep operating sales, payment settlements and ledger revenue separate so the same sale is not counted twice."],
      ["Reconcile Transactions and Prepare Month-End", "Review imported transactions, assign supported categories and match records to bills, invoices or receipts. Use the month-end checklist to track unresolved work. A balanced ledger can still contain missing records or incorrect classifications, so reconcile the evidence and keep your accountant involved."],
      ["Build a 13-Week Cash Flow Forecast", "Start with verified opening cash. Compare confirmed commitments with a separate planning case for expected receipts. Test a proposed stock purchase and inspect the lowest projected balance before approving the spend. Forecast assumptions remain visible, and uncertain receipts do not increase the conservative cash estimate."],
      ["Ask Vanteloq AI About Your Financial Data", "Ask why cash differs from profit, which commitments need review or how to use BookLoQ. AI can explain the financial summaries your role and AI Settings permit it to see. It does not post a journal or approve a payment on your behalf."],
    ],
    calculation: "Assets = liabilities + equity. Period cash movement = cash inflows − cash outflows. Neither gross profit nor an uncollected invoice is the same as cash available to spend.",
    limits: "BookLoQ costs $59 CAD per month on its own, or $39 CAD per month when added to a Vanteloq plan. It does not file tax returns, certify financial statements or replace accounting advice. QuickBooks connectivity remains sandbox-only; check production availability before depending on an external accounting import.",
    resource: "/resources/small-business-cash-flow-management-guide",
    resourceLabel: "Read the cash-flow guide",
  },
} as const;
