export const FEATURE_GUIDES = {
  "retail-intelligence": {
    title: "Retail analytics that explain the change",
    description: "Investigate revenue, category performance, discounts and basket patterns with visible calculations and source records.",
    question: "Sales are down. Which part of the business changed?",
    demo: "/demo#retail",
    lead: "A sales total starts the conversation. Vanteloq helps you follow it into completed purchases, basket value, categories and discounts, so you can decide what to investigate next.",
    steps: [
      ["Use a comparable period", "Choose the location and dates. Confirm that both periods include the intended sources and that imports are complete. A missing day is not evidence that the store had no sales."],
      ["Separate the drivers", "The revenue breakdown separates changes in purchase counts, average purchase value and adjustments. Category contributions help locate the movement. These are numerical contributions, not proof that a promotion, employee or event caused it."],
      ["Inspect products and baskets", "Review units, category revenue, discount reliance and recorded margin. Basket analysis shows observed product and category combinations, sample counts and association measures. A common combination suggests a test; it does not guarantee that a bundle will increase demand."],
      ["Turn the finding into a review", "Ask Vanteloq AI to explain the permitted evidence, create a review task and record the decision. Compare the outcome with the original hypothesis once sufficient new records are available."],
    ],
    calculation: "Gross profit = net sales − recorded product cost. Gross margin = gross profit ÷ net sales. Missing product costs make margin unavailable instead of silently overstating profit.",
    limits: "Product and basket analysis require line-item records. Daily summary imports can support daily totals but do not establish which products were bought together. Customer repeat measures require consistent customer identifiers and sufficient history.",
    resource: "/resources/how-to-calculate-gross-margin-small-business",
    resourceLabel: "Read the gross margin guide",
  },
  "inventory-and-cash": {
    title: "Connect inventory decisions to cash",
    description: "Review stock cover, sell-through, expiry and reorder inputs, then test a proposed purchase against a BookLoQ cash scenario.",
    question: "Which stock needs attention before the next order?",
    demo: "/demo#inventory",
    lead: "Inventory represents both a customer promise and committed cash. Review observed demand, current stock and supplier constraints before deciding what to order.",
    steps: [
      ["Check the stock evidence", "Use a dated stock snapshot, reviewed sales and known product costs. Record or import supported opening stock, receipts, inventory valuation and expiry inputs when the source does not supply them."],
      ["Look at movement and time", "Compare sell-through, turnover and days of stock cover. A slow-moving item may tie up cash, while short stock cover may create a shortage before the next supplier delivery. Seasonal demand and promotions need explicit consideration."],
      ["Review expiry and reorder constraints", "Use lot dates and quantities to prioritize stock at risk. Check lead time, case packs, minimum orders and product demand. A suggested quantity is a review input, not an automatically approved purchase."],
      ["Test the cash impact", "Add the proposed purchase to a BookLoQ cash scenario. Compare confirmed commitments with expected receipts and a cash floor. Keep forecast assumptions separate from the bank balance and posted accounting records."],
    ],
    calculation: "Days of cover = on-hand units ÷ observed units sold per day. Sell-through = units sold ÷ units available for sale. Turnover needs a compatible cost-of-sales period and reviewed average inventory value.",
    limits: "Zero observed demand does not imply infinite certainty about cover. Missing valuation, unknown supplier timing, incomplete imports and unreliable expiry quantities limit the recommendation. Bank-based measures require a verified production connection; Plaid production activation is still pending.",
    resource: "/resources/how-to-track-inventory-small-business",
    resourceLabel: "Read the inventory guide",
  },
  "financial-review": {
    title: "Financial review with the working visible",
    description: "Explore BookLoQ journals, statement checks and 13-week cash planning, with Vanteloq AI to explain permitted financial evidence.",
    question: "Can the business afford the next commitment?",
    demo: "/demo#bookloq",
    lead: "BookLoQ is Vanteloq's optional accounting workspace. Keep journals and financial statements distinct from operating sales reports, then use the relevant evidence to review a decision.",
    steps: [
      ["Organize the financial records", "Review accounts, journals, bills, receivables and supporting documents. Keep the chart of accounts and accounting classifications consistent. Operating revenue and payment settlements are not interchangeable with posted ledger revenue."],
      ["Check arithmetic and reconciliation", "Review journal debits and credits, statement totals and the accounting equation. A balanced ledger can still contain an omitted transaction or an incorrect classification. Reconcile representative records and involve your accountant."],
      ["Model the next 13 weeks", "Separate opening cash, confirmed obligations and expected receipts. Change a proposed purchase or receipt timing to see its effect on cash. An expected receipt is an assumption until it is recorded as received."],
      ["Ask questions with context", "Vanteloq AI can explain permitted statement aggregates, financial checks and cash assumptions. Access depends on your role and AI Settings. Review significant conclusions and preserve human approval for accounting or business decisions."],
    ],
    calculation: "Assets = liabilities + equity. Period cash movement = cash inflows − cash outflows. Neither gross profit nor an uncollected invoice is the same as cash available to spend.",
    limits: "BookLoQ costs $39 CAD per month in addition to a base plan. It does not file tax returns, certify financial statements or replace accounting advice. QuickBooks connectivity remains sandbox-only; check production availability before depending on an external accounting import.",
    resource: "/resources/small-business-cash-flow-management-guide",
    resourceLabel: "Read the cash-flow guide",
  },
} as const;
