import { and, desc, eq } from "drizzle-orm";
import { headers } from "next/headers";
import { getDb } from "../../../db";
import { tasks } from "../../../db/schema";
const organizationId = "supplement-world-newcastle";
async function identity() { return (await headers()).get("oai-authenticated-user-email") ?? "owner@vanteloq.local"; }
export async function GET() { try { const rows = await getDb().select().from(tasks).where(eq(tasks.organizationId, organizationId)).orderBy(desc(tasks.createdAt)); return Response.json({ tasks: rows }); } catch { return Response.json({ error: "The task workspace is being prepared. Please try again shortly." }, { status: 503 }); } }
export async function POST(request: Request) { try { const payload = await request.json() as { title?: string; detail?: string; priority?: "high" | "medium" | "low"; assignee?: string; dueDate?: string }; const title = payload.title?.trim(); if (!title || title.length > 120) return Response.json({ error: "Enter a task title under 120 characters." }, { status: 400 }); const [task] = await getDb().insert(tasks).values({ organizationId, title, detail: payload.detail?.trim() ?? "", priority: payload.priority ?? "medium", assignee: payload.assignee?.trim() || "Hussien", dueDate: payload.dueDate || null, createdBy: await identity() }).returning(); return Response.json({ task }, { status: 201 }); } catch { return Response.json({ error: "The task could not be saved. Please try again." }, { status: 500 }); } }
export async function PATCH(request: Request) { try { const payload = await request.json() as { id?: number; status?: "open" | "in_progress" | "done" }; if (!payload.id || !["open", "in_progress", "done"].includes(payload.status ?? "")) return Response.json({ error: "Invalid task update." }, { status: 400 }); const [task] = await getDb().update(tasks).set({ status: payload.status, updatedAt: new Date() }).where(and(eq(tasks.id, payload.id), eq(tasks.organizationId, organizationId))).returning(); if (!task) return Response.json({ error: "Task not found." }, { status: 404 }); return Response.json({ task }); } catch { return Response.json({ error: "The task could not be updated. Please try again." }, { status: 500 }); } }
