import type { Metadata } from "next";
import Link from "next/link";
import { PLANS, ADDONS } from "../../server/entitlements/catalog";
import ProductBrandLogo from "../product-brand-logo";
import CustomPlanCallout from "../custom-plan-callout";
export const metadata: Metadata = { title: "Vanteloq pricing | Monthly plans and BookLoQ", description: "Compare Vanteloq monthly plans in Canadian dollars, team and location limits, and the optional BookLoQ add-on. Try the product demo before signing up.", alternates: { canonical: "/pricing" }, openGraph: { title: "Vanteloq plans and pricing", description: "Clear monthly pricing for independent retail, with optional BookLoQ.", url: "/pricing" } };
export default function PricingPage() {
  return <div className="public-site demo-page"><header className="demo-page-nav"><Link href="/" aria-label="Vanteloq home"><ProductBrandLogo product="vanteloq"/><strong>Vanteloq</strong></Link><Link href="/demo">Try the demo</Link><Link href="/help">Help centre</Link></header><main className="product-help"><p className="demo-eyebrow">PLANS & PRICING</p><h1>Clarity, including the price.</h1><p>Monthly plans in Canadian dollars. Choose your workspace size, then add BookLoQ if you need the finance workspace. Review taxes and the final total at checkout.</p><div className="public-price-grid">{Object.values(PLANS).map(plan => <article key={plan.key}><h2>{plan.displayName}</h2><strong>${plan.prices.month.amountCents / 100}<small> CAD / month</small></strong><p>{plan.description}</p><ul><li>Up to {plan.limits.activeLocations} active {plan.limits.activeLocations === 1 ? "location" : "locations"}</li><li>Up to {plan.limits.users} team members</li><li>Vanteloq AI access, subject to provider availability</li></ul><Link data-public-event="signup_start" href="/?start=signup">Create a workspace →</Link></article>)}</div><CustomPlanCallout/><section className="public-bookloq-price"><div><p className="demo-eyebrow">OPTIONAL FINANCE WORKSPACE</p><h2>BookLoQ</h2><p>Journals, financial statements, bills, receivables and cash review inside Vanteloq. Requires a base plan and the appropriate finance permissions.</p></div><strong>+${ADDONS.bookloq.prices.month.amountCents / 100}<small> CAD / month</small></strong></section><p>Plans grant access to supported capabilities. Results depend on connected and verified source data. Bank payments, tax filing and unsupported integrations are not included as active services.</p><div className="demo-conversion"><div><h2>Try the decision, before the subscription.</h2><p>No account or payment required for the sample demo.</p></div><Link href="/demo">Explore the demo →</Link></div></main></div>;
}
