import {PLAN_COMPARISON as comparisons} from "../../server/entitlements/presentation";
import type { Metadata } from "next";
import Link from "next/link";
import { PLANS, ADDONS, FREE_PLAN, type FeatureKey } from "../../server/entitlements/catalog";
import PublicPageNav from "../public-page-nav";
import PublicPlanCards from "../public-plan-cards";
import CustomPlanCallout from "../custom-plan-callout";
import PlanFit from "../plan-fit";
import { planSelectionUrl } from "../../shared/plan-selection";
export const metadata: Metadata = { title: "Vanteloq pricing | Monthly plans and BookLoQ", description: "Compare Vanteloq monthly plans and choose BookLoQ as a $39 CAD add-on or a $59 CAD standalone finance workspace.", alternates: { canonical: "/pricing" }, openGraph: { title: "Vanteloq pricing | Monthly plans and BookLoQ", description: "Compare Vanteloq plans and choose BookLoQ with Vanteloq or on its own.", url: "/pricing", type: "website" } };
const vanteloqPlans = [{ ...FREE_PLAN, features: FREE_PLAN.features as readonly FeatureKey[] }, PLANS.starter, PLANS.growth, PLANS.pro] as const;
export default function PricingPage() {
 return <div className="public-site demo-page pricing-page">
 <PublicPageNav/>
 <main className="product-help"><p className="demo-eyebrow">PLANS & PRICING</p><h1>Start with the product that fits.</h1><p>Start with a regular free plan without a card. Free includes two available integrations of your choice. Upgrade for more users and advanced intelligence. Paid prices are in Canadian dollars.</p>
 <div className="pricing-reassurance"><span>Free has no expiry or payment method</span><span>7-day trial on your first paid subscription</span><span>Cancel before renewal</span><Link href="/#connections">Check your integrations first →</Link></div><PlanFit/>
 <PublicPlanCards showStandalone={false}/>
 <section className="plan-comparison" aria-labelledby="comparison-title"><div><p className="demo-eyebrow">COMPARE THE DETAILS</p><h2 id="comparison-title">Compare all plan features</h2><p>Plan access is separate from source availability. Each business connects and reviews its own records.</p></div>
 <div className="plan-table-scroll" role="region" aria-label="Scrollable plan comparison" tabIndex={0}><table><caption>Vanteloq plan features</caption><thead><tr><th scope="col">Capability</th>{vanteloqPlans.map(p=><th scope="col" key={p.key}>{p.displayName}</th>)}</tr></thead><tbody><tr><th scope="row">Active locations</th>{vanteloqPlans.map(p=><td key={p.key}>{p.limits.activeLocations}</td>)}</tr><tr><th scope="row">Team members</th>{vanteloqPlans.map(p=><td key={p.key}>{p.limits.users}</td>)}</tr>{comparisons.map(row=><tr key={row.feature}><th scope="row">{row.label}<small>{row.detail}</small></th>{vanteloqPlans.map(p=><td key={p.key}>{p.features.includes(row.feature)?<span className="plan-included">Included</span>:<span className="plan-not-included">Not included</span>}</td>)}</tr>)}</tbody></table></div><p>All plans include the same account security, privacy controls and accessibility support. AI and processing have request and file-size safeguards; Free includes 10 AI replies and 100 imported or manually entered daily sales records per calendar month, resetting at 00:00 UTC on the first day. Reaching a limit pauses new usage without deleting your records or charging you. Paid plans retain their existing request safeguards with no automatic overage charges. Free includes two available integration providers. Multiple accounts from one provider use one choice. Stripe subscription billing does not use a choice. AI file questions require a paid plan. Connections depend on provider availability and your own account permissions. BookLoQ is a separate purchase.</p></section>
 <section className="public-bookloq-price" aria-labelledby="bookloq-pricing-title"><div><p className="demo-eyebrow">COMMERCE-FIRST FINANCE WORKSPACE</p><h2 id="bookloq-pricing-title">Choose BookLoQ with Vanteloq or on its own.</h2><p>BookLoQ organizes source documents, invoices, transaction review and evidence matching, balanced journals, financial statements and 13-week cash review. It does not file returns, move money or certify that the books are complete.</p><div className="bookloq-price-links"><Link href="/demo#bookloq">Try the fictional cash planning demo →</Link><Link href="/resources/bookloq-vs-traditional-accounting-software">Compare BookLoQ workflows →</Link></div></div><div className="public-bookloq-price-options"><article><span>WITH A VANTELOQ PLAN</span><strong>+${ADDONS.bookloq.prices.month.amountCents/100}<small> CAD / month</small></strong><p>Shares the workspace, permissions and source infrastructure already included with Vanteloq.</p><Link className="bookloq-addon-action" href="#plan-starter">Choose a Vanteloq plan ↑</Link></article><article><span>BOOKLOQ STANDALONE</span><strong>${PLANS.bookloq.prices.month.amountCents/100}<small> CAD / month</small></strong><p>Includes its own secured workspace, source handling, permissions and BookLoQ access.</p><Link data-public-event="plan_selected" href={planSelectionUrl({plan:"bookloq",bookloq:false})}>Try BookLoQ free for 7 days →</Link></article></div></section><CustomPlanCallout/>
 <div className="pricing-questions"><details><summary>Is Free a trial?</summary><p>No. Free is a regular plan with no expiry, no card and no automatic charge. It supports one owner, one location, 100 daily sales records and 10 AI replies per month. Choose two available integrations, or start with CSV or manual daily summaries. Upgrade through Settings &gt; Billing &amp; plans when you need more.</p></details><details><summary>How does the seven-day trial work?</summary><p>Your workspace’s first Vanteloq or standalone BookLoQ subscription includes seven days free. A payment method is required. A BookLoQ add-on selected with your first Vanteloq subscription shares that trial. Stripe shows your first charge date and renewal total before you subscribe. Cancel through Manage Billing before that date to avoid the first charge. Existing subscriptions, returning workspaces and add-ons added to a paid plan do not receive another trial.</p></details><details><summary>Do I need to connect a bank to start?</summary><p>No. Start with a supported sales source or structured CSV import. Bank-based cash measures require an authorized, verified connection. Plaid production activation is still required.</p></details><details><summary>Can I change plans later?</summary><p>Workspace billing opens Stripe’s billing portal for available changes and cancellation. Review the effective date and any prorated charges before confirming a change.</p></details><details><summary>Does this replace my accountant?</summary><p>No. BookLoQ organizes records and checks arithmetic. It does not file tax returns, move bank funds or certify that your books are complete. Keep your accountant involved in accounting and tax decisions.</p></details></div>
 <div className="demo-conversion pricing-demo-conversion"><div><span className="pricing-demo-label">INTERACTIVE, FICTIONAL RECORDS</span><h2>See what your next decision could look like.</h2><p>Change a location or cash assumption, inspect the calculation and follow the result to its source rows.</p></div><Link href="/demo">Explore the demo →</Link></div>
 <footer className="pricing-footer"><Link href="/contact">Contact</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/#connections">Integration availability</Link></footer>
 </main></div>;
}
